/**
 * Copyright © 2026-2026 ThingsBoard, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.thingsboard.client.model;

import javax.annotation.Generated;
import javax.annotation.Nullable;
import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.Arrays;
import java.util.LinkedHashSet;
import java.util.Set;
import org.thingsboard.client.model.ApiFeature;
import org.thingsboard.client.model.ApiUsageStateValue;
import org.thingsboard.client.model.NotificationRuleTriggerConfig;
import org.thingsboard.client.model.NotificationRuleTriggerType;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import org.thingsboard.client.JSON;
import org.thingsboard.client.ApiClient;
/**
 * ApiUsageLimitNotificationRuleTriggerConfig
 */
@JsonPropertyOrder({
  ApiUsageLimitNotificationRuleTriggerConfig.JSON_PROPERTY_API_FEATURES,
  ApiUsageLimitNotificationRuleTriggerConfig.JSON_PROPERTY_NOTIFY_ON
})
@Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.20.0")
@JsonIgnoreProperties(
  value = "triggerType", // ignore manually set triggerType, it will be automatically generated by Jackson during serialization
  allowSetters = true // allows the triggerType to be set during deserialization
)
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "triggerType", visible = true)

public class ApiUsageLimitNotificationRuleTriggerConfig extends NotificationRuleTriggerConfig {
  public static final String JSON_PROPERTY_API_FEATURES = "apiFeatures";
  @Nullable
  private Set<ApiFeature> apiFeatures = new LinkedHashSet<>();

  public static final String JSON_PROPERTY_NOTIFY_ON = "notifyOn";
  @Nullable
  private Set<ApiUsageStateValue> notifyOn = new LinkedHashSet<>();

  public ApiUsageLimitNotificationRuleTriggerConfig() { 
  }

  public ApiUsageLimitNotificationRuleTriggerConfig apiFeatures(@Nullable Set<ApiFeature> apiFeatures) {
    this.apiFeatures = apiFeatures;
    return this;
  }

  public ApiUsageLimitNotificationRuleTriggerConfig addApiFeaturesItem(ApiFeature apiFeaturesItem) {
    if (this.apiFeatures == null) {
      this.apiFeatures = new LinkedHashSet<>();
    }
    this.apiFeatures.add(apiFeaturesItem);
    return this;
  }

  /**
   * Get apiFeatures
   * @return apiFeatures
   */
  @Nullable
  @JsonProperty(value = JSON_PROPERTY_API_FEATURES, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Set<ApiFeature> getApiFeatures() {
    return apiFeatures;
  }


  @JsonDeserialize(as = LinkedHashSet.class)
  @JsonProperty(value = JSON_PROPERTY_API_FEATURES, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setApiFeatures(@Nullable Set<ApiFeature> apiFeatures) {
    this.apiFeatures = apiFeatures;
  }


  public ApiUsageLimitNotificationRuleTriggerConfig notifyOn(@Nullable Set<ApiUsageStateValue> notifyOn) {
    this.notifyOn = notifyOn;
    return this;
  }

  public ApiUsageLimitNotificationRuleTriggerConfig addNotifyOnItem(ApiUsageStateValue notifyOnItem) {
    if (this.notifyOn == null) {
      this.notifyOn = new LinkedHashSet<>();
    }
    this.notifyOn.add(notifyOnItem);
    return this;
  }

  /**
   * Get notifyOn
   * @return notifyOn
   */
  @Nullable
  @JsonProperty(value = JSON_PROPERTY_NOTIFY_ON, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Set<ApiUsageStateValue> getNotifyOn() {
    return notifyOn;
  }


  @JsonDeserialize(as = LinkedHashSet.class)
  @JsonProperty(value = JSON_PROPERTY_NOTIFY_ON, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setNotifyOn(@Nullable Set<ApiUsageStateValue> notifyOn) {
    this.notifyOn = notifyOn;
  }


  /**
   * Return true if this ApiUsageLimitNotificationRuleTriggerConfig object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ApiUsageLimitNotificationRuleTriggerConfig apiUsageLimitNotificationRuleTriggerConfig = (ApiUsageLimitNotificationRuleTriggerConfig) o;
    return Objects.equals(this.apiFeatures, apiUsageLimitNotificationRuleTriggerConfig.apiFeatures) &&
        Objects.equals(this.notifyOn, apiUsageLimitNotificationRuleTriggerConfig.notifyOn) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(apiFeatures, notifyOn, super.hashCode());
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ApiUsageLimitNotificationRuleTriggerConfig {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    apiFeatures: ").append(toIndentedString(apiFeatures)).append("\n");
    sb.append("    notifyOn: ").append(toIndentedString(notifyOn)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `triggerType` to the URL query string
    if (getTriggerType() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%striggerType%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getTriggerType()))));
    }

    // add `apiFeatures` to the URL query string
    if (getApiFeatures() != null) {
      int i = 0;
      for (ApiFeature _item : getApiFeatures()) {
        if (_item != null) {
          joiner.add(String.format(java.util.Locale.ROOT, "%sapiFeatures%s%s=%s", prefix, suffix,
              "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix),
              ApiClient.urlEncode(ApiClient.valueToString(_item))));
        }
        i++;
      }
    }

    // add `notifyOn` to the URL query string
    if (getNotifyOn() != null) {
      int i = 0;
      for (ApiUsageStateValue _item : getNotifyOn()) {
        if (_item != null) {
          joiner.add(String.format(java.util.Locale.ROOT, "%snotifyOn%s%s=%s", prefix, suffix,
              "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix),
              ApiClient.urlEncode(ApiClient.valueToString(_item))));
        }
        i++;
      }
    }

    return joiner.toString();
  }
static {
  // Initialize and register the discriminator mappings.
  Map<String, Class<?>> mappings = new HashMap<String, Class<?>>();
  mappings.put("ApiUsageLimitNotificationRuleTriggerConfig", ApiUsageLimitNotificationRuleTriggerConfig.class);
  JSON.registerDiscriminator(ApiUsageLimitNotificationRuleTriggerConfig.class, "triggerType", mappings);
}
}

