/**
 * Copyright © 2026-2026 ThingsBoard, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.thingsboard.client.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import org.thingsboard.client.model.EventType;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import org.thingsboard.client.JSON;
import org.thingsboard.client.ApiClient;
/**
 * Filter for various event types
 */
@JsonPropertyOrder({
  EventFilter.JSON_PROPERTY_EVENT_TYPE,
  EventFilter.JSON_PROPERTY_NOT_EMPTY
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.20.0")
@JsonIgnoreProperties(
  value = "eventType", // ignore manually set eventType, it will be automatically generated by Jackson during serialization
  allowSetters = true // allows the eventType to be set during deserialization
)
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "eventType", visible = true)
@JsonSubTypes({
  @JsonSubTypes.Type(value = CalculatedFieldDebugEventFilter.class, name = "DEBUG_CALCULATED_FIELD"),
  @JsonSubTypes.Type(value = RuleChainDebugEventFilter.class, name = "DEBUG_RULE_CHAIN"),
  @JsonSubTypes.Type(value = RuleNodeDebugEventFilter.class, name = "DEBUG_RULE_NODE"),
  @JsonSubTypes.Type(value = ErrorEventFilter.class, name = "ERROR"),
  @JsonSubTypes.Type(value = LifeCycleEventFilter.class, name = "LC_EVENT"),
  @JsonSubTypes.Type(value = StatisticsEventFilter.class, name = "STATS"),
})

public class EventFilter {
  public static final String JSON_PROPERTY_EVENT_TYPE = "eventType";
  @javax.annotation.Nonnull
  private EventType eventType;

  public static final String JSON_PROPERTY_NOT_EMPTY = "notEmpty";
  @javax.annotation.Nullable
  private Boolean notEmpty;

  public EventFilter() { 
  }

  public EventFilter eventType(@javax.annotation.Nonnull EventType eventType) {
    this.eventType = eventType;
    return this;
  }

  /**
   * String value representing the event type
   * @return eventType
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_EVENT_TYPE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public EventType getEventType() {
    return eventType;
  }


  @JsonProperty(value = JSON_PROPERTY_EVENT_TYPE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setEventType(@javax.annotation.Nonnull EventType eventType) {
    this.eventType = eventType;
  }


  public EventFilter notEmpty(@javax.annotation.Nullable Boolean notEmpty) {
    this.notEmpty = notEmpty;
    return this;
  }

  /**
   * Get notEmpty
   * @return notEmpty
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_NOT_EMPTY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Boolean getNotEmpty() {
    return notEmpty;
  }


  @JsonProperty(value = JSON_PROPERTY_NOT_EMPTY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setNotEmpty(@javax.annotation.Nullable Boolean notEmpty) {
    this.notEmpty = notEmpty;
  }


  /**
   * Return true if this EventFilter object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EventFilter eventFilter = (EventFilter) o;
    return Objects.equals(this.eventType, eventFilter.eventType) &&
        Objects.equals(this.notEmpty, eventFilter.notEmpty);
  }

  @Override
  public int hashCode() {
    return Objects.hash(eventType, notEmpty);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EventFilter {\n");
    sb.append("    eventType: ").append(toIndentedString(eventType)).append("\n");
    sb.append("    notEmpty: ").append(toIndentedString(notEmpty)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `eventType` to the URL query string
    if (getEventType() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%seventType%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getEventType()))));
    }

    // add `notEmpty` to the URL query string
    if (getNotEmpty() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%snotEmpty%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getNotEmpty()))));
    }

    return joiner.toString();
  }
static {
  // Initialize and register the discriminator mappings.
  Map<String, Class<?>> mappings = new HashMap<String, Class<?>>();
  mappings.put("DEBUG_CALCULATED_FIELD", CalculatedFieldDebugEventFilter.class);
  mappings.put("DEBUG_RULE_CHAIN", RuleChainDebugEventFilter.class);
  mappings.put("DEBUG_RULE_NODE", RuleNodeDebugEventFilter.class);
  mappings.put("ERROR", ErrorEventFilter.class);
  mappings.put("LC_EVENT", LifeCycleEventFilter.class);
  mappings.put("STATS", StatisticsEventFilter.class);
  mappings.put("EventFilter", EventFilter.class);
  JSON.registerDiscriminator(EventFilter.class, "eventType", mappings);
}
}

