/**
 * Copyright © 2026-2026 ThingsBoard, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.thingsboard.client.model;

import javax.annotation.Generated;
import javax.annotation.Nullable;
import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.thingsboard.client.model.EntityAlias;
import org.thingsboard.client.model.Filter;
import org.thingsboard.client.model.HeaderFooter;
import org.thingsboard.client.model.Insets;
import org.thingsboard.client.model.PageOrientation;
import org.thingsboard.client.model.PageSize;
import org.thingsboard.client.model.ReportComponent;
import org.thingsboard.client.model.ReportTemplateConfig;
import org.thingsboard.client.model.TbReportFormat;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import org.thingsboard.client.JSON;
import org.thingsboard.client.ApiClient;
/**
 * PdfReportTemplateConfig
 */
@JsonPropertyOrder({
  PdfReportTemplateConfig.JSON_PROPERTY_FOOTER,
  PdfReportTemplateConfig.JSON_PROPERTY_HEADER,
  PdfReportTemplateConfig.JSON_PROPERTY_PAGE_BACKGROUND,
  PdfReportTemplateConfig.JSON_PROPERTY_PAGE_MARGINS,
  PdfReportTemplateConfig.JSON_PROPERTY_PAGE_ORIENTATION,
  PdfReportTemplateConfig.JSON_PROPERTY_PAGE_SIZE
})
@Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.20.0")
@JsonIgnoreProperties(
  value = "format", // ignore manually set format, it will be automatically generated by Jackson during serialization
  allowSetters = true // allows the format to be set during deserialization
)
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "format", visible = true)

public class PdfReportTemplateConfig extends ReportTemplateConfig {
  public static final String JSON_PROPERTY_FOOTER = "footer";
  @Nullable
  private HeaderFooter footer;

  public static final String JSON_PROPERTY_HEADER = "header";
  @Nullable
  private HeaderFooter header;

  public static final String JSON_PROPERTY_PAGE_BACKGROUND = "pageBackground";
  @Nullable
  private String pageBackground;

  public static final String JSON_PROPERTY_PAGE_MARGINS = "pageMargins";
  @Nullable
  private Insets pageMargins;

  public static final String JSON_PROPERTY_PAGE_ORIENTATION = "pageOrientation";
  @Nullable
  private PageOrientation pageOrientation;

  public static final String JSON_PROPERTY_PAGE_SIZE = "pageSize";
  @Nullable
  private PageSize pageSize;

  public PdfReportTemplateConfig() { 
  }

  public PdfReportTemplateConfig footer(@Nullable HeaderFooter footer) {
    this.footer = footer;
    return this;
  }

  /**
   * Get footer
   * @return footer
   */
  @Nullable
  @JsonProperty(value = JSON_PROPERTY_FOOTER, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public HeaderFooter getFooter() {
    return footer;
  }


  @JsonProperty(value = JSON_PROPERTY_FOOTER, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFooter(@Nullable HeaderFooter footer) {
    this.footer = footer;
  }


  public PdfReportTemplateConfig header(@Nullable HeaderFooter header) {
    this.header = header;
    return this;
  }

  /**
   * Get header
   * @return header
   */
  @Nullable
  @JsonProperty(value = JSON_PROPERTY_HEADER, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public HeaderFooter getHeader() {
    return header;
  }


  @JsonProperty(value = JSON_PROPERTY_HEADER, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setHeader(@Nullable HeaderFooter header) {
    this.header = header;
  }


  public PdfReportTemplateConfig pageBackground(@Nullable String pageBackground) {
    this.pageBackground = pageBackground;
    return this;
  }

  /**
   * Get pageBackground
   * @return pageBackground
   */
  @Nullable
  @JsonProperty(value = JSON_PROPERTY_PAGE_BACKGROUND, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getPageBackground() {
    return pageBackground;
  }


  @JsonProperty(value = JSON_PROPERTY_PAGE_BACKGROUND, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPageBackground(@Nullable String pageBackground) {
    this.pageBackground = pageBackground;
  }


  public PdfReportTemplateConfig pageMargins(@Nullable Insets pageMargins) {
    this.pageMargins = pageMargins;
    return this;
  }

  /**
   * Get pageMargins
   * @return pageMargins
   */
  @Nullable
  @JsonProperty(value = JSON_PROPERTY_PAGE_MARGINS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Insets getPageMargins() {
    return pageMargins;
  }


  @JsonProperty(value = JSON_PROPERTY_PAGE_MARGINS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPageMargins(@Nullable Insets pageMargins) {
    this.pageMargins = pageMargins;
  }


  public PdfReportTemplateConfig pageOrientation(@Nullable PageOrientation pageOrientation) {
    this.pageOrientation = pageOrientation;
    return this;
  }

  /**
   * Get pageOrientation
   * @return pageOrientation
   */
  @Nullable
  @JsonProperty(value = JSON_PROPERTY_PAGE_ORIENTATION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public PageOrientation getPageOrientation() {
    return pageOrientation;
  }


  @JsonProperty(value = JSON_PROPERTY_PAGE_ORIENTATION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPageOrientation(@Nullable PageOrientation pageOrientation) {
    this.pageOrientation = pageOrientation;
  }


  public PdfReportTemplateConfig pageSize(@Nullable PageSize pageSize) {
    this.pageSize = pageSize;
    return this;
  }

  /**
   * Get pageSize
   * @return pageSize
   */
  @Nullable
  @JsonProperty(value = JSON_PROPERTY_PAGE_SIZE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public PageSize getPageSize() {
    return pageSize;
  }


  @JsonProperty(value = JSON_PROPERTY_PAGE_SIZE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPageSize(@Nullable PageSize pageSize) {
    this.pageSize = pageSize;
  }


  @Override
  public PdfReportTemplateConfig namePattern(@Nullable String namePattern) {
    this.setNamePattern(namePattern);
    return this;
  }

  @Override
  public PdfReportTemplateConfig timeDataPattern(@Nullable String timeDataPattern) {
    this.setTimeDataPattern(timeDataPattern);
    return this;
  }

  @Override
  public PdfReportTemplateConfig entityAliases(@Nullable List<EntityAlias> entityAliases) {
    this.setEntityAliases(entityAliases);
    return this;
  }

  @Override
  public PdfReportTemplateConfig filters(@Nullable List<Filter> filters) {
    this.setFilters(filters);
    return this;
  }

  @Override
  public PdfReportTemplateConfig components(@Nullable List<ReportComponent> components) {
    this.setComponents(components);
    return this;
  }

  /**
   * Return true if this PdfReportTemplateConfig object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PdfReportTemplateConfig pdfReportTemplateConfig = (PdfReportTemplateConfig) o;
    return Objects.equals(this.footer, pdfReportTemplateConfig.footer) &&
        Objects.equals(this.header, pdfReportTemplateConfig.header) &&
        Objects.equals(this.pageBackground, pdfReportTemplateConfig.pageBackground) &&
        Objects.equals(this.pageMargins, pdfReportTemplateConfig.pageMargins) &&
        Objects.equals(this.pageOrientation, pdfReportTemplateConfig.pageOrientation) &&
        Objects.equals(this.pageSize, pdfReportTemplateConfig.pageSize) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(footer, header, pageBackground, pageMargins, pageOrientation, pageSize, super.hashCode());
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PdfReportTemplateConfig {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    footer: ").append(toIndentedString(footer)).append("\n");
    sb.append("    header: ").append(toIndentedString(header)).append("\n");
    sb.append("    pageBackground: ").append(toIndentedString(pageBackground)).append("\n");
    sb.append("    pageMargins: ").append(toIndentedString(pageMargins)).append("\n");
    sb.append("    pageOrientation: ").append(toIndentedString(pageOrientation)).append("\n");
    sb.append("    pageSize: ").append(toIndentedString(pageSize)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `namePattern` to the URL query string
    if (getNamePattern() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%snamePattern%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getNamePattern()))));
    }

    // add `timeDataPattern` to the URL query string
    if (getTimeDataPattern() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%stimeDataPattern%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getTimeDataPattern()))));
    }

    // add `format` to the URL query string
    if (getFormat() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sformat%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getFormat()))));
    }

    // add `entityAliases` to the URL query string
    if (getEntityAliases() != null) {
      for (int i = 0; i < getEntityAliases().size(); i++) {
        if (getEntityAliases().get(i) != null) {
          joiner.add(getEntityAliases().get(i).toUrlQueryString(String.format(java.util.Locale.ROOT, "%sentityAliases%s%s", prefix, suffix,
          "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix))));
        }
      }
    }

    // add `filters` to the URL query string
    if (getFilters() != null) {
      for (int i = 0; i < getFilters().size(); i++) {
        if (getFilters().get(i) != null) {
          joiner.add(getFilters().get(i).toUrlQueryString(String.format(java.util.Locale.ROOT, "%sfilters%s%s", prefix, suffix,
          "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix))));
        }
      }
    }

    // add `components` to the URL query string
    if (getComponents() != null) {
      for (int i = 0; i < getComponents().size(); i++) {
        if (getComponents().get(i) != null) {
          joiner.add(getComponents().get(i).toUrlQueryString(String.format(java.util.Locale.ROOT, "%scomponents%s%s", prefix, suffix,
          "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix))));
        }
      }
    }

    // add `footer` to the URL query string
    if (getFooter() != null) {
      joiner.add(getFooter().toUrlQueryString(prefix + "footer" + suffix));
    }

    // add `header` to the URL query string
    if (getHeader() != null) {
      joiner.add(getHeader().toUrlQueryString(prefix + "header" + suffix));
    }

    // add `pageBackground` to the URL query string
    if (getPageBackground() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%spageBackground%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getPageBackground()))));
    }

    // add `pageMargins` to the URL query string
    if (getPageMargins() != null) {
      joiner.add(getPageMargins().toUrlQueryString(prefix + "pageMargins" + suffix));
    }

    // add `pageOrientation` to the URL query string
    if (getPageOrientation() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%spageOrientation%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getPageOrientation()))));
    }

    // add `pageSize` to the URL query string
    if (getPageSize() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%spageSize%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getPageSize()))));
    }

    return joiner.toString();
  }
static {
  // Initialize and register the discriminator mappings.
  Map<String, Class<?>> mappings = new HashMap<String, Class<?>>();
  mappings.put("PdfReportTemplateConfig", PdfReportTemplateConfig.class);
  JSON.registerDiscriminator(PdfReportTemplateConfig.class, "format", mappings);
}
}

