/**
 * Copyright © 2026-2026 ThingsBoard, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.thingsboard.client.model;

import javax.annotation.Generated;
import javax.annotation.Nonnull;
import javax.annotation.Nullable;
import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import org.thingsboard.client.model.AlarmConditionSpec;
import org.thingsboard.client.model.FilterPredicateValueInteger;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import org.thingsboard.client.JSON;
import org.thingsboard.client.ApiClient;
/**
 * RepeatingAlarmConditionSpec
 */
@JsonPropertyOrder({
  RepeatingAlarmConditionSpec.JSON_PROPERTY_PREDICATE
})
@Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.20.0")
@JsonIgnoreProperties(
  value = "type", // ignore manually set type, it will be automatically generated by Jackson during serialization
  allowSetters = true // allows the type to be set during deserialization
)
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "type", visible = true)

public class RepeatingAlarmConditionSpec extends AlarmConditionSpec {
  public static final String JSON_PROPERTY_PREDICATE = "predicate";
  @Nullable
  private FilterPredicateValueInteger predicate;

  public RepeatingAlarmConditionSpec() { 
  }

  public RepeatingAlarmConditionSpec predicate(@Nullable FilterPredicateValueInteger predicate) {
    this.predicate = predicate;
    return this;
  }

  /**
   * Repeating predicate
   * @return predicate
   */
  @Nullable
  @JsonProperty(value = JSON_PROPERTY_PREDICATE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public FilterPredicateValueInteger getPredicate() {
    return predicate;
  }


  @JsonProperty(value = JSON_PROPERTY_PREDICATE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPredicate(@Nullable FilterPredicateValueInteger predicate) {
    this.predicate = predicate;
  }


  @Override
  public RepeatingAlarmConditionSpec type(@Nonnull String type) {
    this.setType(type);
    return this;
  }

  /**
   * Return true if this RepeatingAlarmConditionSpec object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RepeatingAlarmConditionSpec repeatingAlarmConditionSpec = (RepeatingAlarmConditionSpec) o;
    return Objects.equals(this.predicate, repeatingAlarmConditionSpec.predicate) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(predicate, super.hashCode());
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RepeatingAlarmConditionSpec {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    predicate: ").append(toIndentedString(predicate)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `type` to the URL query string
    if (getType() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%stype%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getType()))));
    }

    // add `predicate` to the URL query string
    if (getPredicate() != null) {
      joiner.add(getPredicate().toUrlQueryString(prefix + "predicate" + suffix));
    }

    return joiner.toString();
  }
static {
  // Initialize and register the discriminator mappings.
  Map<String, Class<?>> mappings = new HashMap<String, Class<?>>();
  mappings.put("RepeatingAlarmConditionSpec", RepeatingAlarmConditionSpec.class);
  JSON.registerDiscriminator(RepeatingAlarmConditionSpec.class, "type", mappings);
}
}

