/**
 * Copyright © 2026-2026 ThingsBoard, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.thingsboard.client.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import org.thingsboard.client.model.EventFilter;
import org.thingsboard.client.model.EventType;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import org.thingsboard.client.JSON;
import org.thingsboard.client.ApiClient;
/**
 * RuleChainDebugEventFilter
 */
@JsonPropertyOrder({
  RuleChainDebugEventFilter.JSON_PROPERTY_SERVER,
  RuleChainDebugEventFilter.JSON_PROPERTY_ERROR_STR,
  RuleChainDebugEventFilter.JSON_PROPERTY_MESSAGE,
  RuleChainDebugEventFilter.JSON_PROPERTY_IS_ERROR,
  RuleChainDebugEventFilter.JSON_PROPERTY_ERROR
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.20.0")
@JsonIgnoreProperties(
  value = "eventType", // ignore manually set eventType, it will be automatically generated by Jackson during serialization
  allowSetters = true // allows the eventType to be set during deserialization
)
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "eventType", visible = true)

public class RuleChainDebugEventFilter extends EventFilter {
  public static final String JSON_PROPERTY_SERVER = "server";
  @javax.annotation.Nullable
  private String server;

  public static final String JSON_PROPERTY_ERROR_STR = "errorStr";
  @javax.annotation.Nullable
  private String errorStr;

  public static final String JSON_PROPERTY_MESSAGE = "message";
  @javax.annotation.Nullable
  private String message;

  public static final String JSON_PROPERTY_IS_ERROR = "isError";
  @javax.annotation.Nullable
  private Boolean isError;

  public static final String JSON_PROPERTY_ERROR = "error";
  @javax.annotation.Nullable
  private Boolean error;

  public RuleChainDebugEventFilter() { 
  }

  public RuleChainDebugEventFilter server(@javax.annotation.Nullable String server) {
    this.server = server;
    return this;
  }

  /**
   * String value representing the server name, identifier or ip address where the platform is running
   * @return server
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_SERVER, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getServer() {
    return server;
  }


  @JsonProperty(value = JSON_PROPERTY_SERVER, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setServer(@javax.annotation.Nullable String server) {
    this.server = server;
  }


  public RuleChainDebugEventFilter errorStr(@javax.annotation.Nullable String errorStr) {
    this.errorStr = errorStr;
    return this;
  }

  /**
   * The case insensitive &#39;contains&#39; filter based on error message
   * @return errorStr
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ERROR_STR, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getErrorStr() {
    return errorStr;
  }


  @JsonProperty(value = JSON_PROPERTY_ERROR_STR, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setErrorStr(@javax.annotation.Nullable String errorStr) {
    this.errorStr = errorStr;
  }


  public RuleChainDebugEventFilter message(@javax.annotation.Nullable String message) {
    this.message = message;
    return this;
  }

  /**
   * String value representing the message
   * @return message
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_MESSAGE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getMessage() {
    return message;
  }


  @JsonProperty(value = JSON_PROPERTY_MESSAGE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMessage(@javax.annotation.Nullable String message) {
    this.message = message;
  }


  public RuleChainDebugEventFilter isError(@javax.annotation.Nullable Boolean isError) {
    this.isError = isError;
    return this;
  }

  /**
   * Get isError
   * @return isError
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_IS_ERROR, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Boolean getIsError() {
    return isError;
  }


  @JsonProperty(value = JSON_PROPERTY_IS_ERROR, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIsError(@javax.annotation.Nullable Boolean isError) {
    this.isError = isError;
  }


  public RuleChainDebugEventFilter error(@javax.annotation.Nullable Boolean error) {
    this.error = error;
    return this;
  }

  /**
   * Get error
   * @return error
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ERROR, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Boolean getError() {
    return error;
  }


  @JsonProperty(value = JSON_PROPERTY_ERROR, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setError(@javax.annotation.Nullable Boolean error) {
    this.error = error;
  }


  @Override
  public RuleChainDebugEventFilter eventType(@javax.annotation.Nonnull EventType eventType) {
    this.setEventType(eventType);
    return this;
  }

  @Override
  public RuleChainDebugEventFilter notEmpty(@javax.annotation.Nullable Boolean notEmpty) {
    this.setNotEmpty(notEmpty);
    return this;
  }

  /**
   * Return true if this RuleChainDebugEventFilter object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RuleChainDebugEventFilter ruleChainDebugEventFilter = (RuleChainDebugEventFilter) o;
    return Objects.equals(this.server, ruleChainDebugEventFilter.server) &&
        Objects.equals(this.errorStr, ruleChainDebugEventFilter.errorStr) &&
        Objects.equals(this.message, ruleChainDebugEventFilter.message) &&
        Objects.equals(this.isError, ruleChainDebugEventFilter.isError) &&
        Objects.equals(this.error, ruleChainDebugEventFilter.error) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(server, errorStr, message, isError, error, super.hashCode());
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RuleChainDebugEventFilter {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    server: ").append(toIndentedString(server)).append("\n");
    sb.append("    errorStr: ").append(toIndentedString(errorStr)).append("\n");
    sb.append("    message: ").append(toIndentedString(message)).append("\n");
    sb.append("    isError: ").append(toIndentedString(isError)).append("\n");
    sb.append("    error: ").append(toIndentedString(error)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `eventType` to the URL query string
    if (getEventType() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%seventType%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getEventType()))));
    }

    // add `notEmpty` to the URL query string
    if (getNotEmpty() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%snotEmpty%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getNotEmpty()))));
    }

    // add `server` to the URL query string
    if (getServer() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sserver%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getServer()))));
    }

    // add `errorStr` to the URL query string
    if (getErrorStr() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%serrorStr%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getErrorStr()))));
    }

    // add `message` to the URL query string
    if (getMessage() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%smessage%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getMessage()))));
    }

    // add `isError` to the URL query string
    if (getIsError() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sisError%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getIsError()))));
    }

    // add `error` to the URL query string
    if (getError() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%serror%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getError()))));
    }

    return joiner.toString();
  }
static {
  // Initialize and register the discriminator mappings.
  Map<String, Class<?>> mappings = new HashMap<String, Class<?>>();
  mappings.put("RuleChainDebugEventFilter", RuleChainDebugEventFilter.class);
  JSON.registerDiscriminator(RuleChainDebugEventFilter.class, "eventType", mappings);
}
}

