/**
 * Copyright © 2026-2026 ThingsBoard, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.thingsboard.client.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import java.util.HashMap;
import java.util.Map;
import org.thingsboard.client.model.EntityTypeVersionCreateConfig;
import org.thingsboard.client.model.SyncStrategy;
import org.thingsboard.client.model.VersionCreateRequest;
import org.thingsboard.client.model.VersionCreateRequestType;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import org.thingsboard.client.JSON;
import org.thingsboard.client.ApiClient;
/**
 * ComplexVersionCreateRequest
 */
@JsonPropertyOrder({
  ComplexVersionCreateRequest.JSON_PROPERTY_SYNC_STRATEGY,
  ComplexVersionCreateRequest.JSON_PROPERTY_ENTITY_TYPES
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.20.0")
@JsonIgnoreProperties(
  value = "type", // ignore manually set type, it will be automatically generated by Jackson during serialization
  allowSetters = true // allows the type to be set during deserialization
)
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "type", visible = true)

public class ComplexVersionCreateRequest extends VersionCreateRequest {
  public static final String JSON_PROPERTY_SYNC_STRATEGY = "syncStrategy";
  @javax.annotation.Nullable
  private SyncStrategy syncStrategy;

  public static final String JSON_PROPERTY_ENTITY_TYPES = "entityTypes";
  @javax.annotation.Nullable
  private Map<String, EntityTypeVersionCreateConfig> entityTypes = new HashMap<>();

  public ComplexVersionCreateRequest() { 
  }

  public ComplexVersionCreateRequest syncStrategy(@javax.annotation.Nullable SyncStrategy syncStrategy) {
    this.syncStrategy = syncStrategy;
    return this;
  }

  /**
   * Get syncStrategy
   * @return syncStrategy
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_SYNC_STRATEGY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public SyncStrategy getSyncStrategy() {
    return syncStrategy;
  }


  @JsonProperty(value = JSON_PROPERTY_SYNC_STRATEGY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSyncStrategy(@javax.annotation.Nullable SyncStrategy syncStrategy) {
    this.syncStrategy = syncStrategy;
  }


  public ComplexVersionCreateRequest entityTypes(@javax.annotation.Nullable Map<String, EntityTypeVersionCreateConfig> entityTypes) {
    this.entityTypes = entityTypes;
    return this;
  }

  public ComplexVersionCreateRequest putEntityTypesItem(String key, EntityTypeVersionCreateConfig entityTypesItem) {
    if (this.entityTypes == null) {
      this.entityTypes = new HashMap<>();
    }
    this.entityTypes.put(key, entityTypesItem);
    return this;
  }

  /**
   * Get entityTypes
   * @return entityTypes
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ENTITY_TYPES, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Map<String, EntityTypeVersionCreateConfig> getEntityTypes() {
    return entityTypes;
  }


  @JsonProperty(value = JSON_PROPERTY_ENTITY_TYPES, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEntityTypes(@javax.annotation.Nullable Map<String, EntityTypeVersionCreateConfig> entityTypes) {
    this.entityTypes = entityTypes;
  }


  @Override
  public ComplexVersionCreateRequest versionName(@javax.annotation.Nullable String versionName) {
    this.setVersionName(versionName);
    return this;
  }

  @Override
  public ComplexVersionCreateRequest branch(@javax.annotation.Nullable String branch) {
    this.setBranch(branch);
    return this;
  }

  @Override
  public ComplexVersionCreateRequest type(@javax.annotation.Nonnull VersionCreateRequestType type) {
    this.setType(type);
    return this;
  }

  /**
   * Return true if this ComplexVersionCreateRequest object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ComplexVersionCreateRequest complexVersionCreateRequest = (ComplexVersionCreateRequest) o;
    return Objects.equals(this.syncStrategy, complexVersionCreateRequest.syncStrategy) &&
        Objects.equals(this.entityTypes, complexVersionCreateRequest.entityTypes) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(syncStrategy, entityTypes, super.hashCode());
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ComplexVersionCreateRequest {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    syncStrategy: ").append(toIndentedString(syncStrategy)).append("\n");
    sb.append("    entityTypes: ").append(toIndentedString(entityTypes)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `versionName` to the URL query string
    if (getVersionName() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sversionName%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getVersionName()))));
    }

    // add `branch` to the URL query string
    if (getBranch() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sbranch%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getBranch()))));
    }

    // add `type` to the URL query string
    if (getType() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%stype%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getType()))));
    }

    // add `syncStrategy` to the URL query string
    if (getSyncStrategy() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%ssyncStrategy%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getSyncStrategy()))));
    }

    // add `entityTypes` to the URL query string
    if (getEntityTypes() != null) {
      for (String _key : getEntityTypes().keySet()) {
        if (getEntityTypes().get(_key) != null) {
          joiner.add(getEntityTypes().get(_key).toUrlQueryString(String.format(java.util.Locale.ROOT, "%sentityTypes%s%s", prefix, suffix,
              "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, _key, containerSuffix))));
        }
      }
    }

    return joiner.toString();
  }
static {
  // Initialize and register the discriminator mappings.
  Map<String, Class<?>> mappings = new HashMap<String, Class<?>>();
  mappings.put("ComplexVersionCreateRequest", ComplexVersionCreateRequest.class);
  JSON.registerDiscriminator(ComplexVersionCreateRequest.class, "type", mappings);
}
}

