/**
 * Copyright © 2026-2026 ThingsBoard, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.thingsboard.client.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.thingsboard.client.model.CMItemLinkType;
import org.thingsboard.client.model.CMItemType;
import org.thingsboard.client.model.MenuItem;
import org.thingsboard.client.model.MenuItemType;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import org.thingsboard.client.JSON;
import org.thingsboard.client.ApiClient;
/**
 * CustomMenuItem
 */
@JsonPropertyOrder({
  CustomMenuItem.JSON_PROPERTY_NAME,
  CustomMenuItem.JSON_PROPERTY_ICON,
  CustomMenuItem.JSON_PROPERTY_MENU_ITEM_TYPE,
  CustomMenuItem.JSON_PROPERTY_LINK_TYPE,
  CustomMenuItem.JSON_PROPERTY_DASHBOARD_ID,
  CustomMenuItem.JSON_PROPERTY_HIDE_DASHBOARD_TOOLBAR,
  CustomMenuItem.JSON_PROPERTY_URL,
  CustomMenuItem.JSON_PROPERTY_SET_ACCESS_TOKEN,
  CustomMenuItem.JSON_PROPERTY_VISIBLE,
  CustomMenuItem.JSON_PROPERTY_PAGES
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-02-24T16:18:03.556877+02:00[Europe/Kiev]", comments = "Generator version: 7.20.0")
@JsonIgnoreProperties(
  value = "type", // ignore manually set type, it will be automatically generated by Jackson during serialization
  allowSetters = true // allows the type to be set during deserialization
)
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "type", visible = true)

public class CustomMenuItem extends MenuItem {
  public static final String JSON_PROPERTY_NAME = "name";
  @javax.annotation.Nonnull
  private String name;

  public static final String JSON_PROPERTY_ICON = "icon";
  @javax.annotation.Nullable
  private String icon;

  public static final String JSON_PROPERTY_MENU_ITEM_TYPE = "menuItemType";
  @javax.annotation.Nonnull
  private CMItemType menuItemType;

  public static final String JSON_PROPERTY_LINK_TYPE = "linkType";
  @javax.annotation.Nullable
  private CMItemLinkType linkType;

  public static final String JSON_PROPERTY_DASHBOARD_ID = "dashboardId";
  @javax.annotation.Nullable
  private String dashboardId;

  public static final String JSON_PROPERTY_HIDE_DASHBOARD_TOOLBAR = "hideDashboardToolbar";
  @javax.annotation.Nullable
  private Boolean hideDashboardToolbar;

  public static final String JSON_PROPERTY_URL = "url";
  @javax.annotation.Nullable
  private String url;

  public static final String JSON_PROPERTY_SET_ACCESS_TOKEN = "setAccessToken";
  @javax.annotation.Nullable
  private Boolean setAccessToken;

  public static final String JSON_PROPERTY_VISIBLE = "visible";
  @javax.annotation.Nullable
  private Boolean visible;

  public static final String JSON_PROPERTY_PAGES = "pages";
  @javax.annotation.Nullable
  private List<CustomMenuItem> pages = new ArrayList<>();

  public CustomMenuItem() { 
  }

  public CustomMenuItem name(@javax.annotation.Nonnull String name) {
    this.name = name;
    return this;
  }

  /**
   * Name of the menu item
   * @return name
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_NAME, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getName() {
    return name;
  }


  @JsonProperty(value = JSON_PROPERTY_NAME, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setName(@javax.annotation.Nonnull String name) {
    this.name = name;
  }


  public CustomMenuItem icon(@javax.annotation.Nullable String icon) {
    this.icon = icon;
    return this;
  }

  /**
   * URL of the menu item icon. Overrides &#39;materialIcon&#39;
   * @return icon
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ICON, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getIcon() {
    return icon;
  }


  @JsonProperty(value = JSON_PROPERTY_ICON, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIcon(@javax.annotation.Nullable String icon) {
    this.icon = icon;
  }


  public CustomMenuItem menuItemType(@javax.annotation.Nonnull CMItemType menuItemType) {
    this.menuItemType = menuItemType;
    return this;
  }

  /**
   * Type of menu item (LINK or SECTION). LINK type means item has no child items, SECTION type should have at least one child
   * @return menuItemType
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_MENU_ITEM_TYPE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public CMItemType getMenuItemType() {
    return menuItemType;
  }


  @JsonProperty(value = JSON_PROPERTY_MENU_ITEM_TYPE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setMenuItemType(@javax.annotation.Nonnull CMItemType menuItemType) {
    this.menuItemType = menuItemType;
  }


  public CustomMenuItem linkType(@javax.annotation.Nullable CMItemLinkType linkType) {
    this.linkType = linkType;
    return this;
  }

  /**
   * Type of menu item (URL or DASHBOARD)
   * @return linkType
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_LINK_TYPE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public CMItemLinkType getLinkType() {
    return linkType;
  }


  @JsonProperty(value = JSON_PROPERTY_LINK_TYPE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLinkType(@javax.annotation.Nullable CMItemLinkType linkType) {
    this.linkType = linkType;
  }


  public CustomMenuItem dashboardId(@javax.annotation.Nullable String dashboardId) {
    this.dashboardId = dashboardId;
    return this;
  }

  /**
   * Id of the Dashboard to open, when user clicks the menu item
   * @return dashboardId
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_DASHBOARD_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getDashboardId() {
    return dashboardId;
  }


  @JsonProperty(value = JSON_PROPERTY_DASHBOARD_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDashboardId(@javax.annotation.Nullable String dashboardId) {
    this.dashboardId = dashboardId;
  }


  public CustomMenuItem hideDashboardToolbar(@javax.annotation.Nullable Boolean hideDashboardToolbar) {
    this.hideDashboardToolbar = hideDashboardToolbar;
    return this;
  }

  /**
   * Hide the dashboard toolbar
   * @return hideDashboardToolbar
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_HIDE_DASHBOARD_TOOLBAR, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Boolean getHideDashboardToolbar() {
    return hideDashboardToolbar;
  }


  @JsonProperty(value = JSON_PROPERTY_HIDE_DASHBOARD_TOOLBAR, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setHideDashboardToolbar(@javax.annotation.Nullable Boolean hideDashboardToolbar) {
    this.hideDashboardToolbar = hideDashboardToolbar;
  }


  public CustomMenuItem url(@javax.annotation.Nullable String url) {
    this.url = url;
    return this;
  }

  /**
   * URL to open in the iframe, when user clicks the menu item
   * @return url
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_URL, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getUrl() {
    return url;
  }


  @JsonProperty(value = JSON_PROPERTY_URL, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUrl(@javax.annotation.Nullable String url) {
    this.url = url;
  }


  public CustomMenuItem setAccessToken(@javax.annotation.Nullable Boolean setAccessToken) {
    this.setAccessToken = setAccessToken;
    return this;
  }

  /**
   * Set the access token of the current user to a new dashboard
   * @return setAccessToken
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_SET_ACCESS_TOKEN, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Boolean getSetAccessToken() {
    return setAccessToken;
  }


  @JsonProperty(value = JSON_PROPERTY_SET_ACCESS_TOKEN, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSetAccessToken(@javax.annotation.Nullable Boolean setAccessToken) {
    this.setAccessToken = setAccessToken;
  }


  public CustomMenuItem visible(@javax.annotation.Nullable Boolean visible) {
    this.visible = visible;
    return this;
  }

  /**
   * Mark if menu item is visible for user
   * @return visible
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_VISIBLE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Boolean getVisible() {
    return visible;
  }


  @JsonProperty(value = JSON_PROPERTY_VISIBLE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setVisible(@javax.annotation.Nullable Boolean visible) {
    this.visible = visible;
  }


  public CustomMenuItem pages(@javax.annotation.Nullable List<CustomMenuItem> pages) {
    this.pages = pages;
    return this;
  }

  public CustomMenuItem addPagesItem(CustomMenuItem pagesItem) {
    if (this.pages == null) {
      this.pages = new ArrayList<>();
    }
    this.pages.add(pagesItem);
    return this;
  }

  /**
   * List of child menu items
   * @return pages
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PAGES, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public List<CustomMenuItem> getPages() {
    return pages;
  }


  @JsonProperty(value = JSON_PROPERTY_PAGES, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPages(@javax.annotation.Nullable List<CustomMenuItem> pages) {
    this.pages = pages;
  }


  @Override
  public CustomMenuItem type(@javax.annotation.Nonnull MenuItemType type) {
    this.setType(type);
    return this;
  }

  /**
   * Return true if this CustomMenuItem object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CustomMenuItem customMenuItem = (CustomMenuItem) o;
    return Objects.equals(this.name, customMenuItem.name) &&
        Objects.equals(this.icon, customMenuItem.icon) &&
        Objects.equals(this.menuItemType, customMenuItem.menuItemType) &&
        Objects.equals(this.linkType, customMenuItem.linkType) &&
        Objects.equals(this.dashboardId, customMenuItem.dashboardId) &&
        Objects.equals(this.hideDashboardToolbar, customMenuItem.hideDashboardToolbar) &&
        Objects.equals(this.url, customMenuItem.url) &&
        Objects.equals(this.setAccessToken, customMenuItem.setAccessToken) &&
        Objects.equals(this.visible, customMenuItem.visible) &&
        Objects.equals(this.pages, customMenuItem.pages) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, icon, menuItemType, linkType, dashboardId, hideDashboardToolbar, url, setAccessToken, visible, pages, super.hashCode());
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CustomMenuItem {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    icon: ").append(toIndentedString(icon)).append("\n");
    sb.append("    menuItemType: ").append(toIndentedString(menuItemType)).append("\n");
    sb.append("    linkType: ").append(toIndentedString(linkType)).append("\n");
    sb.append("    dashboardId: ").append(toIndentedString(dashboardId)).append("\n");
    sb.append("    hideDashboardToolbar: ").append(toIndentedString(hideDashboardToolbar)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("    setAccessToken: ").append(toIndentedString(setAccessToken)).append("\n");
    sb.append("    visible: ").append(toIndentedString(visible)).append("\n");
    sb.append("    pages: ").append(toIndentedString(pages)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `type` to the URL query string
    if (getType() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%stype%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getType()))));
    }

    // add `visible` to the URL query string
    if (getVisible() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%svisible%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getVisible()))));
    }

    // add `name` to the URL query string
    if (getName() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sname%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getName()))));
    }

    // add `icon` to the URL query string
    if (getIcon() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sicon%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getIcon()))));
    }

    // add `menuItemType` to the URL query string
    if (getMenuItemType() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%smenuItemType%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getMenuItemType()))));
    }

    // add `linkType` to the URL query string
    if (getLinkType() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%slinkType%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getLinkType()))));
    }

    // add `dashboardId` to the URL query string
    if (getDashboardId() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sdashboardId%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getDashboardId()))));
    }

    // add `hideDashboardToolbar` to the URL query string
    if (getHideDashboardToolbar() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%shideDashboardToolbar%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getHideDashboardToolbar()))));
    }

    // add `url` to the URL query string
    if (getUrl() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%surl%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getUrl()))));
    }

    // add `setAccessToken` to the URL query string
    if (getSetAccessToken() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%ssetAccessToken%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getSetAccessToken()))));
    }

    // add `pages` to the URL query string
    if (getPages() != null) {
      for (int i = 0; i < getPages().size(); i++) {
        if (getPages().get(i) != null) {
          joiner.add(getPages().get(i).toUrlQueryString(String.format(java.util.Locale.ROOT, "%spages%s%s", prefix, suffix,
          "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix))));
        }
      }
    }

    return joiner.toString();
  }
static {
  // Initialize and register the discriminator mappings.
  Map<String, Class<?>> mappings = new HashMap<String, Class<?>>();
  mappings.put("CustomMenuItem", CustomMenuItem.class);
  JSON.registerDiscriminator(CustomMenuItem.class, "type", mappings);
}
}

