/**
 * Copyright © 2026-2026 ThingsBoard, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.thingsboard.client.model;

import javax.annotation.Generated;
import javax.annotation.Nonnull;
import javax.annotation.Nullable;
import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import org.thingsboard.client.model.AlarmCondition;
import org.thingsboard.client.model.AlarmConditionExpression;
import org.thingsboard.client.model.AlarmConditionValueAlarmSchedule;
import org.thingsboard.client.model.AlarmConditionValueLong;
import org.thingsboard.client.model.TimeUnit;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import org.thingsboard.client.JSON;
import org.thingsboard.client.ApiClient;
/**
 * DurationAlarmCondition
 */
@JsonPropertyOrder({
  DurationAlarmCondition.JSON_PROPERTY_UNIT,
  DurationAlarmCondition.JSON_PROPERTY_VALUE
})
@Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.20.0")
@JsonIgnoreProperties(
  value = "type", // ignore manually set type, it will be automatically generated by Jackson during serialization
  allowSetters = true // allows the type to be set during deserialization
)
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "type", visible = true)

public class DurationAlarmCondition extends AlarmCondition {
  public static final String JSON_PROPERTY_UNIT = "unit";
  @Nonnull
  private TimeUnit unit;

  public static final String JSON_PROPERTY_VALUE = "value";
  @Nonnull
  private AlarmConditionValueLong value;

  public DurationAlarmCondition() { 
  }

  public DurationAlarmCondition unit(@Nonnull TimeUnit unit) {
    this.unit = unit;
    return this;
  }

  /**
   * Get unit
   * @return unit
   */
  @Nonnull
  @JsonProperty(value = JSON_PROPERTY_UNIT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public TimeUnit getUnit() {
    return unit;
  }


  @JsonProperty(value = JSON_PROPERTY_UNIT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setUnit(@Nonnull TimeUnit unit) {
    this.unit = unit;
  }


  public DurationAlarmCondition value(@Nonnull AlarmConditionValueLong value) {
    this.value = value;
    return this;
  }

  /**
   * Get value
   * @return value
   */
  @Nonnull
  @JsonProperty(value = JSON_PROPERTY_VALUE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public AlarmConditionValueLong getValue() {
    return value;
  }


  @JsonProperty(value = JSON_PROPERTY_VALUE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setValue(@Nonnull AlarmConditionValueLong value) {
    this.value = value;
  }


  @Override
  public DurationAlarmCondition expression(@Nonnull AlarmConditionExpression expression) {
    this.setExpression(expression);
    return this;
  }

  @Override
  public DurationAlarmCondition schedule(@Nullable AlarmConditionValueAlarmSchedule schedule) {
    this.setSchedule(schedule);
    return this;
  }

  /**
   * Return true if this DurationAlarmCondition object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DurationAlarmCondition durationAlarmCondition = (DurationAlarmCondition) o;
    return Objects.equals(this.unit, durationAlarmCondition.unit) &&
        Objects.equals(this.value, durationAlarmCondition.value) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(unit, value, super.hashCode());
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DurationAlarmCondition {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    unit: ").append(toIndentedString(unit)).append("\n");
    sb.append("    value: ").append(toIndentedString(value)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `expression` to the URL query string
    if (getExpression() != null) {
      joiner.add(getExpression().toUrlQueryString(prefix + "expression" + suffix));
    }

    // add `schedule` to the URL query string
    if (getSchedule() != null) {
      joiner.add(getSchedule().toUrlQueryString(prefix + "schedule" + suffix));
    }

    // add `type` to the URL query string
    if (getType() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%stype%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getType()))));
    }

    // add `unit` to the URL query string
    if (getUnit() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sunit%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getUnit()))));
    }

    // add `value` to the URL query string
    if (getValue() != null) {
      joiner.add(getValue().toUrlQueryString(prefix + "value" + suffix));
    }

    return joiner.toString();
  }
static {
  // Initialize and register the discriminator mappings.
  Map<String, Class<?>> mappings = new HashMap<String, Class<?>>();
  mappings.put("DurationAlarmCondition", DurationAlarmCondition.class);
  JSON.registerDiscriminator(DurationAlarmCondition.class, "type", mappings);
}
}

