/**
 * Copyright © 2026-2026 ThingsBoard, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.thingsboard.client.model;

import javax.annotation.Generated;
import javax.annotation.Nonnull;
import javax.annotation.Nullable;
import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import org.thingsboard.client.model.EntityFilter;
import org.thingsboard.client.model.EntityType;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import org.thingsboard.client.JSON;
import org.thingsboard.client.ApiClient;
/**
 * EntityGroupFilter
 */
@JsonPropertyOrder({
  EntityGroupFilter.JSON_PROPERTY_GROUP_TYPE,
  EntityGroupFilter.JSON_PROPERTY_ENTITY_GROUP,
  EntityGroupFilter.JSON_PROPERTY_GROUP_STATE_ENTITY,
  EntityGroupFilter.JSON_PROPERTY_DEFAULT_STATE_GROUP_TYPE,
  EntityGroupFilter.JSON_PROPERTY_DEFAULT_STATE_ENTITY_GROUP
})
@Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.20.0")
@JsonIgnoreProperties(
  value = "type", // ignore manually set type, it will be automatically generated by Jackson during serialization
  allowSetters = true // allows the type to be set during deserialization
)
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "type", visible = true)

public class EntityGroupFilter extends EntityFilter {
  public static final String JSON_PROPERTY_GROUP_TYPE = "groupType";
  @Nullable
  private EntityType groupType;

  public static final String JSON_PROPERTY_ENTITY_GROUP = "entityGroup";
  @Nullable
  private String entityGroup;

  public static final String JSON_PROPERTY_GROUP_STATE_ENTITY = "groupStateEntity";
  @Nullable
  private Boolean groupStateEntity;

  public static final String JSON_PROPERTY_DEFAULT_STATE_GROUP_TYPE = "defaultStateGroupType";
  @Nullable
  private EntityType defaultStateGroupType;

  public static final String JSON_PROPERTY_DEFAULT_STATE_ENTITY_GROUP = "defaultStateEntityGroup";
  @Nullable
  private String defaultStateEntityGroup;

  public EntityGroupFilter() { 
  }

  public EntityGroupFilter groupType(@Nullable EntityType groupType) {
    this.groupType = groupType;
    return this;
  }

  /**
   * Get groupType
   * @return groupType
   */
  @Nullable
  @JsonProperty(value = JSON_PROPERTY_GROUP_TYPE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public EntityType getGroupType() {
    return groupType;
  }


  @JsonProperty(value = JSON_PROPERTY_GROUP_TYPE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setGroupType(@Nullable EntityType groupType) {
    this.groupType = groupType;
  }


  public EntityGroupFilter entityGroup(@Nullable String entityGroup) {
    this.entityGroup = entityGroup;
    return this;
  }

  /**
   * Get entityGroup
   * @return entityGroup
   */
  @Nullable
  @JsonProperty(value = JSON_PROPERTY_ENTITY_GROUP, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getEntityGroup() {
    return entityGroup;
  }


  @JsonProperty(value = JSON_PROPERTY_ENTITY_GROUP, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEntityGroup(@Nullable String entityGroup) {
    this.entityGroup = entityGroup;
  }


  public EntityGroupFilter groupStateEntity(@Nullable Boolean groupStateEntity) {
    this.groupStateEntity = groupStateEntity;
    return this;
  }

  /**
   * Get groupStateEntity
   * @return groupStateEntity
   */
  @Nullable
  @JsonProperty(value = JSON_PROPERTY_GROUP_STATE_ENTITY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Boolean getGroupStateEntity() {
    return groupStateEntity;
  }


  @JsonProperty(value = JSON_PROPERTY_GROUP_STATE_ENTITY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setGroupStateEntity(@Nullable Boolean groupStateEntity) {
    this.groupStateEntity = groupStateEntity;
  }


  public EntityGroupFilter defaultStateGroupType(@Nullable EntityType defaultStateGroupType) {
    this.defaultStateGroupType = defaultStateGroupType;
    return this;
  }

  /**
   * Get defaultStateGroupType
   * @return defaultStateGroupType
   */
  @Nullable
  @JsonProperty(value = JSON_PROPERTY_DEFAULT_STATE_GROUP_TYPE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public EntityType getDefaultStateGroupType() {
    return defaultStateGroupType;
  }


  @JsonProperty(value = JSON_PROPERTY_DEFAULT_STATE_GROUP_TYPE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDefaultStateGroupType(@Nullable EntityType defaultStateGroupType) {
    this.defaultStateGroupType = defaultStateGroupType;
  }


  public EntityGroupFilter defaultStateEntityGroup(@Nullable String defaultStateEntityGroup) {
    this.defaultStateEntityGroup = defaultStateEntityGroup;
    return this;
  }

  /**
   * Get defaultStateEntityGroup
   * @return defaultStateEntityGroup
   */
  @Nullable
  @JsonProperty(value = JSON_PROPERTY_DEFAULT_STATE_ENTITY_GROUP, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getDefaultStateEntityGroup() {
    return defaultStateEntityGroup;
  }


  @JsonProperty(value = JSON_PROPERTY_DEFAULT_STATE_ENTITY_GROUP, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDefaultStateEntityGroup(@Nullable String defaultStateEntityGroup) {
    this.defaultStateEntityGroup = defaultStateEntityGroup;
  }


  @Override
  public EntityGroupFilter type(@Nonnull String type) {
    this.setType(type);
    return this;
  }

  /**
   * Return true if this EntityGroupFilter object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EntityGroupFilter entityGroupFilter = (EntityGroupFilter) o;
    return Objects.equals(this.groupType, entityGroupFilter.groupType) &&
        Objects.equals(this.entityGroup, entityGroupFilter.entityGroup) &&
        Objects.equals(this.groupStateEntity, entityGroupFilter.groupStateEntity) &&
        Objects.equals(this.defaultStateGroupType, entityGroupFilter.defaultStateGroupType) &&
        Objects.equals(this.defaultStateEntityGroup, entityGroupFilter.defaultStateEntityGroup) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(groupType, entityGroup, groupStateEntity, defaultStateGroupType, defaultStateEntityGroup, super.hashCode());
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EntityGroupFilter {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    groupType: ").append(toIndentedString(groupType)).append("\n");
    sb.append("    entityGroup: ").append(toIndentedString(entityGroup)).append("\n");
    sb.append("    groupStateEntity: ").append(toIndentedString(groupStateEntity)).append("\n");
    sb.append("    defaultStateGroupType: ").append(toIndentedString(defaultStateGroupType)).append("\n");
    sb.append("    defaultStateEntityGroup: ").append(toIndentedString(defaultStateEntityGroup)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `type` to the URL query string
    if (getType() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%stype%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getType()))));
    }

    // add `groupType` to the URL query string
    if (getGroupType() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sgroupType%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getGroupType()))));
    }

    // add `entityGroup` to the URL query string
    if (getEntityGroup() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sentityGroup%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getEntityGroup()))));
    }

    // add `groupStateEntity` to the URL query string
    if (getGroupStateEntity() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sgroupStateEntity%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getGroupStateEntity()))));
    }

    // add `defaultStateGroupType` to the URL query string
    if (getDefaultStateGroupType() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sdefaultStateGroupType%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getDefaultStateGroupType()))));
    }

    // add `defaultStateEntityGroup` to the URL query string
    if (getDefaultStateEntityGroup() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sdefaultStateEntityGroup%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getDefaultStateEntityGroup()))));
    }

    return joiner.toString();
  }
static {
  // Initialize and register the discriminator mappings.
  Map<String, Class<?>> mappings = new HashMap<String, Class<?>>();
  mappings.put("EntityGroupFilter", EntityGroupFilter.class);
  JSON.registerDiscriminator(EntityGroupFilter.class, "type", mappings);
}
}

