/**
 * Copyright © 2026-2026 ThingsBoard, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.thingsboard.client.model;

import javax.annotation.Generated;
import javax.annotation.Nullable;
import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.thingsboard.client.model.AttributeExportData;
import org.thingsboard.client.model.CalculatedField;
import org.thingsboard.client.model.DeviceGroupOtaPackage;
import org.thingsboard.client.model.EntityExportData;
import org.thingsboard.client.model.EntityRelation;
import org.thingsboard.client.model.EntityType;
import org.thingsboard.client.model.ExportableEntity;
import org.thingsboard.client.model.GroupPermission;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import org.thingsboard.client.JSON;
import org.thingsboard.client.ApiClient;
/**
 * EntityGroupExportData
 */
@JsonPropertyOrder({
  EntityGroupExportData.JSON_PROPERTY_PERMISSIONS,
  EntityGroupExportData.JSON_PROPERTY_GROUP_OTA_PACKAGES,
  EntityGroupExportData.JSON_PROPERTY_GROUP_ENTITIES
})
@Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.20.0")
@JsonIgnoreProperties(
  value = "entityType", // ignore manually set entityType, it will be automatically generated by Jackson during serialization
  allowSetters = true // allows the entityType to be set during deserialization
)
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "entityType", visible = true)

public class EntityGroupExportData extends EntityExportData {
  public static final String JSON_PROPERTY_PERMISSIONS = "permissions";
  @Nullable
  private List<GroupPermission> permissions = new ArrayList<>();

  public static final String JSON_PROPERTY_GROUP_OTA_PACKAGES = "groupOtaPackages";
  @Nullable
  private List<DeviceGroupOtaPackage> groupOtaPackages = new ArrayList<>();

  public static final String JSON_PROPERTY_GROUP_ENTITIES = "groupEntities";
  @Nullable
  private Boolean groupEntities;

  public EntityGroupExportData() { 
  }

  public EntityGroupExportData permissions(@Nullable List<GroupPermission> permissions) {
    this.permissions = permissions;
    return this;
  }

  public EntityGroupExportData addPermissionsItem(GroupPermission permissionsItem) {
    if (this.permissions == null) {
      this.permissions = new ArrayList<>();
    }
    this.permissions.add(permissionsItem);
    return this;
  }

  /**
   * Get permissions
   * @return permissions
   */
  @Nullable
  @JsonProperty(value = JSON_PROPERTY_PERMISSIONS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public List<GroupPermission> getPermissions() {
    return permissions;
  }


  @JsonProperty(value = JSON_PROPERTY_PERMISSIONS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPermissions(@Nullable List<GroupPermission> permissions) {
    this.permissions = permissions;
  }


  public EntityGroupExportData groupOtaPackages(@Nullable List<DeviceGroupOtaPackage> groupOtaPackages) {
    this.groupOtaPackages = groupOtaPackages;
    return this;
  }

  public EntityGroupExportData addGroupOtaPackagesItem(DeviceGroupOtaPackage groupOtaPackagesItem) {
    if (this.groupOtaPackages == null) {
      this.groupOtaPackages = new ArrayList<>();
    }
    this.groupOtaPackages.add(groupOtaPackagesItem);
    return this;
  }

  /**
   * Get groupOtaPackages
   * @return groupOtaPackages
   */
  @Nullable
  @JsonProperty(value = JSON_PROPERTY_GROUP_OTA_PACKAGES, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public List<DeviceGroupOtaPackage> getGroupOtaPackages() {
    return groupOtaPackages;
  }


  @JsonProperty(value = JSON_PROPERTY_GROUP_OTA_PACKAGES, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setGroupOtaPackages(@Nullable List<DeviceGroupOtaPackage> groupOtaPackages) {
    this.groupOtaPackages = groupOtaPackages;
  }


  public EntityGroupExportData groupEntities(@Nullable Boolean groupEntities) {
    this.groupEntities = groupEntities;
    return this;
  }

  /**
   * Get groupEntities
   * @return groupEntities
   */
  @Nullable
  @JsonProperty(value = JSON_PROPERTY_GROUP_ENTITIES, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Boolean getGroupEntities() {
    return groupEntities;
  }


  @JsonProperty(value = JSON_PROPERTY_GROUP_ENTITIES, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setGroupEntities(@Nullable Boolean groupEntities) {
    this.groupEntities = groupEntities;
  }


  @Override
  public EntityGroupExportData entity(@Nullable ExportableEntity entity) {
    this.setEntity(entity);
    return this;
  }

  @Override
  public EntityGroupExportData relations(@Nullable List<EntityRelation> relations) {
    this.setRelations(relations);
    return this;
  }

  @Override
  public EntityGroupExportData attributes(@Nullable Map<String, List<AttributeExportData>> attributes) {
    this.setAttributes(attributes);
    return this;
  }

  @Override
  public EntityGroupExportData calculatedFields(@Nullable List<CalculatedField> calculatedFields) {
    this.setCalculatedFields(calculatedFields);
    return this;
  }

  /**
   * Return true if this EntityGroupExportData object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EntityGroupExportData entityGroupExportData = (EntityGroupExportData) o;
    return Objects.equals(this.permissions, entityGroupExportData.permissions) &&
        Objects.equals(this.groupOtaPackages, entityGroupExportData.groupOtaPackages) &&
        Objects.equals(this.groupEntities, entityGroupExportData.groupEntities) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(permissions, groupOtaPackages, groupEntities, super.hashCode());
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EntityGroupExportData {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    permissions: ").append(toIndentedString(permissions)).append("\n");
    sb.append("    groupOtaPackages: ").append(toIndentedString(groupOtaPackages)).append("\n");
    sb.append("    groupEntities: ").append(toIndentedString(groupEntities)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `entity` to the URL query string
    if (getEntity() != null) {
      joiner.add(getEntity().toUrlQueryString(prefix + "entity" + suffix));
    }

    // add `relations` to the URL query string
    if (getRelations() != null) {
      for (int i = 0; i < getRelations().size(); i++) {
        if (getRelations().get(i) != null) {
          joiner.add(getRelations().get(i).toUrlQueryString(String.format(java.util.Locale.ROOT, "%srelations%s%s", prefix, suffix,
          "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix))));
        }
      }
    }

    // add `attributes` to the URL query string
    if (getAttributes() != null) {
      for (String _key : getAttributes().keySet()) {
        joiner.add(String.format(java.util.Locale.ROOT, "%sattributes%s%s=%s", prefix, suffix,
            "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, _key, containerSuffix),
            getAttributes().get(_key), ApiClient.urlEncode(ApiClient.valueToString(getAttributes().get(_key)))));
      }
    }

    // add `calculatedFields` to the URL query string
    if (getCalculatedFields() != null) {
      for (int i = 0; i < getCalculatedFields().size(); i++) {
        if (getCalculatedFields().get(i) != null) {
          joiner.add(getCalculatedFields().get(i).toUrlQueryString(String.format(java.util.Locale.ROOT, "%scalculatedFields%s%s", prefix, suffix,
          "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix))));
        }
      }
    }

    // add `entityType` to the URL query string
    if (getEntityType() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sentityType%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getEntityType()))));
    }

    // add `permissions` to the URL query string
    if (getPermissions() != null) {
      for (int i = 0; i < getPermissions().size(); i++) {
        if (getPermissions().get(i) != null) {
          joiner.add(getPermissions().get(i).toUrlQueryString(String.format(java.util.Locale.ROOT, "%spermissions%s%s", prefix, suffix,
          "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix))));
        }
      }
    }

    // add `groupOtaPackages` to the URL query string
    if (getGroupOtaPackages() != null) {
      for (int i = 0; i < getGroupOtaPackages().size(); i++) {
        if (getGroupOtaPackages().get(i) != null) {
          joiner.add(getGroupOtaPackages().get(i).toUrlQueryString(String.format(java.util.Locale.ROOT, "%sgroupOtaPackages%s%s", prefix, suffix,
          "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix))));
        }
      }
    }

    // add `groupEntities` to the URL query string
    if (getGroupEntities() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sgroupEntities%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getGroupEntities()))));
    }

    return joiner.toString();
  }
static {
  // Initialize and register the discriminator mappings.
  Map<String, Class<?>> mappings = new HashMap<String, Class<?>>();
  mappings.put("EntityGroupExportData", EntityGroupExportData.class);
  JSON.registerDiscriminator(EntityGroupExportData.class, "entityType", mappings);
}
}

