/**
 * Copyright © 2026-2026 ThingsBoard, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.thingsboard.client.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import java.util.HashMap;
import java.util.Map;
import org.thingsboard.client.model.CalculatedFieldConfiguration;
import org.thingsboard.client.model.EntityCoordinates;
import org.thingsboard.client.model.Output;
import org.thingsboard.client.model.ZoneGroupConfiguration;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import org.thingsboard.client.JSON;
import org.thingsboard.client.ApiClient;
/**
 * GeofencingCalculatedFieldConfiguration
 */
@JsonPropertyOrder({
  GeofencingCalculatedFieldConfiguration.JSON_PROPERTY_ENTITY_COORDINATES,
  GeofencingCalculatedFieldConfiguration.JSON_PROPERTY_SCHEDULED_UPDATE_ENABLED,
  GeofencingCalculatedFieldConfiguration.JSON_PROPERTY_SCHEDULED_UPDATE_INTERVAL,
  GeofencingCalculatedFieldConfiguration.JSON_PROPERTY_ZONE_GROUPS
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.20.0")
@JsonIgnoreProperties(
  value = "type", // ignore manually set type, it will be automatically generated by Jackson during serialization
  allowSetters = true // allows the type to be set during deserialization
)
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "type", visible = true)

public class GeofencingCalculatedFieldConfiguration extends CalculatedFieldConfiguration {
  public static final String JSON_PROPERTY_ENTITY_COORDINATES = "entityCoordinates";
  @javax.annotation.Nonnull
  private EntityCoordinates entityCoordinates;

  public static final String JSON_PROPERTY_SCHEDULED_UPDATE_ENABLED = "scheduledUpdateEnabled";
  @javax.annotation.Nullable
  private Boolean scheduledUpdateEnabled;

  public static final String JSON_PROPERTY_SCHEDULED_UPDATE_INTERVAL = "scheduledUpdateInterval";
  @javax.annotation.Nullable
  private Integer scheduledUpdateInterval;

  public static final String JSON_PROPERTY_ZONE_GROUPS = "zoneGroups";
  @javax.annotation.Nonnull
  private Map<String, ZoneGroupConfiguration> zoneGroups = new HashMap<>();

  public GeofencingCalculatedFieldConfiguration() { 
  }

  public GeofencingCalculatedFieldConfiguration entityCoordinates(@javax.annotation.Nonnull EntityCoordinates entityCoordinates) {
    this.entityCoordinates = entityCoordinates;
    return this;
  }

  /**
   * Get entityCoordinates
   * @return entityCoordinates
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_ENTITY_COORDINATES, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public EntityCoordinates getEntityCoordinates() {
    return entityCoordinates;
  }


  @JsonProperty(value = JSON_PROPERTY_ENTITY_COORDINATES, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setEntityCoordinates(@javax.annotation.Nonnull EntityCoordinates entityCoordinates) {
    this.entityCoordinates = entityCoordinates;
  }


  public GeofencingCalculatedFieldConfiguration scheduledUpdateEnabled(@javax.annotation.Nullable Boolean scheduledUpdateEnabled) {
    this.scheduledUpdateEnabled = scheduledUpdateEnabled;
    return this;
  }

  /**
   * Get scheduledUpdateEnabled
   * @return scheduledUpdateEnabled
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_SCHEDULED_UPDATE_ENABLED, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Boolean getScheduledUpdateEnabled() {
    return scheduledUpdateEnabled;
  }


  @JsonProperty(value = JSON_PROPERTY_SCHEDULED_UPDATE_ENABLED, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setScheduledUpdateEnabled(@javax.annotation.Nullable Boolean scheduledUpdateEnabled) {
    this.scheduledUpdateEnabled = scheduledUpdateEnabled;
  }


  public GeofencingCalculatedFieldConfiguration scheduledUpdateInterval(@javax.annotation.Nullable Integer scheduledUpdateInterval) {
    this.scheduledUpdateInterval = scheduledUpdateInterval;
    return this;
  }

  /**
   * Get scheduledUpdateInterval
   * @return scheduledUpdateInterval
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_SCHEDULED_UPDATE_INTERVAL, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Integer getScheduledUpdateInterval() {
    return scheduledUpdateInterval;
  }


  @JsonProperty(value = JSON_PROPERTY_SCHEDULED_UPDATE_INTERVAL, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setScheduledUpdateInterval(@javax.annotation.Nullable Integer scheduledUpdateInterval) {
    this.scheduledUpdateInterval = scheduledUpdateInterval;
  }


  public GeofencingCalculatedFieldConfiguration zoneGroups(@javax.annotation.Nonnull Map<String, ZoneGroupConfiguration> zoneGroups) {
    this.zoneGroups = zoneGroups;
    return this;
  }

  public GeofencingCalculatedFieldConfiguration putZoneGroupsItem(String key, ZoneGroupConfiguration zoneGroupsItem) {
    if (this.zoneGroups == null) {
      this.zoneGroups = new HashMap<>();
    }
    this.zoneGroups.put(key, zoneGroupsItem);
    return this;
  }

  /**
   * Get zoneGroups
   * @return zoneGroups
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_ZONE_GROUPS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Map<String, ZoneGroupConfiguration> getZoneGroups() {
    return zoneGroups;
  }


  @JsonProperty(value = JSON_PROPERTY_ZONE_GROUPS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setZoneGroups(@javax.annotation.Nonnull Map<String, ZoneGroupConfiguration> zoneGroups) {
    this.zoneGroups = zoneGroups;
  }


  @Override
  public GeofencingCalculatedFieldConfiguration output(@javax.annotation.Nullable Output output) {
    this.setOutput(output);
    return this;
  }

  @Override
  public GeofencingCalculatedFieldConfiguration aiGenerated(@javax.annotation.Nullable Boolean aiGenerated) {
    this.setAiGenerated(aiGenerated);
    return this;
  }

  @Override
  public GeofencingCalculatedFieldConfiguration type(@javax.annotation.Nonnull String type) {
    this.setType(type);
    return this;
  }

  /**
   * Return true if this GeofencingCalculatedFieldConfiguration object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GeofencingCalculatedFieldConfiguration geofencingCalculatedFieldConfiguration = (GeofencingCalculatedFieldConfiguration) o;
    return Objects.equals(this.entityCoordinates, geofencingCalculatedFieldConfiguration.entityCoordinates) &&
        Objects.equals(this.scheduledUpdateEnabled, geofencingCalculatedFieldConfiguration.scheduledUpdateEnabled) &&
        Objects.equals(this.scheduledUpdateInterval, geofencingCalculatedFieldConfiguration.scheduledUpdateInterval) &&
        Objects.equals(this.zoneGroups, geofencingCalculatedFieldConfiguration.zoneGroups) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(entityCoordinates, scheduledUpdateEnabled, scheduledUpdateInterval, zoneGroups, super.hashCode());
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GeofencingCalculatedFieldConfiguration {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    entityCoordinates: ").append(toIndentedString(entityCoordinates)).append("\n");
    sb.append("    scheduledUpdateEnabled: ").append(toIndentedString(scheduledUpdateEnabled)).append("\n");
    sb.append("    scheduledUpdateInterval: ").append(toIndentedString(scheduledUpdateInterval)).append("\n");
    sb.append("    zoneGroups: ").append(toIndentedString(zoneGroups)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `output` to the URL query string
    if (getOutput() != null) {
      joiner.add(getOutput().toUrlQueryString(prefix + "output" + suffix));
    }

    // add `aiGenerated` to the URL query string
    if (getAiGenerated() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%saiGenerated%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getAiGenerated()))));
    }

    // add `type` to the URL query string
    if (getType() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%stype%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getType()))));
    }

    // add `entityCoordinates` to the URL query string
    if (getEntityCoordinates() != null) {
      joiner.add(getEntityCoordinates().toUrlQueryString(prefix + "entityCoordinates" + suffix));
    }

    // add `scheduledUpdateEnabled` to the URL query string
    if (getScheduledUpdateEnabled() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sscheduledUpdateEnabled%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getScheduledUpdateEnabled()))));
    }

    // add `scheduledUpdateInterval` to the URL query string
    if (getScheduledUpdateInterval() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sscheduledUpdateInterval%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getScheduledUpdateInterval()))));
    }

    // add `zoneGroups` to the URL query string
    if (getZoneGroups() != null) {
      for (String _key : getZoneGroups().keySet()) {
        if (getZoneGroups().get(_key) != null) {
          joiner.add(getZoneGroups().get(_key).toUrlQueryString(String.format(java.util.Locale.ROOT, "%szoneGroups%s%s", prefix, suffix,
              "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, _key, containerSuffix))));
        }
      }
    }

    return joiner.toString();
  }
static {
  // Initialize and register the discriminator mappings.
  Map<String, Class<?>> mappings = new HashMap<String, Class<?>>();
  mappings.put("GeofencingCalculatedFieldConfiguration", GeofencingCalculatedFieldConfiguration.class);
  JSON.registerDiscriminator(GeofencingCalculatedFieldConfiguration.class, "type", mappings);
}
}

