/**
 * Copyright © 2026-2026 ThingsBoard, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.thingsboard.client.model;

import javax.annotation.Generated;
import javax.annotation.Nonnull;
import javax.annotation.Nullable;
import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import org.thingsboard.client.model.DeliveryMethodNotificationTemplate;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import org.thingsboard.client.JSON;
import org.thingsboard.client.ApiClient;
/**
 * WebDeliveryMethodNotificationTemplate
 */
@JsonPropertyOrder({
  WebDeliveryMethodNotificationTemplate.JSON_PROPERTY_SUBJECT,
  WebDeliveryMethodNotificationTemplate.JSON_PROPERTY_ADDITIONAL_CONFIG
})
@Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.20.0")
@JsonIgnoreProperties(
  value = "method", // ignore manually set method, it will be automatically generated by Jackson during serialization
  allowSetters = true // allows the method to be set during deserialization
)
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "method", visible = true)

public class WebDeliveryMethodNotificationTemplate extends DeliveryMethodNotificationTemplate {
  public static final String JSON_PROPERTY_SUBJECT = "subject";
  @Nonnull
  private String subject;

  public static final String JSON_PROPERTY_ADDITIONAL_CONFIG = "additionalConfig";
  @Nullable
  private com.fasterxml.jackson.databind.JsonNode additionalConfig;

  public WebDeliveryMethodNotificationTemplate() { 
  }

  public WebDeliveryMethodNotificationTemplate subject(@Nonnull String subject) {
    this.subject = subject;
    return this;
  }

  /**
   * Subject line for the web notification
   * @return subject
   */
  @Nonnull
  @JsonProperty(value = JSON_PROPERTY_SUBJECT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getSubject() {
    return subject;
  }


  @JsonProperty(value = JSON_PROPERTY_SUBJECT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setSubject(@Nonnull String subject) {
    this.subject = subject;
  }


  public WebDeliveryMethodNotificationTemplate additionalConfig(@Nullable com.fasterxml.jackson.databind.JsonNode additionalConfig) {
    this.additionalConfig = additionalConfig;
    return this;
  }

  /**
   * Additional JSON configuration for web buttons/actions
   * @return additionalConfig
   */
  @Nullable
  @JsonProperty(value = JSON_PROPERTY_ADDITIONAL_CONFIG, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public com.fasterxml.jackson.databind.JsonNode getAdditionalConfig() {
    return additionalConfig;
  }


  @JsonProperty(value = JSON_PROPERTY_ADDITIONAL_CONFIG, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAdditionalConfig(@Nullable com.fasterxml.jackson.databind.JsonNode additionalConfig) {
    this.additionalConfig = additionalConfig;
  }


  @Override
  public WebDeliveryMethodNotificationTemplate enabled(@Nullable Boolean enabled) {
    this.setEnabled(enabled);
    return this;
  }

  @Override
  public WebDeliveryMethodNotificationTemplate body(@Nonnull String body) {
    this.setBody(body);
    return this;
  }

  /**
   * Return true if this WebDeliveryMethodNotificationTemplate object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WebDeliveryMethodNotificationTemplate webDeliveryMethodNotificationTemplate = (WebDeliveryMethodNotificationTemplate) o;
    return Objects.equals(this.subject, webDeliveryMethodNotificationTemplate.subject) &&
        Objects.equals(this.additionalConfig, webDeliveryMethodNotificationTemplate.additionalConfig) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(subject, additionalConfig, super.hashCode());
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WebDeliveryMethodNotificationTemplate {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    subject: ").append(toIndentedString(subject)).append("\n");
    sb.append("    additionalConfig: ").append(toIndentedString(additionalConfig)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `enabled` to the URL query string
    if (getEnabled() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%senabled%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getEnabled()))));
    }

    // add `body` to the URL query string
    if (getBody() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sbody%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getBody()))));
    }

    // add `method` to the URL query string
    if (getMethod() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%smethod%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getMethod()))));
    }

    // add `subject` to the URL query string
    if (getSubject() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%ssubject%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getSubject()))));
    }

    // add `additionalConfig` to the URL query string
    if (getAdditionalConfig() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sadditionalConfig%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getAdditionalConfig()))));
    }

    return joiner.toString();
  }
static {
  // Initialize and register the discriminator mappings.
  Map<String, Class<?>> mappings = new HashMap<String, Class<?>>();
  mappings.put("WebDeliveryMethodNotificationTemplate", WebDeliveryMethodNotificationTemplate.class);
  JSON.registerDiscriminator(WebDeliveryMethodNotificationTemplate.class, "method", mappings);
}
}

