/**
 * Copyright © 2026-2026 ThingsBoard, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.thingsboard.client.model;

import javax.annotation.Generated;
import javax.annotation.Nonnull;
import javax.annotation.Nullable;
import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import org.thingsboard.client.model.AlarmConditionExpression;
import org.thingsboard.client.model.AlarmConditionValueAlarmSchedule;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import org.thingsboard.client.JSON;
import org.thingsboard.client.ApiClient;
/**
 * AlarmCondition
 */
@JsonPropertyOrder({
  AlarmCondition.JSON_PROPERTY_EXPRESSION,
  AlarmCondition.JSON_PROPERTY_SCHEDULE,
  AlarmCondition.JSON_PROPERTY_TYPE
})
@Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.20.0")
@JsonIgnoreProperties(
  value = "type", // ignore manually set type, it will be automatically generated by Jackson during serialization
  allowSetters = true // allows the type to be set during deserialization
)
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "type", visible = true)
@JsonSubTypes({
  @JsonSubTypes.Type(value = DurationAlarmCondition.class, name = "DURATION"),
  @JsonSubTypes.Type(value = RepeatingAlarmCondition.class, name = "REPEATING"),
  @JsonSubTypes.Type(value = SimpleAlarmCondition.class, name = "SIMPLE"),
})

public class AlarmCondition {
  public static final String JSON_PROPERTY_EXPRESSION = "expression";
  @Nonnull
  private AlarmConditionExpression expression;

  public static final String JSON_PROPERTY_SCHEDULE = "schedule";
  @Nullable
  private AlarmConditionValueAlarmSchedule schedule;

  public static final String JSON_PROPERTY_TYPE = "type";
  @Nonnull
  private String type;

  public AlarmCondition() { 
  }

  public AlarmCondition expression(@Nonnull AlarmConditionExpression expression) {
    this.expression = expression;
    return this;
  }

  /**
   * Get expression
   * @return expression
   */
  @Nonnull
  @JsonProperty(value = JSON_PROPERTY_EXPRESSION, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public AlarmConditionExpression getExpression() {
    return expression;
  }


  @JsonProperty(value = JSON_PROPERTY_EXPRESSION, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setExpression(@Nonnull AlarmConditionExpression expression) {
    this.expression = expression;
  }


  public AlarmCondition schedule(@Nullable AlarmConditionValueAlarmSchedule schedule) {
    this.schedule = schedule;
    return this;
  }

  /**
   * Get schedule
   * @return schedule
   */
  @Nullable
  @JsonProperty(value = JSON_PROPERTY_SCHEDULE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public AlarmConditionValueAlarmSchedule getSchedule() {
    return schedule;
  }


  @JsonProperty(value = JSON_PROPERTY_SCHEDULE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSchedule(@Nullable AlarmConditionValueAlarmSchedule schedule) {
    this.schedule = schedule;
  }


  public AlarmCondition type(@Nonnull String type) {
    this.type = type;
    return this;
  }

  /**
   * Get type
   * @return type
   */
  @Nonnull
  @JsonProperty(value = JSON_PROPERTY_TYPE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getType() {
    return type;
  }


  @JsonProperty(value = JSON_PROPERTY_TYPE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setType(@Nonnull String type) {
    this.type = type;
  }


  /**
   * Return true if this AlarmCondition object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AlarmCondition alarmCondition = (AlarmCondition) o;
    return Objects.equals(this.expression, alarmCondition.expression) &&
        Objects.equals(this.schedule, alarmCondition.schedule) &&
        Objects.equals(this.type, alarmCondition.type);
  }

  @Override
  public int hashCode() {
    return Objects.hash(expression, schedule, type);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AlarmCondition {\n");
    sb.append("    expression: ").append(toIndentedString(expression)).append("\n");
    sb.append("    schedule: ").append(toIndentedString(schedule)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `expression` to the URL query string
    if (getExpression() != null) {
      joiner.add(getExpression().toUrlQueryString(prefix + "expression" + suffix));
    }

    // add `schedule` to the URL query string
    if (getSchedule() != null) {
      joiner.add(getSchedule().toUrlQueryString(prefix + "schedule" + suffix));
    }

    // add `type` to the URL query string
    if (getType() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%stype%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getType()))));
    }

    return joiner.toString();
  }
static {
  // Initialize and register the discriminator mappings.
  Map<String, Class<?>> mappings = new HashMap<String, Class<?>>();
  mappings.put("DURATION", DurationAlarmCondition.class);
  mappings.put("REPEATING", RepeatingAlarmCondition.class);
  mappings.put("SIMPLE", SimpleAlarmCondition.class);
  mappings.put("AlarmCondition", AlarmCondition.class);
  JSON.registerDiscriminator(AlarmCondition.class, "type", mappings);
}
}

