/**
 * Copyright © 2026-2026 ThingsBoard, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.thingsboard.client.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import org.thingsboard.client.model.AlarmConditionValueLong;
import org.thingsboard.client.model.AlarmRuleKeyFilterPredicate;
import org.thingsboard.client.model.TimeUnit;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import org.thingsboard.client.JSON;
import org.thingsboard.client.ApiClient;
/**
 * AlarmRuleNoDataFilterPredicate
 */
@JsonPropertyOrder({
  AlarmRuleNoDataFilterPredicate.JSON_PROPERTY_UNIT,
  AlarmRuleNoDataFilterPredicate.JSON_PROPERTY_DURATION
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-02-24T16:17:55.932789+02:00[Europe/Kiev]", comments = "Generator version: 7.20.0")
@JsonIgnoreProperties(
  value = "type", // ignore manually set type, it will be automatically generated by Jackson during serialization
  allowSetters = true // allows the type to be set during deserialization
)
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "type", visible = true)

public class AlarmRuleNoDataFilterPredicate extends AlarmRuleKeyFilterPredicate {
  public static final String JSON_PROPERTY_UNIT = "unit";
  @javax.annotation.Nonnull
  private TimeUnit unit;

  public static final String JSON_PROPERTY_DURATION = "duration";
  @javax.annotation.Nonnull
  private AlarmConditionValueLong duration;

  public AlarmRuleNoDataFilterPredicate() { 
  }

  public AlarmRuleNoDataFilterPredicate unit(@javax.annotation.Nonnull TimeUnit unit) {
    this.unit = unit;
    return this;
  }

  /**
   * Get unit
   * @return unit
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_UNIT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public TimeUnit getUnit() {
    return unit;
  }


  @JsonProperty(value = JSON_PROPERTY_UNIT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setUnit(@javax.annotation.Nonnull TimeUnit unit) {
    this.unit = unit;
  }


  public AlarmRuleNoDataFilterPredicate duration(@javax.annotation.Nonnull AlarmConditionValueLong duration) {
    this.duration = duration;
    return this;
  }

  /**
   * Get duration
   * @return duration
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_DURATION, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public AlarmConditionValueLong getDuration() {
    return duration;
  }


  @JsonProperty(value = JSON_PROPERTY_DURATION, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setDuration(@javax.annotation.Nonnull AlarmConditionValueLong duration) {
    this.duration = duration;
  }


  @Override
  public AlarmRuleNoDataFilterPredicate type(@javax.annotation.Nonnull String type) {
    this.setType(type);
    return this;
  }

  /**
   * Return true if this AlarmRuleNoDataFilterPredicate object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AlarmRuleNoDataFilterPredicate alarmRuleNoDataFilterPredicate = (AlarmRuleNoDataFilterPredicate) o;
    return Objects.equals(this.unit, alarmRuleNoDataFilterPredicate.unit) &&
        Objects.equals(this.duration, alarmRuleNoDataFilterPredicate.duration) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(unit, duration, super.hashCode());
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AlarmRuleNoDataFilterPredicate {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    unit: ").append(toIndentedString(unit)).append("\n");
    sb.append("    duration: ").append(toIndentedString(duration)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `type` to the URL query string
    if (getType() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%stype%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getType()))));
    }

    // add `unit` to the URL query string
    if (getUnit() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sunit%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getUnit()))));
    }

    // add `duration` to the URL query string
    if (getDuration() != null) {
      joiner.add(getDuration().toUrlQueryString(prefix + "duration" + suffix));
    }

    return joiner.toString();
  }
static {
  // Initialize and register the discriminator mappings.
  Map<String, Class<?>> mappings = new HashMap<String, Class<?>>();
  mappings.put("AlarmRuleNoDataFilterPredicate", AlarmRuleNoDataFilterPredicate.class);
  JSON.registerDiscriminator(AlarmRuleNoDataFilterPredicate.class, "type", mappings);
}
}

