/**
 * Copyright © 2026-2026 ThingsBoard, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.thingsboard.client.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.thingsboard.client.model.JobConfiguration;
import org.thingsboard.client.model.TaskResult;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import org.thingsboard.client.JSON;
import org.thingsboard.client.ApiClient;
/**
 * Dummy job configuration
 */
@JsonPropertyOrder({
  DummyJobConfiguration.JSON_PROPERTY_TASK_PROCESSING_TIME_MS,
  DummyJobConfiguration.JSON_PROPERTY_SUCCESSFUL_TASKS_COUNT,
  DummyJobConfiguration.JSON_PROPERTY_FAILED_TASKS_COUNT,
  DummyJobConfiguration.JSON_PROPERTY_PERMANENTLY_FAILED_TASKS_COUNT,
  DummyJobConfiguration.JSON_PROPERTY_ERRORS,
  DummyJobConfiguration.JSON_PROPERTY_RETRIES,
  DummyJobConfiguration.JSON_PROPERTY_TASK_PROCESSING_TIMEOUT_MS,
  DummyJobConfiguration.JSON_PROPERTY_GENERAL_ERROR,
  DummyJobConfiguration.JSON_PROPERTY_SUBMITTED_TASKS_BEFORE_GENERAL_ERROR
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-02-24T16:17:55.932789+02:00[Europe/Kiev]", comments = "Generator version: 7.20.0")
@JsonIgnoreProperties(
  value = "type", // ignore manually set type, it will be automatically generated by Jackson during serialization
  allowSetters = true // allows the type to be set during deserialization
)
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "type", visible = true)

public class DummyJobConfiguration extends JobConfiguration {
  public static final String JSON_PROPERTY_TASK_PROCESSING_TIME_MS = "taskProcessingTimeMs";
  @javax.annotation.Nullable
  private Long taskProcessingTimeMs;

  public static final String JSON_PROPERTY_SUCCESSFUL_TASKS_COUNT = "successfulTasksCount";
  @javax.annotation.Nullable
  private Integer successfulTasksCount;

  public static final String JSON_PROPERTY_FAILED_TASKS_COUNT = "failedTasksCount";
  @javax.annotation.Nullable
  private Integer failedTasksCount;

  public static final String JSON_PROPERTY_PERMANENTLY_FAILED_TASKS_COUNT = "permanentlyFailedTasksCount";
  @javax.annotation.Nullable
  private Integer permanentlyFailedTasksCount;

  public static final String JSON_PROPERTY_ERRORS = "errors";
  @javax.annotation.Nullable
  private List<String> errors = new ArrayList<>();

  public static final String JSON_PROPERTY_RETRIES = "retries";
  @javax.annotation.Nullable
  private Integer retries;

  public static final String JSON_PROPERTY_TASK_PROCESSING_TIMEOUT_MS = "taskProcessingTimeoutMs";
  @javax.annotation.Nullable
  private Long taskProcessingTimeoutMs;

  public static final String JSON_PROPERTY_GENERAL_ERROR = "generalError";
  @javax.annotation.Nullable
  private String generalError;

  public static final String JSON_PROPERTY_SUBMITTED_TASKS_BEFORE_GENERAL_ERROR = "submittedTasksBeforeGeneralError";
  @javax.annotation.Nullable
  private Integer submittedTasksBeforeGeneralError;

  public DummyJobConfiguration() { 
  }

  public DummyJobConfiguration taskProcessingTimeMs(@javax.annotation.Nullable Long taskProcessingTimeMs) {
    this.taskProcessingTimeMs = taskProcessingTimeMs;
    return this;
  }

  /**
   * Get taskProcessingTimeMs
   * @return taskProcessingTimeMs
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TASK_PROCESSING_TIME_MS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Long getTaskProcessingTimeMs() {
    return taskProcessingTimeMs;
  }


  @JsonProperty(value = JSON_PROPERTY_TASK_PROCESSING_TIME_MS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTaskProcessingTimeMs(@javax.annotation.Nullable Long taskProcessingTimeMs) {
    this.taskProcessingTimeMs = taskProcessingTimeMs;
  }


  public DummyJobConfiguration successfulTasksCount(@javax.annotation.Nullable Integer successfulTasksCount) {
    this.successfulTasksCount = successfulTasksCount;
    return this;
  }

  /**
   * Get successfulTasksCount
   * @return successfulTasksCount
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_SUCCESSFUL_TASKS_COUNT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Integer getSuccessfulTasksCount() {
    return successfulTasksCount;
  }


  @JsonProperty(value = JSON_PROPERTY_SUCCESSFUL_TASKS_COUNT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSuccessfulTasksCount(@javax.annotation.Nullable Integer successfulTasksCount) {
    this.successfulTasksCount = successfulTasksCount;
  }


  public DummyJobConfiguration failedTasksCount(@javax.annotation.Nullable Integer failedTasksCount) {
    this.failedTasksCount = failedTasksCount;
    return this;
  }

  /**
   * Get failedTasksCount
   * @return failedTasksCount
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_FAILED_TASKS_COUNT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Integer getFailedTasksCount() {
    return failedTasksCount;
  }


  @JsonProperty(value = JSON_PROPERTY_FAILED_TASKS_COUNT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFailedTasksCount(@javax.annotation.Nullable Integer failedTasksCount) {
    this.failedTasksCount = failedTasksCount;
  }


  public DummyJobConfiguration permanentlyFailedTasksCount(@javax.annotation.Nullable Integer permanentlyFailedTasksCount) {
    this.permanentlyFailedTasksCount = permanentlyFailedTasksCount;
    return this;
  }

  /**
   * Get permanentlyFailedTasksCount
   * @return permanentlyFailedTasksCount
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PERMANENTLY_FAILED_TASKS_COUNT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Integer getPermanentlyFailedTasksCount() {
    return permanentlyFailedTasksCount;
  }


  @JsonProperty(value = JSON_PROPERTY_PERMANENTLY_FAILED_TASKS_COUNT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPermanentlyFailedTasksCount(@javax.annotation.Nullable Integer permanentlyFailedTasksCount) {
    this.permanentlyFailedTasksCount = permanentlyFailedTasksCount;
  }


  public DummyJobConfiguration errors(@javax.annotation.Nullable List<String> errors) {
    this.errors = errors;
    return this;
  }

  public DummyJobConfiguration addErrorsItem(String errorsItem) {
    if (this.errors == null) {
      this.errors = new ArrayList<>();
    }
    this.errors.add(errorsItem);
    return this;
  }

  /**
   * Get errors
   * @return errors
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ERRORS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public List<String> getErrors() {
    return errors;
  }


  @JsonProperty(value = JSON_PROPERTY_ERRORS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setErrors(@javax.annotation.Nullable List<String> errors) {
    this.errors = errors;
  }


  public DummyJobConfiguration retries(@javax.annotation.Nullable Integer retries) {
    this.retries = retries;
    return this;
  }

  /**
   * Get retries
   * @return retries
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_RETRIES, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Integer getRetries() {
    return retries;
  }


  @JsonProperty(value = JSON_PROPERTY_RETRIES, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRetries(@javax.annotation.Nullable Integer retries) {
    this.retries = retries;
  }


  public DummyJobConfiguration taskProcessingTimeoutMs(@javax.annotation.Nullable Long taskProcessingTimeoutMs) {
    this.taskProcessingTimeoutMs = taskProcessingTimeoutMs;
    return this;
  }

  /**
   * Get taskProcessingTimeoutMs
   * @return taskProcessingTimeoutMs
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TASK_PROCESSING_TIMEOUT_MS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Long getTaskProcessingTimeoutMs() {
    return taskProcessingTimeoutMs;
  }


  @JsonProperty(value = JSON_PROPERTY_TASK_PROCESSING_TIMEOUT_MS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTaskProcessingTimeoutMs(@javax.annotation.Nullable Long taskProcessingTimeoutMs) {
    this.taskProcessingTimeoutMs = taskProcessingTimeoutMs;
  }


  public DummyJobConfiguration generalError(@javax.annotation.Nullable String generalError) {
    this.generalError = generalError;
    return this;
  }

  /**
   * Get generalError
   * @return generalError
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_GENERAL_ERROR, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getGeneralError() {
    return generalError;
  }


  @JsonProperty(value = JSON_PROPERTY_GENERAL_ERROR, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setGeneralError(@javax.annotation.Nullable String generalError) {
    this.generalError = generalError;
  }


  public DummyJobConfiguration submittedTasksBeforeGeneralError(@javax.annotation.Nullable Integer submittedTasksBeforeGeneralError) {
    this.submittedTasksBeforeGeneralError = submittedTasksBeforeGeneralError;
    return this;
  }

  /**
   * Get submittedTasksBeforeGeneralError
   * @return submittedTasksBeforeGeneralError
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_SUBMITTED_TASKS_BEFORE_GENERAL_ERROR, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Integer getSubmittedTasksBeforeGeneralError() {
    return submittedTasksBeforeGeneralError;
  }


  @JsonProperty(value = JSON_PROPERTY_SUBMITTED_TASKS_BEFORE_GENERAL_ERROR, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSubmittedTasksBeforeGeneralError(@javax.annotation.Nullable Integer submittedTasksBeforeGeneralError) {
    this.submittedTasksBeforeGeneralError = submittedTasksBeforeGeneralError;
  }


  @Override
  public DummyJobConfiguration tasksKey(@javax.annotation.Nonnull String tasksKey) {
    this.setTasksKey(tasksKey);
    return this;
  }

  @Override
  public DummyJobConfiguration toReprocess(@javax.annotation.Nullable List<TaskResult> toReprocess) {
    this.setToReprocess(toReprocess);
    return this;
  }

  @Override
  public DummyJobConfiguration type(@javax.annotation.Nonnull String type) {
    this.setType(type);
    return this;
  }

  /**
   * Return true if this DummyJobConfiguration object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DummyJobConfiguration dummyJobConfiguration = (DummyJobConfiguration) o;
    return Objects.equals(this.taskProcessingTimeMs, dummyJobConfiguration.taskProcessingTimeMs) &&
        Objects.equals(this.successfulTasksCount, dummyJobConfiguration.successfulTasksCount) &&
        Objects.equals(this.failedTasksCount, dummyJobConfiguration.failedTasksCount) &&
        Objects.equals(this.permanentlyFailedTasksCount, dummyJobConfiguration.permanentlyFailedTasksCount) &&
        Objects.equals(this.errors, dummyJobConfiguration.errors) &&
        Objects.equals(this.retries, dummyJobConfiguration.retries) &&
        Objects.equals(this.taskProcessingTimeoutMs, dummyJobConfiguration.taskProcessingTimeoutMs) &&
        Objects.equals(this.generalError, dummyJobConfiguration.generalError) &&
        Objects.equals(this.submittedTasksBeforeGeneralError, dummyJobConfiguration.submittedTasksBeforeGeneralError) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(taskProcessingTimeMs, successfulTasksCount, failedTasksCount, permanentlyFailedTasksCount, errors, retries, taskProcessingTimeoutMs, generalError, submittedTasksBeforeGeneralError, super.hashCode());
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DummyJobConfiguration {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    taskProcessingTimeMs: ").append(toIndentedString(taskProcessingTimeMs)).append("\n");
    sb.append("    successfulTasksCount: ").append(toIndentedString(successfulTasksCount)).append("\n");
    sb.append("    failedTasksCount: ").append(toIndentedString(failedTasksCount)).append("\n");
    sb.append("    permanentlyFailedTasksCount: ").append(toIndentedString(permanentlyFailedTasksCount)).append("\n");
    sb.append("    errors: ").append(toIndentedString(errors)).append("\n");
    sb.append("    retries: ").append(toIndentedString(retries)).append("\n");
    sb.append("    taskProcessingTimeoutMs: ").append(toIndentedString(taskProcessingTimeoutMs)).append("\n");
    sb.append("    generalError: ").append(toIndentedString(generalError)).append("\n");
    sb.append("    submittedTasksBeforeGeneralError: ").append(toIndentedString(submittedTasksBeforeGeneralError)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `tasksKey` to the URL query string
    if (getTasksKey() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%stasksKey%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getTasksKey()))));
    }

    // add `toReprocess` to the URL query string
    if (getToReprocess() != null) {
      for (int i = 0; i < getToReprocess().size(); i++) {
        if (getToReprocess().get(i) != null) {
          joiner.add(getToReprocess().get(i).toUrlQueryString(String.format(java.util.Locale.ROOT, "%stoReprocess%s%s", prefix, suffix,
          "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix))));
        }
      }
    }

    // add `type` to the URL query string
    if (getType() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%stype%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getType()))));
    }

    // add `taskProcessingTimeMs` to the URL query string
    if (getTaskProcessingTimeMs() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%staskProcessingTimeMs%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getTaskProcessingTimeMs()))));
    }

    // add `successfulTasksCount` to the URL query string
    if (getSuccessfulTasksCount() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%ssuccessfulTasksCount%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getSuccessfulTasksCount()))));
    }

    // add `failedTasksCount` to the URL query string
    if (getFailedTasksCount() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sfailedTasksCount%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getFailedTasksCount()))));
    }

    // add `permanentlyFailedTasksCount` to the URL query string
    if (getPermanentlyFailedTasksCount() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%spermanentlyFailedTasksCount%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getPermanentlyFailedTasksCount()))));
    }

    // add `errors` to the URL query string
    if (getErrors() != null) {
      for (int i = 0; i < getErrors().size(); i++) {
        joiner.add(String.format(java.util.Locale.ROOT, "%serrors%s%s=%s", prefix, suffix,
            "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix),
            ApiClient.urlEncode(ApiClient.valueToString(getErrors().get(i)))));
      }
    }

    // add `retries` to the URL query string
    if (getRetries() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sretries%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getRetries()))));
    }

    // add `taskProcessingTimeoutMs` to the URL query string
    if (getTaskProcessingTimeoutMs() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%staskProcessingTimeoutMs%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getTaskProcessingTimeoutMs()))));
    }

    // add `generalError` to the URL query string
    if (getGeneralError() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sgeneralError%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getGeneralError()))));
    }

    // add `submittedTasksBeforeGeneralError` to the URL query string
    if (getSubmittedTasksBeforeGeneralError() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%ssubmittedTasksBeforeGeneralError%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getSubmittedTasksBeforeGeneralError()))));
    }

    return joiner.toString();
  }
static {
  // Initialize and register the discriminator mappings.
  Map<String, Class<?>> mappings = new HashMap<String, Class<?>>();
  mappings.put("DummyJobConfiguration", DummyJobConfiguration.class);
  JSON.registerDiscriminator(DummyJobConfiguration.class, "type", mappings);
}
}

