/**
 * Copyright © 2026-2026 ThingsBoard, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.thingsboard.client.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import org.thingsboard.client.model.CaptchaParams;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import org.thingsboard.client.JSON;
import org.thingsboard.client.ApiClient;
/**
 * EnterpriseCaptchaParams
 */
@JsonPropertyOrder({
  EnterpriseCaptchaParams.JSON_PROPERTY_PROJECT_ID,
  EnterpriseCaptchaParams.JSON_PROPERTY_SERVICE_ACCOUNT_CREDENTIALS,
  EnterpriseCaptchaParams.JSON_PROPERTY_SERVICE_ACCOUNT_CREDENTIALS_FILE_NAME,
  EnterpriseCaptchaParams.JSON_PROPERTY_ANDROID_KEY,
  EnterpriseCaptchaParams.JSON_PROPERTY_IOS_KEY,
  EnterpriseCaptchaParams.JSON_PROPERTY_LOG_ACTION_NAME
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.20.0")
@JsonIgnoreProperties(
  value = "version", // ignore manually set version, it will be automatically generated by Jackson during serialization
  allowSetters = true // allows the version to be set during deserialization
)
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "version", visible = true)

public class EnterpriseCaptchaParams extends CaptchaParams {
  public static final String JSON_PROPERTY_PROJECT_ID = "projectId";
  @javax.annotation.Nullable
  private String projectId;

  public static final String JSON_PROPERTY_SERVICE_ACCOUNT_CREDENTIALS = "serviceAccountCredentials";
  @javax.annotation.Nullable
  private String serviceAccountCredentials;

  public static final String JSON_PROPERTY_SERVICE_ACCOUNT_CREDENTIALS_FILE_NAME = "serviceAccountCredentialsFileName";
  @javax.annotation.Nullable
  private String serviceAccountCredentialsFileName;

  public static final String JSON_PROPERTY_ANDROID_KEY = "androidKey";
  @javax.annotation.Nullable
  private String androidKey;

  public static final String JSON_PROPERTY_IOS_KEY = "iosKey";
  @javax.annotation.Nullable
  private String iosKey;

  public static final String JSON_PROPERTY_LOG_ACTION_NAME = "logActionName";
  @javax.annotation.Nullable
  private String logActionName;

  public EnterpriseCaptchaParams() { 
  }

  public EnterpriseCaptchaParams projectId(@javax.annotation.Nullable String projectId) {
    this.projectId = projectId;
    return this;
  }

  /**
   * Your Google Cloud project ID
   * @return projectId
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PROJECT_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getProjectId() {
    return projectId;
  }


  @JsonProperty(value = JSON_PROPERTY_PROJECT_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setProjectId(@javax.annotation.Nullable String projectId) {
    this.projectId = projectId;
  }


  public EnterpriseCaptchaParams serviceAccountCredentials(@javax.annotation.Nullable String serviceAccountCredentials) {
    this.serviceAccountCredentials = serviceAccountCredentials;
    return this;
  }

  /**
   * Service account credentials
   * @return serviceAccountCredentials
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_SERVICE_ACCOUNT_CREDENTIALS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getServiceAccountCredentials() {
    return serviceAccountCredentials;
  }


  @JsonProperty(value = JSON_PROPERTY_SERVICE_ACCOUNT_CREDENTIALS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setServiceAccountCredentials(@javax.annotation.Nullable String serviceAccountCredentials) {
    this.serviceAccountCredentials = serviceAccountCredentials;
  }


  public EnterpriseCaptchaParams serviceAccountCredentialsFileName(@javax.annotation.Nullable String serviceAccountCredentialsFileName) {
    this.serviceAccountCredentialsFileName = serviceAccountCredentialsFileName;
    return this;
  }

  /**
   * Service account credentials file name
   * @return serviceAccountCredentialsFileName
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_SERVICE_ACCOUNT_CREDENTIALS_FILE_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getServiceAccountCredentialsFileName() {
    return serviceAccountCredentialsFileName;
  }


  @JsonProperty(value = JSON_PROPERTY_SERVICE_ACCOUNT_CREDENTIALS_FILE_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setServiceAccountCredentialsFileName(@javax.annotation.Nullable String serviceAccountCredentialsFileName) {
    this.serviceAccountCredentialsFileName = serviceAccountCredentialsFileName;
  }


  public EnterpriseCaptchaParams androidKey(@javax.annotation.Nullable String androidKey) {
    this.androidKey = androidKey;
    return this;
  }

  /**
   * The reCAPTCHA key associated with android app.
   * @return androidKey
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ANDROID_KEY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getAndroidKey() {
    return androidKey;
  }


  @JsonProperty(value = JSON_PROPERTY_ANDROID_KEY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAndroidKey(@javax.annotation.Nullable String androidKey) {
    this.androidKey = androidKey;
  }


  public EnterpriseCaptchaParams iosKey(@javax.annotation.Nullable String iosKey) {
    this.iosKey = iosKey;
    return this;
  }

  /**
   * The reCAPTCHA key associated with iOS app.
   * @return iosKey
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_IOS_KEY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getIosKey() {
    return iosKey;
  }


  @JsonProperty(value = JSON_PROPERTY_IOS_KEY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIosKey(@javax.annotation.Nullable String iosKey) {
    this.iosKey = iosKey;
  }


  public EnterpriseCaptchaParams logActionName(@javax.annotation.Nullable String logActionName) {
    this.logActionName = logActionName;
    return this;
  }

  /**
   * Optional action name used for logging
   * @return logActionName
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_LOG_ACTION_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getLogActionName() {
    return logActionName;
  }


  @JsonProperty(value = JSON_PROPERTY_LOG_ACTION_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLogActionName(@javax.annotation.Nullable String logActionName) {
    this.logActionName = logActionName;
  }


  @Override
  public EnterpriseCaptchaParams version(@javax.annotation.Nonnull String version) {
    this.setVersion(version);
    return this;
  }

  /**
   * Return true if this EnterpriseCaptchaParams object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EnterpriseCaptchaParams enterpriseCaptchaParams = (EnterpriseCaptchaParams) o;
    return Objects.equals(this.projectId, enterpriseCaptchaParams.projectId) &&
        Objects.equals(this.serviceAccountCredentials, enterpriseCaptchaParams.serviceAccountCredentials) &&
        Objects.equals(this.serviceAccountCredentialsFileName, enterpriseCaptchaParams.serviceAccountCredentialsFileName) &&
        Objects.equals(this.androidKey, enterpriseCaptchaParams.androidKey) &&
        Objects.equals(this.iosKey, enterpriseCaptchaParams.iosKey) &&
        Objects.equals(this.logActionName, enterpriseCaptchaParams.logActionName) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(projectId, serviceAccountCredentials, serviceAccountCredentialsFileName, androidKey, iosKey, logActionName, super.hashCode());
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EnterpriseCaptchaParams {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    projectId: ").append(toIndentedString(projectId)).append("\n");
    sb.append("    serviceAccountCredentials: ").append(toIndentedString(serviceAccountCredentials)).append("\n");
    sb.append("    serviceAccountCredentialsFileName: ").append(toIndentedString(serviceAccountCredentialsFileName)).append("\n");
    sb.append("    androidKey: ").append(toIndentedString(androidKey)).append("\n");
    sb.append("    iosKey: ").append(toIndentedString(iosKey)).append("\n");
    sb.append("    logActionName: ").append(toIndentedString(logActionName)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `version` to the URL query string
    if (getVersion() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sversion%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getVersion()))));
    }

    // add `projectId` to the URL query string
    if (getProjectId() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sprojectId%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getProjectId()))));
    }

    // add `serviceAccountCredentials` to the URL query string
    if (getServiceAccountCredentials() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sserviceAccountCredentials%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getServiceAccountCredentials()))));
    }

    // add `serviceAccountCredentialsFileName` to the URL query string
    if (getServiceAccountCredentialsFileName() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sserviceAccountCredentialsFileName%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getServiceAccountCredentialsFileName()))));
    }

    // add `androidKey` to the URL query string
    if (getAndroidKey() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sandroidKey%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getAndroidKey()))));
    }

    // add `iosKey` to the URL query string
    if (getIosKey() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%siosKey%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getIosKey()))));
    }

    // add `logActionName` to the URL query string
    if (getLogActionName() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%slogActionName%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getLogActionName()))));
    }

    return joiner.toString();
  }
static {
  // Initialize and register the discriminator mappings.
  Map<String, Class<?>> mappings = new HashMap<String, Class<?>>();
  mappings.put("EnterpriseCaptchaParams", EnterpriseCaptchaParams.class);
  JSON.registerDiscriminator(EnterpriseCaptchaParams.class, "version", mappings);
}
}

