/**
 * Copyright © 2026-2026 ThingsBoard, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.thingsboard.client.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.Arrays;
import java.util.LinkedHashSet;
import java.util.Set;
import org.thingsboard.client.model.EntityType;
import org.thingsboard.client.model.NotificationRuleTriggerConfig;
import org.thingsboard.client.model.NotificationRuleTriggerType;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import org.thingsboard.client.JSON;
import org.thingsboard.client.ApiClient;
/**
 * EntitiesLimitNotificationRuleTriggerConfig
 */
@JsonPropertyOrder({
  EntitiesLimitNotificationRuleTriggerConfig.JSON_PROPERTY_ENTITY_TYPES,
  EntitiesLimitNotificationRuleTriggerConfig.JSON_PROPERTY_THRESHOLD
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.20.0")
@JsonIgnoreProperties(
  value = "triggerType", // ignore manually set triggerType, it will be automatically generated by Jackson during serialization
  allowSetters = true // allows the triggerType to be set during deserialization
)
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "triggerType", visible = true)

public class EntitiesLimitNotificationRuleTriggerConfig extends NotificationRuleTriggerConfig {
  public static final String JSON_PROPERTY_ENTITY_TYPES = "entityTypes";
  @javax.annotation.Nullable
  private Set<EntityType> entityTypes = new LinkedHashSet<>();

  public static final String JSON_PROPERTY_THRESHOLD = "threshold";
  @javax.annotation.Nullable
  private Float threshold;

  public EntitiesLimitNotificationRuleTriggerConfig() { 
  }

  public EntitiesLimitNotificationRuleTriggerConfig entityTypes(@javax.annotation.Nullable Set<EntityType> entityTypes) {
    this.entityTypes = entityTypes;
    return this;
  }

  public EntitiesLimitNotificationRuleTriggerConfig addEntityTypesItem(EntityType entityTypesItem) {
    if (this.entityTypes == null) {
      this.entityTypes = new LinkedHashSet<>();
    }
    this.entityTypes.add(entityTypesItem);
    return this;
  }

  /**
   * Get entityTypes
   * @return entityTypes
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ENTITY_TYPES, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Set<EntityType> getEntityTypes() {
    return entityTypes;
  }


  @JsonDeserialize(as = LinkedHashSet.class)
  @JsonProperty(value = JSON_PROPERTY_ENTITY_TYPES, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEntityTypes(@javax.annotation.Nullable Set<EntityType> entityTypes) {
    this.entityTypes = entityTypes;
  }


  public EntitiesLimitNotificationRuleTriggerConfig threshold(@javax.annotation.Nullable Float threshold) {
    this.threshold = threshold;
    return this;
  }

  /**
   * Get threshold
   * maximum: 1
   * @return threshold
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_THRESHOLD, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Float getThreshold() {
    return threshold;
  }


  @JsonProperty(value = JSON_PROPERTY_THRESHOLD, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setThreshold(@javax.annotation.Nullable Float threshold) {
    this.threshold = threshold;
  }


  /**
   * Return true if this EntitiesLimitNotificationRuleTriggerConfig object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EntitiesLimitNotificationRuleTriggerConfig entitiesLimitNotificationRuleTriggerConfig = (EntitiesLimitNotificationRuleTriggerConfig) o;
    return Objects.equals(this.entityTypes, entitiesLimitNotificationRuleTriggerConfig.entityTypes) &&
        Objects.equals(this.threshold, entitiesLimitNotificationRuleTriggerConfig.threshold) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(entityTypes, threshold, super.hashCode());
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EntitiesLimitNotificationRuleTriggerConfig {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    entityTypes: ").append(toIndentedString(entityTypes)).append("\n");
    sb.append("    threshold: ").append(toIndentedString(threshold)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `triggerType` to the URL query string
    if (getTriggerType() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%striggerType%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getTriggerType()))));
    }

    // add `entityTypes` to the URL query string
    if (getEntityTypes() != null) {
      int i = 0;
      for (EntityType _item : getEntityTypes()) {
        if (_item != null) {
          joiner.add(String.format(java.util.Locale.ROOT, "%sentityTypes%s%s=%s", prefix, suffix,
              "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix),
              ApiClient.urlEncode(ApiClient.valueToString(_item))));
        }
        i++;
      }
    }

    // add `threshold` to the URL query string
    if (getThreshold() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sthreshold%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getThreshold()))));
    }

    return joiner.toString();
  }
static {
  // Initialize and register the discriminator mappings.
  Map<String, Class<?>> mappings = new HashMap<String, Class<?>>();
  mappings.put("EntitiesLimitNotificationRuleTriggerConfig", EntitiesLimitNotificationRuleTriggerConfig.class);
  JSON.registerDiscriminator(EntitiesLimitNotificationRuleTriggerConfig.class, "triggerType", mappings);
}
}

