/**
 * Copyright © 2026-2026 ThingsBoard, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.thingsboard.client.model;

import javax.annotation.Generated;
import javax.annotation.Nonnull;
import javax.annotation.Nullable;
import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import java.util.HashMap;
import java.util.Map;
import org.thingsboard.client.model.AggInterval;
import org.thingsboard.client.model.AggMetric;
import org.thingsboard.client.model.Argument;
import org.thingsboard.client.model.CalculatedFieldConfiguration;
import org.thingsboard.client.model.Output;
import org.thingsboard.client.model.Watermark;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import org.thingsboard.client.JSON;
import org.thingsboard.client.ApiClient;
/**
 * EntityAggregationCalculatedFieldConfiguration
 */
@JsonPropertyOrder({
  EntityAggregationCalculatedFieldConfiguration.JSON_PROPERTY_ARGUMENTS,
  EntityAggregationCalculatedFieldConfiguration.JSON_PROPERTY_METRICS,
  EntityAggregationCalculatedFieldConfiguration.JSON_PROPERTY_INTERVAL,
  EntityAggregationCalculatedFieldConfiguration.JSON_PROPERTY_WATERMARK,
  EntityAggregationCalculatedFieldConfiguration.JSON_PROPERTY_PRODUCE_INTERMEDIATE_RESULT
})
@Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.20.0")
@JsonIgnoreProperties(
  value = "type", // ignore manually set type, it will be automatically generated by Jackson during serialization
  allowSetters = true // allows the type to be set during deserialization
)
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "type", visible = true)

public class EntityAggregationCalculatedFieldConfiguration extends CalculatedFieldConfiguration {
  public static final String JSON_PROPERTY_ARGUMENTS = "arguments";
  @Nonnull
  private Map<String, Argument> arguments = new HashMap<>();

  public static final String JSON_PROPERTY_METRICS = "metrics";
  @Nonnull
  private Map<String, AggMetric> metrics = new HashMap<>();

  public static final String JSON_PROPERTY_INTERVAL = "interval";
  @Nonnull
  private AggInterval interval;

  public static final String JSON_PROPERTY_WATERMARK = "watermark";
  @Nullable
  private Watermark watermark;

  public static final String JSON_PROPERTY_PRODUCE_INTERMEDIATE_RESULT = "produceIntermediateResult";
  @Nullable
  private Boolean produceIntermediateResult;

  public EntityAggregationCalculatedFieldConfiguration() { 
  }

  public EntityAggregationCalculatedFieldConfiguration arguments(@Nonnull Map<String, Argument> arguments) {
    this.arguments = arguments;
    return this;
  }

  public EntityAggregationCalculatedFieldConfiguration putArgumentsItem(String key, Argument argumentsItem) {
    if (this.arguments == null) {
      this.arguments = new HashMap<>();
    }
    this.arguments.put(key, argumentsItem);
    return this;
  }

  /**
   * Get arguments
   * @return arguments
   */
  @Nonnull
  @JsonProperty(value = JSON_PROPERTY_ARGUMENTS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Map<String, Argument> getArguments() {
    return arguments;
  }


  @JsonProperty(value = JSON_PROPERTY_ARGUMENTS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setArguments(@Nonnull Map<String, Argument> arguments) {
    this.arguments = arguments;
  }


  public EntityAggregationCalculatedFieldConfiguration metrics(@Nonnull Map<String, AggMetric> metrics) {
    this.metrics = metrics;
    return this;
  }

  public EntityAggregationCalculatedFieldConfiguration putMetricsItem(String key, AggMetric metricsItem) {
    if (this.metrics == null) {
      this.metrics = new HashMap<>();
    }
    this.metrics.put(key, metricsItem);
    return this;
  }

  /**
   * Get metrics
   * @return metrics
   */
  @Nonnull
  @JsonProperty(value = JSON_PROPERTY_METRICS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Map<String, AggMetric> getMetrics() {
    return metrics;
  }


  @JsonProperty(value = JSON_PROPERTY_METRICS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setMetrics(@Nonnull Map<String, AggMetric> metrics) {
    this.metrics = metrics;
  }


  public EntityAggregationCalculatedFieldConfiguration interval(@Nonnull AggInterval interval) {
    this.interval = interval;
    return this;
  }

  /**
   * Get interval
   * @return interval
   */
  @Nonnull
  @JsonProperty(value = JSON_PROPERTY_INTERVAL, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public AggInterval getInterval() {
    return interval;
  }


  @JsonProperty(value = JSON_PROPERTY_INTERVAL, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setInterval(@Nonnull AggInterval interval) {
    this.interval = interval;
  }


  public EntityAggregationCalculatedFieldConfiguration watermark(@Nullable Watermark watermark) {
    this.watermark = watermark;
    return this;
  }

  /**
   * Get watermark
   * @return watermark
   */
  @Nullable
  @JsonProperty(value = JSON_PROPERTY_WATERMARK, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Watermark getWatermark() {
    return watermark;
  }


  @JsonProperty(value = JSON_PROPERTY_WATERMARK, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setWatermark(@Nullable Watermark watermark) {
    this.watermark = watermark;
  }


  public EntityAggregationCalculatedFieldConfiguration produceIntermediateResult(@Nullable Boolean produceIntermediateResult) {
    this.produceIntermediateResult = produceIntermediateResult;
    return this;
  }

  /**
   * Get produceIntermediateResult
   * @return produceIntermediateResult
   */
  @Nullable
  @JsonProperty(value = JSON_PROPERTY_PRODUCE_INTERMEDIATE_RESULT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Boolean getProduceIntermediateResult() {
    return produceIntermediateResult;
  }


  @JsonProperty(value = JSON_PROPERTY_PRODUCE_INTERMEDIATE_RESULT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setProduceIntermediateResult(@Nullable Boolean produceIntermediateResult) {
    this.produceIntermediateResult = produceIntermediateResult;
  }


  @Override
  public EntityAggregationCalculatedFieldConfiguration output(@Nonnull Output output) {
    this.setOutput(output);
    return this;
  }

  @Override
  public EntityAggregationCalculatedFieldConfiguration type(@Nonnull String type) {
    this.setType(type);
    return this;
  }

  /**
   * Return true if this EntityAggregationCalculatedFieldConfiguration object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EntityAggregationCalculatedFieldConfiguration entityAggregationCalculatedFieldConfiguration = (EntityAggregationCalculatedFieldConfiguration) o;
    return Objects.equals(this.arguments, entityAggregationCalculatedFieldConfiguration.arguments) &&
        Objects.equals(this.metrics, entityAggregationCalculatedFieldConfiguration.metrics) &&
        Objects.equals(this.interval, entityAggregationCalculatedFieldConfiguration.interval) &&
        Objects.equals(this.watermark, entityAggregationCalculatedFieldConfiguration.watermark) &&
        Objects.equals(this.produceIntermediateResult, entityAggregationCalculatedFieldConfiguration.produceIntermediateResult) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(arguments, metrics, interval, watermark, produceIntermediateResult, super.hashCode());
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EntityAggregationCalculatedFieldConfiguration {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    arguments: ").append(toIndentedString(arguments)).append("\n");
    sb.append("    metrics: ").append(toIndentedString(metrics)).append("\n");
    sb.append("    interval: ").append(toIndentedString(interval)).append("\n");
    sb.append("    watermark: ").append(toIndentedString(watermark)).append("\n");
    sb.append("    produceIntermediateResult: ").append(toIndentedString(produceIntermediateResult)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `output` to the URL query string
    if (getOutput() != null) {
      joiner.add(getOutput().toUrlQueryString(prefix + "output" + suffix));
    }

    // add `type` to the URL query string
    if (getType() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%stype%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getType()))));
    }

    // add `arguments` to the URL query string
    if (getArguments() != null) {
      for (String _key : getArguments().keySet()) {
        if (getArguments().get(_key) != null) {
          joiner.add(getArguments().get(_key).toUrlQueryString(String.format(java.util.Locale.ROOT, "%sarguments%s%s", prefix, suffix,
              "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, _key, containerSuffix))));
        }
      }
    }

    // add `metrics` to the URL query string
    if (getMetrics() != null) {
      for (String _key : getMetrics().keySet()) {
        if (getMetrics().get(_key) != null) {
          joiner.add(getMetrics().get(_key).toUrlQueryString(String.format(java.util.Locale.ROOT, "%smetrics%s%s", prefix, suffix,
              "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, _key, containerSuffix))));
        }
      }
    }

    // add `interval` to the URL query string
    if (getInterval() != null) {
      joiner.add(getInterval().toUrlQueryString(prefix + "interval" + suffix));
    }

    // add `watermark` to the URL query string
    if (getWatermark() != null) {
      joiner.add(getWatermark().toUrlQueryString(prefix + "watermark" + suffix));
    }

    // add `produceIntermediateResult` to the URL query string
    if (getProduceIntermediateResult() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sproduceIntermediateResult%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getProduceIntermediateResult()))));
    }

    return joiner.toString();
  }
static {
  // Initialize and register the discriminator mappings.
  Map<String, Class<?>> mappings = new HashMap<String, Class<?>>();
  mappings.put("EntityAggregationCalculatedFieldConfiguration", EntityAggregationCalculatedFieldConfiguration.class);
  JSON.registerDiscriminator(EntityAggregationCalculatedFieldConfiguration.class, "type", mappings);
}
}

