/**
 * Copyright © 2026-2026 ThingsBoard, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.thingsboard.client.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.thingsboard.client.model.DataSource;
import org.thingsboard.client.model.ImageAlignment;
import org.thingsboard.client.model.ImageSourceType;
import org.thingsboard.client.model.ImageWidthType;
import org.thingsboard.client.model.Insets;
import org.thingsboard.client.model.ReportComponent;
import org.thingsboard.client.model.ReportComponentSubType;
import org.thingsboard.client.model.ReportComponentType;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import org.thingsboard.client.JSON;
import org.thingsboard.client.ApiClient;
/**
 * ImageComponent
 */
@JsonPropertyOrder({
  ImageComponent.JSON_PROPERTY_DATA_SOURCES,
  ImageComponent.JSON_PROPERTY_MARGINS,
  ImageComponent.JSON_PROPERTY_PADDINGS,
  ImageComponent.JSON_PROPERTY_BACKGROUND,
  ImageComponent.JSON_PROPERTY_BORDER_WIDTH,
  ImageComponent.JSON_PROPERTY_BORDER_RADIUS,
  ImageComponent.JSON_PROPERTY_BORDER_COLOR,
  ImageComponent.JSON_PROPERTY_WIDTH_TYPE,
  ImageComponent.JSON_PROPERTY_CUSTOM_WIDTH,
  ImageComponent.JSON_PROPERTY_ALIGNMENT,
  ImageComponent.JSON_PROPERTY_SOURCE_TYPE,
  ImageComponent.JSON_PROPERTY_IMAGE_URL
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-02-24T16:17:55.932789+02:00[Europe/Kiev]", comments = "Generator version: 7.20.0")
@JsonIgnoreProperties(
  value = "type", // ignore manually set type, it will be automatically generated by Jackson during serialization
  allowSetters = true // allows the type to be set during deserialization
)
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "type", visible = true)

public class ImageComponent extends ReportComponent {
  public static final String JSON_PROPERTY_DATA_SOURCES = "dataSources";
  @javax.annotation.Nullable
  private List<DataSource> dataSources = new ArrayList<>();

  public static final String JSON_PROPERTY_MARGINS = "margins";
  @javax.annotation.Nullable
  private Insets margins;

  public static final String JSON_PROPERTY_PADDINGS = "paddings";
  @javax.annotation.Nullable
  private Insets paddings;

  public static final String JSON_PROPERTY_BACKGROUND = "background";
  @javax.annotation.Nullable
  private String background;

  public static final String JSON_PROPERTY_BORDER_WIDTH = "borderWidth";
  @javax.annotation.Nullable
  private Integer borderWidth;

  public static final String JSON_PROPERTY_BORDER_RADIUS = "borderRadius";
  @javax.annotation.Nullable
  private Integer borderRadius;

  public static final String JSON_PROPERTY_BORDER_COLOR = "borderColor";
  @javax.annotation.Nullable
  private String borderColor;

  public static final String JSON_PROPERTY_WIDTH_TYPE = "widthType";
  @javax.annotation.Nullable
  private ImageWidthType widthType;

  public static final String JSON_PROPERTY_CUSTOM_WIDTH = "customWidth";
  @javax.annotation.Nullable
  private Integer customWidth;

  public static final String JSON_PROPERTY_ALIGNMENT = "alignment";
  @javax.annotation.Nullable
  private ImageAlignment alignment;

  public static final String JSON_PROPERTY_SOURCE_TYPE = "sourceType";
  @javax.annotation.Nullable
  private ImageSourceType sourceType;

  public static final String JSON_PROPERTY_IMAGE_URL = "imageUrl";
  @javax.annotation.Nullable
  private String imageUrl;

  public ImageComponent() { 
  }

  public ImageComponent dataSources(@javax.annotation.Nullable List<DataSource> dataSources) {
    this.dataSources = dataSources;
    return this;
  }

  public ImageComponent addDataSourcesItem(DataSource dataSourcesItem) {
    if (this.dataSources == null) {
      this.dataSources = new ArrayList<>();
    }
    this.dataSources.add(dataSourcesItem);
    return this;
  }

  /**
   * Get dataSources
   * @return dataSources
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_DATA_SOURCES, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public List<DataSource> getDataSources() {
    return dataSources;
  }


  @JsonProperty(value = JSON_PROPERTY_DATA_SOURCES, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDataSources(@javax.annotation.Nullable List<DataSource> dataSources) {
    this.dataSources = dataSources;
  }


  public ImageComponent margins(@javax.annotation.Nullable Insets margins) {
    this.margins = margins;
    return this;
  }

  /**
   * Get margins
   * @return margins
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_MARGINS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Insets getMargins() {
    return margins;
  }


  @JsonProperty(value = JSON_PROPERTY_MARGINS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMargins(@javax.annotation.Nullable Insets margins) {
    this.margins = margins;
  }


  public ImageComponent paddings(@javax.annotation.Nullable Insets paddings) {
    this.paddings = paddings;
    return this;
  }

  /**
   * Get paddings
   * @return paddings
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PADDINGS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Insets getPaddings() {
    return paddings;
  }


  @JsonProperty(value = JSON_PROPERTY_PADDINGS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPaddings(@javax.annotation.Nullable Insets paddings) {
    this.paddings = paddings;
  }


  public ImageComponent background(@javax.annotation.Nullable String background) {
    this.background = background;
    return this;
  }

  /**
   * Get background
   * @return background
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_BACKGROUND, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getBackground() {
    return background;
  }


  @JsonProperty(value = JSON_PROPERTY_BACKGROUND, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setBackground(@javax.annotation.Nullable String background) {
    this.background = background;
  }


  public ImageComponent borderWidth(@javax.annotation.Nullable Integer borderWidth) {
    this.borderWidth = borderWidth;
    return this;
  }

  /**
   * Get borderWidth
   * @return borderWidth
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_BORDER_WIDTH, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Integer getBorderWidth() {
    return borderWidth;
  }


  @JsonProperty(value = JSON_PROPERTY_BORDER_WIDTH, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setBorderWidth(@javax.annotation.Nullable Integer borderWidth) {
    this.borderWidth = borderWidth;
  }


  public ImageComponent borderRadius(@javax.annotation.Nullable Integer borderRadius) {
    this.borderRadius = borderRadius;
    return this;
  }

  /**
   * Get borderRadius
   * @return borderRadius
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_BORDER_RADIUS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Integer getBorderRadius() {
    return borderRadius;
  }


  @JsonProperty(value = JSON_PROPERTY_BORDER_RADIUS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setBorderRadius(@javax.annotation.Nullable Integer borderRadius) {
    this.borderRadius = borderRadius;
  }


  public ImageComponent borderColor(@javax.annotation.Nullable String borderColor) {
    this.borderColor = borderColor;
    return this;
  }

  /**
   * Get borderColor
   * @return borderColor
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_BORDER_COLOR, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getBorderColor() {
    return borderColor;
  }


  @JsonProperty(value = JSON_PROPERTY_BORDER_COLOR, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setBorderColor(@javax.annotation.Nullable String borderColor) {
    this.borderColor = borderColor;
  }


  public ImageComponent widthType(@javax.annotation.Nullable ImageWidthType widthType) {
    this.widthType = widthType;
    return this;
  }

  /**
   * Get widthType
   * @return widthType
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_WIDTH_TYPE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public ImageWidthType getWidthType() {
    return widthType;
  }


  @JsonProperty(value = JSON_PROPERTY_WIDTH_TYPE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setWidthType(@javax.annotation.Nullable ImageWidthType widthType) {
    this.widthType = widthType;
  }


  public ImageComponent customWidth(@javax.annotation.Nullable Integer customWidth) {
    this.customWidth = customWidth;
    return this;
  }

  /**
   * Get customWidth
   * @return customWidth
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CUSTOM_WIDTH, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Integer getCustomWidth() {
    return customWidth;
  }


  @JsonProperty(value = JSON_PROPERTY_CUSTOM_WIDTH, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCustomWidth(@javax.annotation.Nullable Integer customWidth) {
    this.customWidth = customWidth;
  }


  public ImageComponent alignment(@javax.annotation.Nullable ImageAlignment alignment) {
    this.alignment = alignment;
    return this;
  }

  /**
   * Get alignment
   * @return alignment
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ALIGNMENT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public ImageAlignment getAlignment() {
    return alignment;
  }


  @JsonProperty(value = JSON_PROPERTY_ALIGNMENT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAlignment(@javax.annotation.Nullable ImageAlignment alignment) {
    this.alignment = alignment;
  }


  public ImageComponent sourceType(@javax.annotation.Nullable ImageSourceType sourceType) {
    this.sourceType = sourceType;
    return this;
  }

  /**
   * Get sourceType
   * @return sourceType
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_SOURCE_TYPE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public ImageSourceType getSourceType() {
    return sourceType;
  }


  @JsonProperty(value = JSON_PROPERTY_SOURCE_TYPE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSourceType(@javax.annotation.Nullable ImageSourceType sourceType) {
    this.sourceType = sourceType;
  }


  public ImageComponent imageUrl(@javax.annotation.Nullable String imageUrl) {
    this.imageUrl = imageUrl;
    return this;
  }

  /**
   * Get imageUrl
   * @return imageUrl
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_IMAGE_URL, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getImageUrl() {
    return imageUrl;
  }


  @JsonProperty(value = JSON_PROPERTY_IMAGE_URL, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setImageUrl(@javax.annotation.Nullable String imageUrl) {
    this.imageUrl = imageUrl;
  }


  @Override
  public ImageComponent subType(@javax.annotation.Nonnull ReportComponentSubType subType) {
    this.setSubType(subType);
    return this;
  }

  @Override
  public ImageComponent type(@javax.annotation.Nonnull ReportComponentType type) {
    this.setType(type);
    return this;
  }

  /**
   * Return true if this ImageComponent object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ImageComponent imageComponent = (ImageComponent) o;
    return Objects.equals(this.dataSources, imageComponent.dataSources) &&
        Objects.equals(this.margins, imageComponent.margins) &&
        Objects.equals(this.paddings, imageComponent.paddings) &&
        Objects.equals(this.background, imageComponent.background) &&
        Objects.equals(this.borderWidth, imageComponent.borderWidth) &&
        Objects.equals(this.borderRadius, imageComponent.borderRadius) &&
        Objects.equals(this.borderColor, imageComponent.borderColor) &&
        Objects.equals(this.widthType, imageComponent.widthType) &&
        Objects.equals(this.customWidth, imageComponent.customWidth) &&
        Objects.equals(this.alignment, imageComponent.alignment) &&
        Objects.equals(this.sourceType, imageComponent.sourceType) &&
        Objects.equals(this.imageUrl, imageComponent.imageUrl) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(dataSources, margins, paddings, background, borderWidth, borderRadius, borderColor, widthType, customWidth, alignment, sourceType, imageUrl, super.hashCode());
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ImageComponent {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    dataSources: ").append(toIndentedString(dataSources)).append("\n");
    sb.append("    margins: ").append(toIndentedString(margins)).append("\n");
    sb.append("    paddings: ").append(toIndentedString(paddings)).append("\n");
    sb.append("    background: ").append(toIndentedString(background)).append("\n");
    sb.append("    borderWidth: ").append(toIndentedString(borderWidth)).append("\n");
    sb.append("    borderRadius: ").append(toIndentedString(borderRadius)).append("\n");
    sb.append("    borderColor: ").append(toIndentedString(borderColor)).append("\n");
    sb.append("    widthType: ").append(toIndentedString(widthType)).append("\n");
    sb.append("    customWidth: ").append(toIndentedString(customWidth)).append("\n");
    sb.append("    alignment: ").append(toIndentedString(alignment)).append("\n");
    sb.append("    sourceType: ").append(toIndentedString(sourceType)).append("\n");
    sb.append("    imageUrl: ").append(toIndentedString(imageUrl)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `subType` to the URL query string
    if (getSubType() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%ssubType%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getSubType()))));
    }

    // add `type` to the URL query string
    if (getType() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%stype%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getType()))));
    }

    // add `dataSources` to the URL query string
    if (getDataSources() != null) {
      for (int i = 0; i < getDataSources().size(); i++) {
        if (getDataSources().get(i) != null) {
          joiner.add(getDataSources().get(i).toUrlQueryString(String.format(java.util.Locale.ROOT, "%sdataSources%s%s", prefix, suffix,
          "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix))));
        }
      }
    }

    // add `margins` to the URL query string
    if (getMargins() != null) {
      joiner.add(getMargins().toUrlQueryString(prefix + "margins" + suffix));
    }

    // add `paddings` to the URL query string
    if (getPaddings() != null) {
      joiner.add(getPaddings().toUrlQueryString(prefix + "paddings" + suffix));
    }

    // add `background` to the URL query string
    if (getBackground() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sbackground%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getBackground()))));
    }

    // add `borderWidth` to the URL query string
    if (getBorderWidth() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sborderWidth%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getBorderWidth()))));
    }

    // add `borderRadius` to the URL query string
    if (getBorderRadius() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sborderRadius%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getBorderRadius()))));
    }

    // add `borderColor` to the URL query string
    if (getBorderColor() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sborderColor%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getBorderColor()))));
    }

    // add `widthType` to the URL query string
    if (getWidthType() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%swidthType%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getWidthType()))));
    }

    // add `customWidth` to the URL query string
    if (getCustomWidth() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%scustomWidth%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getCustomWidth()))));
    }

    // add `alignment` to the URL query string
    if (getAlignment() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%salignment%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getAlignment()))));
    }

    // add `sourceType` to the URL query string
    if (getSourceType() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%ssourceType%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getSourceType()))));
    }

    // add `imageUrl` to the URL query string
    if (getImageUrl() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%simageUrl%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getImageUrl()))));
    }

    return joiner.toString();
  }
static {
  // Initialize and register the discriminator mappings.
  Map<String, Class<?>> mappings = new HashMap<String, Class<?>>();
  mappings.put("ImageComponent", ImageComponent.class);
  JSON.registerDiscriminator(ImageComponent.class, "type", mappings);
}
}

