/**
 * Copyright © 2026-2026 ThingsBoard, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.thingsboard.client.model;

import javax.annotation.Generated;
import javax.annotation.Nonnull;
import javax.annotation.Nullable;
import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.thingsboard.client.model.DeviceProfileTransportConfiguration;
import org.thingsboard.client.model.LwM2MBootstrapServerCredential;
import org.thingsboard.client.model.OtherConfiguration;
import org.thingsboard.client.model.TelemetryMappingConfiguration;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import org.thingsboard.client.JSON;
import org.thingsboard.client.ApiClient;
/**
 * Lwm2mDeviceProfileTransportConfiguration
 */
@JsonPropertyOrder({
  Lwm2mDeviceProfileTransportConfiguration.JSON_PROPERTY_OBSERVE_ATTR,
  Lwm2mDeviceProfileTransportConfiguration.JSON_PROPERTY_BOOTSTRAP_SERVER_UPDATE_ENABLE,
  Lwm2mDeviceProfileTransportConfiguration.JSON_PROPERTY_BOOTSTRAP,
  Lwm2mDeviceProfileTransportConfiguration.JSON_PROPERTY_CLIENT_LW_M2M_SETTINGS
})
@Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.20.0")
@JsonIgnoreProperties(
  value = "type", // ignore manually set type, it will be automatically generated by Jackson during serialization
  allowSetters = true // allows the type to be set during deserialization
)
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "type", visible = true)

public class Lwm2mDeviceProfileTransportConfiguration extends DeviceProfileTransportConfiguration {
  public static final String JSON_PROPERTY_OBSERVE_ATTR = "observeAttr";
  @Nullable
  private TelemetryMappingConfiguration observeAttr;

  public static final String JSON_PROPERTY_BOOTSTRAP_SERVER_UPDATE_ENABLE = "bootstrapServerUpdateEnable";
  @Nullable
  private Boolean bootstrapServerUpdateEnable;

  public static final String JSON_PROPERTY_BOOTSTRAP = "bootstrap";
  @Nullable
  private List<LwM2MBootstrapServerCredential> bootstrap = new ArrayList<>();

  public static final String JSON_PROPERTY_CLIENT_LW_M2M_SETTINGS = "clientLwM2mSettings";
  @Nullable
  private OtherConfiguration clientLwM2mSettings;

  public Lwm2mDeviceProfileTransportConfiguration() { 
  }

  public Lwm2mDeviceProfileTransportConfiguration observeAttr(@Nullable TelemetryMappingConfiguration observeAttr) {
    this.observeAttr = observeAttr;
    return this;
  }

  /**
   * Configuration for mapping LwM2M resources to telemetry and attributes
   * @return observeAttr
   */
  @Nullable
  @JsonProperty(value = JSON_PROPERTY_OBSERVE_ATTR, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public TelemetryMappingConfiguration getObserveAttr() {
    return observeAttr;
  }


  @JsonProperty(value = JSON_PROPERTY_OBSERVE_ATTR, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setObserveAttr(@Nullable TelemetryMappingConfiguration observeAttr) {
    this.observeAttr = observeAttr;
  }


  public Lwm2mDeviceProfileTransportConfiguration bootstrapServerUpdateEnable(@Nullable Boolean bootstrapServerUpdateEnable) {
    this.bootstrapServerUpdateEnable = bootstrapServerUpdateEnable;
    return this;
  }

  /**
   * Flag indicating whether LwM2M bootstrap server update is enabled
   * @return bootstrapServerUpdateEnable
   */
  @Nullable
  @JsonProperty(value = JSON_PROPERTY_BOOTSTRAP_SERVER_UPDATE_ENABLE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Boolean getBootstrapServerUpdateEnable() {
    return bootstrapServerUpdateEnable;
  }


  @JsonProperty(value = JSON_PROPERTY_BOOTSTRAP_SERVER_UPDATE_ENABLE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setBootstrapServerUpdateEnable(@Nullable Boolean bootstrapServerUpdateEnable) {
    this.bootstrapServerUpdateEnable = bootstrapServerUpdateEnable;
  }


  public Lwm2mDeviceProfileTransportConfiguration bootstrap(@Nullable List<LwM2MBootstrapServerCredential> bootstrap) {
    this.bootstrap = bootstrap;
    return this;
  }

  public Lwm2mDeviceProfileTransportConfiguration addBootstrapItem(LwM2MBootstrapServerCredential bootstrapItem) {
    if (this.bootstrap == null) {
      this.bootstrap = new ArrayList<>();
    }
    this.bootstrap.add(bootstrapItem);
    return this;
  }

  /**
   * Get bootstrap
   * @return bootstrap
   */
  @Nullable
  @JsonProperty(value = JSON_PROPERTY_BOOTSTRAP, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public List<LwM2MBootstrapServerCredential> getBootstrap() {
    return bootstrap;
  }


  @JsonProperty(value = JSON_PROPERTY_BOOTSTRAP, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setBootstrap(@Nullable List<LwM2MBootstrapServerCredential> bootstrap) {
    this.bootstrap = bootstrap;
  }


  public Lwm2mDeviceProfileTransportConfiguration clientLwM2mSettings(@Nullable OtherConfiguration clientLwM2mSettings) {
    this.clientLwM2mSettings = clientLwM2mSettings;
    return this;
  }

  /**
   * Other LwM2M client settings
   * @return clientLwM2mSettings
   */
  @Nullable
  @JsonProperty(value = JSON_PROPERTY_CLIENT_LW_M2M_SETTINGS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public OtherConfiguration getClientLwM2mSettings() {
    return clientLwM2mSettings;
  }


  @JsonProperty(value = JSON_PROPERTY_CLIENT_LW_M2M_SETTINGS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setClientLwM2mSettings(@Nullable OtherConfiguration clientLwM2mSettings) {
    this.clientLwM2mSettings = clientLwM2mSettings;
  }


  @Override
  public Lwm2mDeviceProfileTransportConfiguration type(@Nonnull String type) {
    this.setType(type);
    return this;
  }

  /**
   * Return true if this Lwm2mDeviceProfileTransportConfiguration object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Lwm2mDeviceProfileTransportConfiguration lwm2mDeviceProfileTransportConfiguration = (Lwm2mDeviceProfileTransportConfiguration) o;
    return Objects.equals(this.observeAttr, lwm2mDeviceProfileTransportConfiguration.observeAttr) &&
        Objects.equals(this.bootstrapServerUpdateEnable, lwm2mDeviceProfileTransportConfiguration.bootstrapServerUpdateEnable) &&
        Objects.equals(this.bootstrap, lwm2mDeviceProfileTransportConfiguration.bootstrap) &&
        Objects.equals(this.clientLwM2mSettings, lwm2mDeviceProfileTransportConfiguration.clientLwM2mSettings) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(observeAttr, bootstrapServerUpdateEnable, bootstrap, clientLwM2mSettings, super.hashCode());
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Lwm2mDeviceProfileTransportConfiguration {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    observeAttr: ").append(toIndentedString(observeAttr)).append("\n");
    sb.append("    bootstrapServerUpdateEnable: ").append(toIndentedString(bootstrapServerUpdateEnable)).append("\n");
    sb.append("    bootstrap: ").append(toIndentedString(bootstrap)).append("\n");
    sb.append("    clientLwM2mSettings: ").append(toIndentedString(clientLwM2mSettings)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `type` to the URL query string
    if (getType() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%stype%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getType()))));
    }

    // add `observeAttr` to the URL query string
    if (getObserveAttr() != null) {
      joiner.add(getObserveAttr().toUrlQueryString(prefix + "observeAttr" + suffix));
    }

    // add `bootstrapServerUpdateEnable` to the URL query string
    if (getBootstrapServerUpdateEnable() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sbootstrapServerUpdateEnable%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getBootstrapServerUpdateEnable()))));
    }

    // add `bootstrap` to the URL query string
    if (getBootstrap() != null) {
      for (int i = 0; i < getBootstrap().size(); i++) {
        if (getBootstrap().get(i) != null) {
          joiner.add(getBootstrap().get(i).toUrlQueryString(String.format(java.util.Locale.ROOT, "%sbootstrap%s%s", prefix, suffix,
          "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix))));
        }
      }
    }

    // add `clientLwM2mSettings` to the URL query string
    if (getClientLwM2mSettings() != null) {
      joiner.add(getClientLwM2mSettings().toUrlQueryString(prefix + "clientLwM2mSettings" + suffix));
    }

    return joiner.toString();
  }
static {
  // Initialize and register the discriminator mappings.
  Map<String, Class<?>> mappings = new HashMap<String, Class<?>>();
  mappings.put("Lwm2mDeviceProfileTransportConfiguration", Lwm2mDeviceProfileTransportConfiguration.class);
  JSON.registerDiscriminator(Lwm2mDeviceProfileTransportConfiguration.class, "type", mappings);
}
}

