/**
 * Copyright © 2026-2026 ThingsBoard, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.thingsboard.client.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import org.openapitools.jackson.nullable.JsonNullable;
import org.thingsboard.client.model.NotificationTargetConfig;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import org.thingsboard.client.JSON;
import org.thingsboard.client.ApiClient;
/**
 * MicrosoftTeamsNotificationTargetConfig
 */
@JsonPropertyOrder({
  MicrosoftTeamsNotificationTargetConfig.JSON_PROPERTY_WEBHOOK_URL,
  MicrosoftTeamsNotificationTargetConfig.JSON_PROPERTY_CHANNEL_NAME,
  MicrosoftTeamsNotificationTargetConfig.JSON_PROPERTY_USE_OLD_API,
  MicrosoftTeamsNotificationTargetConfig.JSON_PROPERTY_TITLE,
  MicrosoftTeamsNotificationTargetConfig.JSON_PROPERTY_ID,
  MicrosoftTeamsNotificationTargetConfig.JSON_PROPERTY_EMAIL,
  MicrosoftTeamsNotificationTargetConfig.JSON_PROPERTY_FIRST_NAME,
  MicrosoftTeamsNotificationTargetConfig.JSON_PROPERTY_LAST_NAME
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-02-24T16:17:55.932789+02:00[Europe/Kiev]", comments = "Generator version: 7.20.0")
@JsonIgnoreProperties(
  value = "type", // ignore manually set type, it will be automatically generated by Jackson during serialization
  allowSetters = true // allows the type to be set during deserialization
)
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "type", visible = true)

public class MicrosoftTeamsNotificationTargetConfig extends NotificationTargetConfig {
  public static final String JSON_PROPERTY_WEBHOOK_URL = "webhookUrl";
  @javax.annotation.Nonnull
  private String webhookUrl;

  public static final String JSON_PROPERTY_CHANNEL_NAME = "channelName";
  @javax.annotation.Nonnull
  private String channelName;

  public static final String JSON_PROPERTY_USE_OLD_API = "useOldApi";
  @javax.annotation.Nullable
  private Boolean useOldApi;

  public static final String JSON_PROPERTY_TITLE = "title";
  @javax.annotation.Nullable
  private String title;

  public static final String JSON_PROPERTY_ID = "id";
  private JsonNullable<Object> id = JsonNullable.<Object>of(null);

  public static final String JSON_PROPERTY_EMAIL = "email";
  @javax.annotation.Nullable
  private String email;

  public static final String JSON_PROPERTY_FIRST_NAME = "firstName";
  @javax.annotation.Nullable
  private String firstName;

  public static final String JSON_PROPERTY_LAST_NAME = "lastName";
  @javax.annotation.Nullable
  private String lastName;

  public MicrosoftTeamsNotificationTargetConfig() { 
  }

  public MicrosoftTeamsNotificationTargetConfig webhookUrl(@javax.annotation.Nonnull String webhookUrl) {
    this.webhookUrl = webhookUrl;
    return this;
  }

  /**
   * Get webhookUrl
   * @return webhookUrl
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_WEBHOOK_URL, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getWebhookUrl() {
    return webhookUrl;
  }


  @JsonProperty(value = JSON_PROPERTY_WEBHOOK_URL, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setWebhookUrl(@javax.annotation.Nonnull String webhookUrl) {
    this.webhookUrl = webhookUrl;
  }


  public MicrosoftTeamsNotificationTargetConfig channelName(@javax.annotation.Nonnull String channelName) {
    this.channelName = channelName;
    return this;
  }

  /**
   * Get channelName
   * @return channelName
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_CHANNEL_NAME, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getChannelName() {
    return channelName;
  }


  @JsonProperty(value = JSON_PROPERTY_CHANNEL_NAME, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setChannelName(@javax.annotation.Nonnull String channelName) {
    this.channelName = channelName;
  }


  public MicrosoftTeamsNotificationTargetConfig useOldApi(@javax.annotation.Nullable Boolean useOldApi) {
    this.useOldApi = useOldApi;
    return this;
  }

  /**
   * Get useOldApi
   * @return useOldApi
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_USE_OLD_API, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Boolean getUseOldApi() {
    return useOldApi;
  }


  @JsonProperty(value = JSON_PROPERTY_USE_OLD_API, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUseOldApi(@javax.annotation.Nullable Boolean useOldApi) {
    this.useOldApi = useOldApi;
  }


  public MicrosoftTeamsNotificationTargetConfig title(@javax.annotation.Nullable String title) {
    this.title = title;
    return this;
  }

  /**
   * Get title
   * @return title
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TITLE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getTitle() {
    return title;
  }


  @JsonProperty(value = JSON_PROPERTY_TITLE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTitle(@javax.annotation.Nullable String title) {
    this.title = title;
  }


  public MicrosoftTeamsNotificationTargetConfig id(@javax.annotation.Nullable Object id) {
    this.id = JsonNullable.<Object>of(id);
    return this;
  }

  /**
   * Get id
   * @return id
   */
  @javax.annotation.Nullable
  @JsonIgnore
  public Object getId() {
        return id.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<Object> getId_JsonNullable() {
    return id;
  }
  
  @JsonProperty(JSON_PROPERTY_ID)
  public void setId_JsonNullable(JsonNullable<Object> id) {
    this.id = id;
  }

  public void setId(@javax.annotation.Nullable Object id) {
    this.id = JsonNullable.<Object>of(id);
  }


  public MicrosoftTeamsNotificationTargetConfig email(@javax.annotation.Nullable String email) {
    this.email = email;
    return this;
  }

  /**
   * Get email
   * @return email
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_EMAIL, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getEmail() {
    return email;
  }


  @JsonProperty(value = JSON_PROPERTY_EMAIL, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEmail(@javax.annotation.Nullable String email) {
    this.email = email;
  }


  public MicrosoftTeamsNotificationTargetConfig firstName(@javax.annotation.Nullable String firstName) {
    this.firstName = firstName;
    return this;
  }

  /**
   * Get firstName
   * @return firstName
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_FIRST_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getFirstName() {
    return firstName;
  }


  @JsonProperty(value = JSON_PROPERTY_FIRST_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFirstName(@javax.annotation.Nullable String firstName) {
    this.firstName = firstName;
  }


  public MicrosoftTeamsNotificationTargetConfig lastName(@javax.annotation.Nullable String lastName) {
    this.lastName = lastName;
    return this;
  }

  /**
   * Get lastName
   * @return lastName
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_LAST_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getLastName() {
    return lastName;
  }


  @JsonProperty(value = JSON_PROPERTY_LAST_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLastName(@javax.annotation.Nullable String lastName) {
    this.lastName = lastName;
  }


  @Override
  public MicrosoftTeamsNotificationTargetConfig description(@javax.annotation.Nullable String description) {
    this.setDescription(description);
    return this;
  }

  @Override
  public MicrosoftTeamsNotificationTargetConfig type(@javax.annotation.Nonnull String type) {
    this.setType(type);
    return this;
  }

  /**
   * Return true if this MicrosoftTeamsNotificationTargetConfig object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MicrosoftTeamsNotificationTargetConfig microsoftTeamsNotificationTargetConfig = (MicrosoftTeamsNotificationTargetConfig) o;
    return Objects.equals(this.webhookUrl, microsoftTeamsNotificationTargetConfig.webhookUrl) &&
        Objects.equals(this.channelName, microsoftTeamsNotificationTargetConfig.channelName) &&
        Objects.equals(this.useOldApi, microsoftTeamsNotificationTargetConfig.useOldApi) &&
        Objects.equals(this.title, microsoftTeamsNotificationTargetConfig.title) &&
        equalsNullable(this.id, microsoftTeamsNotificationTargetConfig.id) &&
        Objects.equals(this.email, microsoftTeamsNotificationTargetConfig.email) &&
        Objects.equals(this.firstName, microsoftTeamsNotificationTargetConfig.firstName) &&
        Objects.equals(this.lastName, microsoftTeamsNotificationTargetConfig.lastName) &&
        super.equals(o);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(webhookUrl, channelName, useOldApi, title, hashCodeNullable(id), email, firstName, lastName, super.hashCode());
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MicrosoftTeamsNotificationTargetConfig {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    webhookUrl: ").append(toIndentedString(webhookUrl)).append("\n");
    sb.append("    channelName: ").append(toIndentedString(channelName)).append("\n");
    sb.append("    useOldApi: ").append(toIndentedString(useOldApi)).append("\n");
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    email: ").append(toIndentedString(email)).append("\n");
    sb.append("    firstName: ").append(toIndentedString(firstName)).append("\n");
    sb.append("    lastName: ").append(toIndentedString(lastName)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `description` to the URL query string
    if (getDescription() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sdescription%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getDescription()))));
    }

    // add `type` to the URL query string
    if (getType() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%stype%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getType()))));
    }

    // add `webhookUrl` to the URL query string
    if (getWebhookUrl() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%swebhookUrl%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getWebhookUrl()))));
    }

    // add `channelName` to the URL query string
    if (getChannelName() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%schannelName%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getChannelName()))));
    }

    // add `useOldApi` to the URL query string
    if (getUseOldApi() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%suseOldApi%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getUseOldApi()))));
    }

    // add `title` to the URL query string
    if (getTitle() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%stitle%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getTitle()))));
    }

    // add `id` to the URL query string
    if (getId() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sid%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getId()))));
    }

    // add `email` to the URL query string
    if (getEmail() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%semail%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getEmail()))));
    }

    // add `firstName` to the URL query string
    if (getFirstName() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sfirstName%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getFirstName()))));
    }

    // add `lastName` to the URL query string
    if (getLastName() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%slastName%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getLastName()))));
    }

    return joiner.toString();
  }
static {
  // Initialize and register the discriminator mappings.
  Map<String, Class<?>> mappings = new HashMap<String, Class<?>>();
  mappings.put("MicrosoftTeamsNotificationTargetConfig", MicrosoftTeamsNotificationTargetConfig.class);
  JSON.registerDiscriminator(MicrosoftTeamsNotificationTargetConfig.class, "type", mappings);
}
}

