/**
 * Copyright © 2026-2026 ThingsBoard, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.thingsboard.client.model;

import javax.annotation.Generated;
import javax.annotation.Nonnull;
import javax.annotation.Nullable;
import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.thingsboard.client.model.JobResult;
import org.thingsboard.client.model.Report;
import org.thingsboard.client.model.TaskResult;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import org.thingsboard.client.JSON;
import org.thingsboard.client.ApiClient;
/**
 * ReportJobResult
 */
@JsonPropertyOrder({
  ReportJobResult.JSON_PROPERTY_REPORT
})
@Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.20.0")
@JsonIgnoreProperties(
  value = "jobType", // ignore manually set jobType, it will be automatically generated by Jackson during serialization
  allowSetters = true // allows the jobType to be set during deserialization
)
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "jobType", visible = true)

public class ReportJobResult extends JobResult {
  public static final String JSON_PROPERTY_REPORT = "report";
  @Nullable
  private Report report;

  public ReportJobResult() { 
  }

  public ReportJobResult report(@Nullable Report report) {
    this.report = report;
    return this;
  }

  /**
   * Get report
   * @return report
   */
  @Nullable
  @JsonProperty(value = JSON_PROPERTY_REPORT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Report getReport() {
    return report;
  }


  @JsonProperty(value = JSON_PROPERTY_REPORT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setReport(@Nullable Report report) {
    this.report = report;
  }


  @Override
  public ReportJobResult successfulCount(@Nullable Integer successfulCount) {
    this.setSuccessfulCount(successfulCount);
    return this;
  }

  @Override
  public ReportJobResult failedCount(@Nullable Integer failedCount) {
    this.setFailedCount(failedCount);
    return this;
  }

  @Override
  public ReportJobResult discardedCount(@Nullable Integer discardedCount) {
    this.setDiscardedCount(discardedCount);
    return this;
  }

  @Override
  public ReportJobResult totalCount(@Nullable Integer totalCount) {
    this.setTotalCount(totalCount);
    return this;
  }

  @Override
  public ReportJobResult results(@Nullable List<TaskResult> results) {
    this.setResults(results);
    return this;
  }

  @Override
  public ReportJobResult generalError(@Nullable String generalError) {
    this.setGeneralError(generalError);
    return this;
  }

  @Override
  public ReportJobResult startTs(@Nullable Long startTs) {
    this.setStartTs(startTs);
    return this;
  }

  @Override
  public ReportJobResult finishTs(@Nullable Long finishTs) {
    this.setFinishTs(finishTs);
    return this;
  }

  @Override
  public ReportJobResult cancellationTs(@Nullable Long cancellationTs) {
    this.setCancellationTs(cancellationTs);
    return this;
  }

  @Override
  public ReportJobResult jobType(@Nonnull String jobType) {
    this.setJobType(jobType);
    return this;
  }

  /**
   * Return true if this ReportJobResult object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ReportJobResult reportJobResult = (ReportJobResult) o;
    return Objects.equals(this.report, reportJobResult.report) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(report, super.hashCode());
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ReportJobResult {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    report: ").append(toIndentedString(report)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `successfulCount` to the URL query string
    if (getSuccessfulCount() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%ssuccessfulCount%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getSuccessfulCount()))));
    }

    // add `failedCount` to the URL query string
    if (getFailedCount() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sfailedCount%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getFailedCount()))));
    }

    // add `discardedCount` to the URL query string
    if (getDiscardedCount() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sdiscardedCount%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getDiscardedCount()))));
    }

    // add `totalCount` to the URL query string
    if (getTotalCount() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%stotalCount%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getTotalCount()))));
    }

    // add `results` to the URL query string
    if (getResults() != null) {
      for (int i = 0; i < getResults().size(); i++) {
        if (getResults().get(i) != null) {
          joiner.add(getResults().get(i).toUrlQueryString(String.format(java.util.Locale.ROOT, "%sresults%s%s", prefix, suffix,
          "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix))));
        }
      }
    }

    // add `generalError` to the URL query string
    if (getGeneralError() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sgeneralError%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getGeneralError()))));
    }

    // add `startTs` to the URL query string
    if (getStartTs() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sstartTs%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getStartTs()))));
    }

    // add `finishTs` to the URL query string
    if (getFinishTs() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sfinishTs%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getFinishTs()))));
    }

    // add `cancellationTs` to the URL query string
    if (getCancellationTs() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%scancellationTs%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getCancellationTs()))));
    }

    // add `jobType` to the URL query string
    if (getJobType() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sjobType%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getJobType()))));
    }

    // add `report` to the URL query string
    if (getReport() != null) {
      joiner.add(getReport().toUrlQueryString(prefix + "report" + suffix));
    }

    return joiner.toString();
  }
static {
  // Initialize and register the discriminator mappings.
  Map<String, Class<?>> mappings = new HashMap<String, Class<?>>();
  mappings.put("ReportJobResult", ReportJobResult.class);
  JSON.registerDiscriminator(ReportJobResult.class, "jobType", mappings);
}
}

