/**
 * Copyright © 2026-2026 ThingsBoard, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.thingsboard.client.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.thingsboard.client.model.ComparisonDuration;
import org.thingsboard.client.model.Font;
import org.thingsboard.client.model.LegendConfig;
import org.thingsboard.client.model.TextAlignment;
import org.thingsboard.client.model.TimeSeriesChartBarWidthSettings;
import org.thingsboard.client.model.TimeSeriesChartGridSettings;
import org.thingsboard.client.model.TimeSeriesChartNoAggregationBarWidthSettings;
import org.thingsboard.client.model.TimeSeriesChartStateSettings;
import org.thingsboard.client.model.TimeSeriesChartThreshold;
import org.thingsboard.client.model.TimeSeriesChartXAxisSettings;
import org.thingsboard.client.model.TimeSeriesChartYAxisSettings;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import org.thingsboard.client.JSON;
import org.thingsboard.client.ApiClient;
/**
 * ReportTimeSeriesChartSettings
 */
@JsonPropertyOrder({
  ReportTimeSeriesChartSettings.JSON_PROPERTY_SHOW_TITLE,
  ReportTimeSeriesChartSettings.JSON_PROPERTY_TITLE,
  ReportTimeSeriesChartSettings.JSON_PROPERTY_TITLE_FONT,
  ReportTimeSeriesChartSettings.JSON_PROPERTY_TITLE_COLOR,
  ReportTimeSeriesChartSettings.JSON_PROPERTY_TITLE_ALIGNMENT,
  ReportTimeSeriesChartSettings.JSON_PROPERTY_STACK,
  ReportTimeSeriesChartSettings.JSON_PROPERTY_COMPARISON_ENABLED,
  ReportTimeSeriesChartSettings.JSON_PROPERTY_TIME_FOR_COMPARISON,
  ReportTimeSeriesChartSettings.JSON_PROPERTY_COMPARISON_CUSTOM_INTERVAL_VALUE,
  ReportTimeSeriesChartSettings.JSON_PROPERTY_SHOW_LEGEND,
  ReportTimeSeriesChartSettings.JSON_PROPERTY_LEGEND_COLUMN_TITLE_FONT,
  ReportTimeSeriesChartSettings.JSON_PROPERTY_LEGEND_COLUMN_TITLE_COLOR,
  ReportTimeSeriesChartSettings.JSON_PROPERTY_LEGEND_LABEL_FONT,
  ReportTimeSeriesChartSettings.JSON_PROPERTY_LEGEND_LABEL_COLOR,
  ReportTimeSeriesChartSettings.JSON_PROPERTY_LEGEND_VALUE_FONT,
  ReportTimeSeriesChartSettings.JSON_PROPERTY_LEGEND_VALUE_COLOR,
  ReportTimeSeriesChartSettings.JSON_PROPERTY_THRESHOLDS,
  ReportTimeSeriesChartSettings.JSON_PROPERTY_GRID,
  ReportTimeSeriesChartSettings.JSON_PROPERTY_Y_AXES,
  ReportTimeSeriesChartSettings.JSON_PROPERTY_X_AXIS,
  ReportTimeSeriesChartSettings.JSON_PROPERTY_BAR_WIDTH_SETTINGS,
  ReportTimeSeriesChartSettings.JSON_PROPERTY_NO_AGGREGATION_BAR_WIDTH_SETTINGS,
  ReportTimeSeriesChartSettings.JSON_PROPERTY_STATES,
  ReportTimeSeriesChartSettings.JSON_PROPERTY_COMPARISON_X_AXIS,
  ReportTimeSeriesChartSettings.JSON_PROPERTY_LEGEND_CONFIG
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.20.0")
@JsonIgnoreProperties(
  value = "subType", // ignore manually set subType, it will be automatically generated by Jackson during serialization
  allowSetters = true // allows the subType to be set during deserialization
)
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "subType", visible = true)
@JsonSubTypes({
  @JsonSubTypes.Type(value = ReportBarChartWithLabelsSettings.class, name = "barChartWithLabels"),
  @JsonSubTypes.Type(value = ReportRangeChartSettings.class, name = "rangeChart"),
})

public class ReportTimeSeriesChartSettings {
  public static final String JSON_PROPERTY_SHOW_TITLE = "showTitle";
  @javax.annotation.Nullable
  private Boolean showTitle;

  public static final String JSON_PROPERTY_TITLE = "title";
  @javax.annotation.Nullable
  private String title;

  public static final String JSON_PROPERTY_TITLE_FONT = "titleFont";
  @javax.annotation.Nullable
  private Font titleFont;

  public static final String JSON_PROPERTY_TITLE_COLOR = "titleColor";
  @javax.annotation.Nullable
  private String titleColor;

  public static final String JSON_PROPERTY_TITLE_ALIGNMENT = "titleAlignment";
  @javax.annotation.Nullable
  private TextAlignment titleAlignment;

  public static final String JSON_PROPERTY_STACK = "stack";
  @javax.annotation.Nullable
  private Boolean stack;

  public static final String JSON_PROPERTY_COMPARISON_ENABLED = "comparisonEnabled";
  @javax.annotation.Nullable
  private Boolean comparisonEnabled;

  public static final String JSON_PROPERTY_TIME_FOR_COMPARISON = "timeForComparison";
  @javax.annotation.Nullable
  private ComparisonDuration timeForComparison;

  public static final String JSON_PROPERTY_COMPARISON_CUSTOM_INTERVAL_VALUE = "comparisonCustomIntervalValue";
  @javax.annotation.Nullable
  private Long comparisonCustomIntervalValue;

  public static final String JSON_PROPERTY_SHOW_LEGEND = "showLegend";
  @javax.annotation.Nullable
  private Boolean showLegend;

  public static final String JSON_PROPERTY_LEGEND_COLUMN_TITLE_FONT = "legendColumnTitleFont";
  @javax.annotation.Nullable
  private Font legendColumnTitleFont;

  public static final String JSON_PROPERTY_LEGEND_COLUMN_TITLE_COLOR = "legendColumnTitleColor";
  @javax.annotation.Nullable
  private String legendColumnTitleColor;

  public static final String JSON_PROPERTY_LEGEND_LABEL_FONT = "legendLabelFont";
  @javax.annotation.Nullable
  private Font legendLabelFont;

  public static final String JSON_PROPERTY_LEGEND_LABEL_COLOR = "legendLabelColor";
  @javax.annotation.Nullable
  private String legendLabelColor;

  public static final String JSON_PROPERTY_LEGEND_VALUE_FONT = "legendValueFont";
  @javax.annotation.Nullable
  private Font legendValueFont;

  public static final String JSON_PROPERTY_LEGEND_VALUE_COLOR = "legendValueColor";
  @javax.annotation.Nullable
  private String legendValueColor;

  public static final String JSON_PROPERTY_THRESHOLDS = "thresholds";
  @javax.annotation.Nullable
  private List<TimeSeriesChartThreshold> thresholds = new ArrayList<>();

  public static final String JSON_PROPERTY_GRID = "grid";
  @javax.annotation.Nullable
  private TimeSeriesChartGridSettings grid;

  public static final String JSON_PROPERTY_Y_AXES = "yAxes";
  @javax.annotation.Nullable
  private Map<String, TimeSeriesChartYAxisSettings> yAxes = new HashMap<>();

  public static final String JSON_PROPERTY_X_AXIS = "xAxis";
  @javax.annotation.Nullable
  private TimeSeriesChartXAxisSettings xAxis;

  public static final String JSON_PROPERTY_BAR_WIDTH_SETTINGS = "barWidthSettings";
  @javax.annotation.Nullable
  private TimeSeriesChartBarWidthSettings barWidthSettings;

  public static final String JSON_PROPERTY_NO_AGGREGATION_BAR_WIDTH_SETTINGS = "noAggregationBarWidthSettings";
  @javax.annotation.Nullable
  private TimeSeriesChartNoAggregationBarWidthSettings noAggregationBarWidthSettings;

  public static final String JSON_PROPERTY_STATES = "states";
  @javax.annotation.Nullable
  private List<TimeSeriesChartStateSettings> states = new ArrayList<>();

  public static final String JSON_PROPERTY_COMPARISON_X_AXIS = "comparisonXAxis";
  @javax.annotation.Nullable
  private TimeSeriesChartXAxisSettings comparisonXAxis;

  public static final String JSON_PROPERTY_LEGEND_CONFIG = "legendConfig";
  @javax.annotation.Nullable
  private LegendConfig legendConfig;

  public ReportTimeSeriesChartSettings() { 
  }

  public ReportTimeSeriesChartSettings showTitle(@javax.annotation.Nullable Boolean showTitle) {
    this.showTitle = showTitle;
    return this;
  }

  /**
   * Get showTitle
   * @return showTitle
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_SHOW_TITLE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Boolean getShowTitle() {
    return showTitle;
  }


  @JsonProperty(value = JSON_PROPERTY_SHOW_TITLE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setShowTitle(@javax.annotation.Nullable Boolean showTitle) {
    this.showTitle = showTitle;
  }


  public ReportTimeSeriesChartSettings title(@javax.annotation.Nullable String title) {
    this.title = title;
    return this;
  }

  /**
   * Get title
   * @return title
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TITLE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getTitle() {
    return title;
  }


  @JsonProperty(value = JSON_PROPERTY_TITLE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTitle(@javax.annotation.Nullable String title) {
    this.title = title;
  }


  public ReportTimeSeriesChartSettings titleFont(@javax.annotation.Nullable Font titleFont) {
    this.titleFont = titleFont;
    return this;
  }

  /**
   * Get titleFont
   * @return titleFont
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TITLE_FONT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Font getTitleFont() {
    return titleFont;
  }


  @JsonProperty(value = JSON_PROPERTY_TITLE_FONT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTitleFont(@javax.annotation.Nullable Font titleFont) {
    this.titleFont = titleFont;
  }


  public ReportTimeSeriesChartSettings titleColor(@javax.annotation.Nullable String titleColor) {
    this.titleColor = titleColor;
    return this;
  }

  /**
   * Get titleColor
   * @return titleColor
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TITLE_COLOR, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getTitleColor() {
    return titleColor;
  }


  @JsonProperty(value = JSON_PROPERTY_TITLE_COLOR, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTitleColor(@javax.annotation.Nullable String titleColor) {
    this.titleColor = titleColor;
  }


  public ReportTimeSeriesChartSettings titleAlignment(@javax.annotation.Nullable TextAlignment titleAlignment) {
    this.titleAlignment = titleAlignment;
    return this;
  }

  /**
   * Get titleAlignment
   * @return titleAlignment
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TITLE_ALIGNMENT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public TextAlignment getTitleAlignment() {
    return titleAlignment;
  }


  @JsonProperty(value = JSON_PROPERTY_TITLE_ALIGNMENT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTitleAlignment(@javax.annotation.Nullable TextAlignment titleAlignment) {
    this.titleAlignment = titleAlignment;
  }


  public ReportTimeSeriesChartSettings stack(@javax.annotation.Nullable Boolean stack) {
    this.stack = stack;
    return this;
  }

  /**
   * Get stack
   * @return stack
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_STACK, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Boolean getStack() {
    return stack;
  }


  @JsonProperty(value = JSON_PROPERTY_STACK, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStack(@javax.annotation.Nullable Boolean stack) {
    this.stack = stack;
  }


  public ReportTimeSeriesChartSettings comparisonEnabled(@javax.annotation.Nullable Boolean comparisonEnabled) {
    this.comparisonEnabled = comparisonEnabled;
    return this;
  }

  /**
   * Get comparisonEnabled
   * @return comparisonEnabled
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_COMPARISON_ENABLED, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Boolean getComparisonEnabled() {
    return comparisonEnabled;
  }


  @JsonProperty(value = JSON_PROPERTY_COMPARISON_ENABLED, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setComparisonEnabled(@javax.annotation.Nullable Boolean comparisonEnabled) {
    this.comparisonEnabled = comparisonEnabled;
  }


  public ReportTimeSeriesChartSettings timeForComparison(@javax.annotation.Nullable ComparisonDuration timeForComparison) {
    this.timeForComparison = timeForComparison;
    return this;
  }

  /**
   * Get timeForComparison
   * @return timeForComparison
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TIME_FOR_COMPARISON, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public ComparisonDuration getTimeForComparison() {
    return timeForComparison;
  }


  @JsonProperty(value = JSON_PROPERTY_TIME_FOR_COMPARISON, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTimeForComparison(@javax.annotation.Nullable ComparisonDuration timeForComparison) {
    this.timeForComparison = timeForComparison;
  }


  public ReportTimeSeriesChartSettings comparisonCustomIntervalValue(@javax.annotation.Nullable Long comparisonCustomIntervalValue) {
    this.comparisonCustomIntervalValue = comparisonCustomIntervalValue;
    return this;
  }

  /**
   * Get comparisonCustomIntervalValue
   * @return comparisonCustomIntervalValue
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_COMPARISON_CUSTOM_INTERVAL_VALUE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Long getComparisonCustomIntervalValue() {
    return comparisonCustomIntervalValue;
  }


  @JsonProperty(value = JSON_PROPERTY_COMPARISON_CUSTOM_INTERVAL_VALUE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setComparisonCustomIntervalValue(@javax.annotation.Nullable Long comparisonCustomIntervalValue) {
    this.comparisonCustomIntervalValue = comparisonCustomIntervalValue;
  }


  public ReportTimeSeriesChartSettings showLegend(@javax.annotation.Nullable Boolean showLegend) {
    this.showLegend = showLegend;
    return this;
  }

  /**
   * Get showLegend
   * @return showLegend
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_SHOW_LEGEND, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Boolean getShowLegend() {
    return showLegend;
  }


  @JsonProperty(value = JSON_PROPERTY_SHOW_LEGEND, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setShowLegend(@javax.annotation.Nullable Boolean showLegend) {
    this.showLegend = showLegend;
  }


  public ReportTimeSeriesChartSettings legendColumnTitleFont(@javax.annotation.Nullable Font legendColumnTitleFont) {
    this.legendColumnTitleFont = legendColumnTitleFont;
    return this;
  }

  /**
   * Get legendColumnTitleFont
   * @return legendColumnTitleFont
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_LEGEND_COLUMN_TITLE_FONT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Font getLegendColumnTitleFont() {
    return legendColumnTitleFont;
  }


  @JsonProperty(value = JSON_PROPERTY_LEGEND_COLUMN_TITLE_FONT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLegendColumnTitleFont(@javax.annotation.Nullable Font legendColumnTitleFont) {
    this.legendColumnTitleFont = legendColumnTitleFont;
  }


  public ReportTimeSeriesChartSettings legendColumnTitleColor(@javax.annotation.Nullable String legendColumnTitleColor) {
    this.legendColumnTitleColor = legendColumnTitleColor;
    return this;
  }

  /**
   * Get legendColumnTitleColor
   * @return legendColumnTitleColor
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_LEGEND_COLUMN_TITLE_COLOR, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getLegendColumnTitleColor() {
    return legendColumnTitleColor;
  }


  @JsonProperty(value = JSON_PROPERTY_LEGEND_COLUMN_TITLE_COLOR, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLegendColumnTitleColor(@javax.annotation.Nullable String legendColumnTitleColor) {
    this.legendColumnTitleColor = legendColumnTitleColor;
  }


  public ReportTimeSeriesChartSettings legendLabelFont(@javax.annotation.Nullable Font legendLabelFont) {
    this.legendLabelFont = legendLabelFont;
    return this;
  }

  /**
   * Get legendLabelFont
   * @return legendLabelFont
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_LEGEND_LABEL_FONT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Font getLegendLabelFont() {
    return legendLabelFont;
  }


  @JsonProperty(value = JSON_PROPERTY_LEGEND_LABEL_FONT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLegendLabelFont(@javax.annotation.Nullable Font legendLabelFont) {
    this.legendLabelFont = legendLabelFont;
  }


  public ReportTimeSeriesChartSettings legendLabelColor(@javax.annotation.Nullable String legendLabelColor) {
    this.legendLabelColor = legendLabelColor;
    return this;
  }

  /**
   * Get legendLabelColor
   * @return legendLabelColor
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_LEGEND_LABEL_COLOR, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getLegendLabelColor() {
    return legendLabelColor;
  }


  @JsonProperty(value = JSON_PROPERTY_LEGEND_LABEL_COLOR, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLegendLabelColor(@javax.annotation.Nullable String legendLabelColor) {
    this.legendLabelColor = legendLabelColor;
  }


  public ReportTimeSeriesChartSettings legendValueFont(@javax.annotation.Nullable Font legendValueFont) {
    this.legendValueFont = legendValueFont;
    return this;
  }

  /**
   * Get legendValueFont
   * @return legendValueFont
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_LEGEND_VALUE_FONT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Font getLegendValueFont() {
    return legendValueFont;
  }


  @JsonProperty(value = JSON_PROPERTY_LEGEND_VALUE_FONT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLegendValueFont(@javax.annotation.Nullable Font legendValueFont) {
    this.legendValueFont = legendValueFont;
  }


  public ReportTimeSeriesChartSettings legendValueColor(@javax.annotation.Nullable String legendValueColor) {
    this.legendValueColor = legendValueColor;
    return this;
  }

  /**
   * Get legendValueColor
   * @return legendValueColor
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_LEGEND_VALUE_COLOR, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getLegendValueColor() {
    return legendValueColor;
  }


  @JsonProperty(value = JSON_PROPERTY_LEGEND_VALUE_COLOR, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLegendValueColor(@javax.annotation.Nullable String legendValueColor) {
    this.legendValueColor = legendValueColor;
  }


  public ReportTimeSeriesChartSettings thresholds(@javax.annotation.Nullable List<TimeSeriesChartThreshold> thresholds) {
    this.thresholds = thresholds;
    return this;
  }

  public ReportTimeSeriesChartSettings addThresholdsItem(TimeSeriesChartThreshold thresholdsItem) {
    if (this.thresholds == null) {
      this.thresholds = new ArrayList<>();
    }
    this.thresholds.add(thresholdsItem);
    return this;
  }

  /**
   * Get thresholds
   * @return thresholds
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_THRESHOLDS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public List<TimeSeriesChartThreshold> getThresholds() {
    return thresholds;
  }


  @JsonProperty(value = JSON_PROPERTY_THRESHOLDS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setThresholds(@javax.annotation.Nullable List<TimeSeriesChartThreshold> thresholds) {
    this.thresholds = thresholds;
  }


  public ReportTimeSeriesChartSettings grid(@javax.annotation.Nullable TimeSeriesChartGridSettings grid) {
    this.grid = grid;
    return this;
  }

  /**
   * Get grid
   * @return grid
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_GRID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public TimeSeriesChartGridSettings getGrid() {
    return grid;
  }


  @JsonProperty(value = JSON_PROPERTY_GRID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setGrid(@javax.annotation.Nullable TimeSeriesChartGridSettings grid) {
    this.grid = grid;
  }


  public ReportTimeSeriesChartSettings yAxes(@javax.annotation.Nullable Map<String, TimeSeriesChartYAxisSettings> yAxes) {
    this.yAxes = yAxes;
    return this;
  }

  public ReportTimeSeriesChartSettings putYAxesItem(String key, TimeSeriesChartYAxisSettings yAxesItem) {
    if (this.yAxes == null) {
      this.yAxes = new HashMap<>();
    }
    this.yAxes.put(key, yAxesItem);
    return this;
  }

  /**
   * Get yAxes
   * @return yAxes
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_Y_AXES, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Map<String, TimeSeriesChartYAxisSettings> getyAxes() {
    return yAxes;
  }


  @JsonProperty(value = JSON_PROPERTY_Y_AXES, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setyAxes(@javax.annotation.Nullable Map<String, TimeSeriesChartYAxisSettings> yAxes) {
    this.yAxes = yAxes;
  }


  public ReportTimeSeriesChartSettings xAxis(@javax.annotation.Nullable TimeSeriesChartXAxisSettings xAxis) {
    this.xAxis = xAxis;
    return this;
  }

  /**
   * Get xAxis
   * @return xAxis
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_X_AXIS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public TimeSeriesChartXAxisSettings getxAxis() {
    return xAxis;
  }


  @JsonProperty(value = JSON_PROPERTY_X_AXIS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setxAxis(@javax.annotation.Nullable TimeSeriesChartXAxisSettings xAxis) {
    this.xAxis = xAxis;
  }


  public ReportTimeSeriesChartSettings barWidthSettings(@javax.annotation.Nullable TimeSeriesChartBarWidthSettings barWidthSettings) {
    this.barWidthSettings = barWidthSettings;
    return this;
  }

  /**
   * Get barWidthSettings
   * @return barWidthSettings
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_BAR_WIDTH_SETTINGS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public TimeSeriesChartBarWidthSettings getBarWidthSettings() {
    return barWidthSettings;
  }


  @JsonProperty(value = JSON_PROPERTY_BAR_WIDTH_SETTINGS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setBarWidthSettings(@javax.annotation.Nullable TimeSeriesChartBarWidthSettings barWidthSettings) {
    this.barWidthSettings = barWidthSettings;
  }


  public ReportTimeSeriesChartSettings noAggregationBarWidthSettings(@javax.annotation.Nullable TimeSeriesChartNoAggregationBarWidthSettings noAggregationBarWidthSettings) {
    this.noAggregationBarWidthSettings = noAggregationBarWidthSettings;
    return this;
  }

  /**
   * Get noAggregationBarWidthSettings
   * @return noAggregationBarWidthSettings
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_NO_AGGREGATION_BAR_WIDTH_SETTINGS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public TimeSeriesChartNoAggregationBarWidthSettings getNoAggregationBarWidthSettings() {
    return noAggregationBarWidthSettings;
  }


  @JsonProperty(value = JSON_PROPERTY_NO_AGGREGATION_BAR_WIDTH_SETTINGS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setNoAggregationBarWidthSettings(@javax.annotation.Nullable TimeSeriesChartNoAggregationBarWidthSettings noAggregationBarWidthSettings) {
    this.noAggregationBarWidthSettings = noAggregationBarWidthSettings;
  }


  public ReportTimeSeriesChartSettings states(@javax.annotation.Nullable List<TimeSeriesChartStateSettings> states) {
    this.states = states;
    return this;
  }

  public ReportTimeSeriesChartSettings addStatesItem(TimeSeriesChartStateSettings statesItem) {
    if (this.states == null) {
      this.states = new ArrayList<>();
    }
    this.states.add(statesItem);
    return this;
  }

  /**
   * Get states
   * @return states
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_STATES, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public List<TimeSeriesChartStateSettings> getStates() {
    return states;
  }


  @JsonProperty(value = JSON_PROPERTY_STATES, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStates(@javax.annotation.Nullable List<TimeSeriesChartStateSettings> states) {
    this.states = states;
  }


  public ReportTimeSeriesChartSettings comparisonXAxis(@javax.annotation.Nullable TimeSeriesChartXAxisSettings comparisonXAxis) {
    this.comparisonXAxis = comparisonXAxis;
    return this;
  }

  /**
   * Get comparisonXAxis
   * @return comparisonXAxis
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_COMPARISON_X_AXIS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public TimeSeriesChartXAxisSettings getComparisonXAxis() {
    return comparisonXAxis;
  }


  @JsonProperty(value = JSON_PROPERTY_COMPARISON_X_AXIS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setComparisonXAxis(@javax.annotation.Nullable TimeSeriesChartXAxisSettings comparisonXAxis) {
    this.comparisonXAxis = comparisonXAxis;
  }


  public ReportTimeSeriesChartSettings legendConfig(@javax.annotation.Nullable LegendConfig legendConfig) {
    this.legendConfig = legendConfig;
    return this;
  }

  /**
   * Get legendConfig
   * @return legendConfig
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_LEGEND_CONFIG, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public LegendConfig getLegendConfig() {
    return legendConfig;
  }


  @JsonProperty(value = JSON_PROPERTY_LEGEND_CONFIG, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLegendConfig(@javax.annotation.Nullable LegendConfig legendConfig) {
    this.legendConfig = legendConfig;
  }


  /**
   * Return true if this ReportTimeSeriesChartSettings object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ReportTimeSeriesChartSettings reportTimeSeriesChartSettings = (ReportTimeSeriesChartSettings) o;
    return Objects.equals(this.showTitle, reportTimeSeriesChartSettings.showTitle) &&
        Objects.equals(this.title, reportTimeSeriesChartSettings.title) &&
        Objects.equals(this.titleFont, reportTimeSeriesChartSettings.titleFont) &&
        Objects.equals(this.titleColor, reportTimeSeriesChartSettings.titleColor) &&
        Objects.equals(this.titleAlignment, reportTimeSeriesChartSettings.titleAlignment) &&
        Objects.equals(this.stack, reportTimeSeriesChartSettings.stack) &&
        Objects.equals(this.comparisonEnabled, reportTimeSeriesChartSettings.comparisonEnabled) &&
        Objects.equals(this.timeForComparison, reportTimeSeriesChartSettings.timeForComparison) &&
        Objects.equals(this.comparisonCustomIntervalValue, reportTimeSeriesChartSettings.comparisonCustomIntervalValue) &&
        Objects.equals(this.showLegend, reportTimeSeriesChartSettings.showLegend) &&
        Objects.equals(this.legendColumnTitleFont, reportTimeSeriesChartSettings.legendColumnTitleFont) &&
        Objects.equals(this.legendColumnTitleColor, reportTimeSeriesChartSettings.legendColumnTitleColor) &&
        Objects.equals(this.legendLabelFont, reportTimeSeriesChartSettings.legendLabelFont) &&
        Objects.equals(this.legendLabelColor, reportTimeSeriesChartSettings.legendLabelColor) &&
        Objects.equals(this.legendValueFont, reportTimeSeriesChartSettings.legendValueFont) &&
        Objects.equals(this.legendValueColor, reportTimeSeriesChartSettings.legendValueColor) &&
        Objects.equals(this.thresholds, reportTimeSeriesChartSettings.thresholds) &&
        Objects.equals(this.grid, reportTimeSeriesChartSettings.grid) &&
        Objects.equals(this.yAxes, reportTimeSeriesChartSettings.yAxes) &&
        Objects.equals(this.xAxis, reportTimeSeriesChartSettings.xAxis) &&
        Objects.equals(this.barWidthSettings, reportTimeSeriesChartSettings.barWidthSettings) &&
        Objects.equals(this.noAggregationBarWidthSettings, reportTimeSeriesChartSettings.noAggregationBarWidthSettings) &&
        Objects.equals(this.states, reportTimeSeriesChartSettings.states) &&
        Objects.equals(this.comparisonXAxis, reportTimeSeriesChartSettings.comparisonXAxis) &&
        Objects.equals(this.legendConfig, reportTimeSeriesChartSettings.legendConfig);
  }

  @Override
  public int hashCode() {
    return Objects.hash(showTitle, title, titleFont, titleColor, titleAlignment, stack, comparisonEnabled, timeForComparison, comparisonCustomIntervalValue, showLegend, legendColumnTitleFont, legendColumnTitleColor, legendLabelFont, legendLabelColor, legendValueFont, legendValueColor, thresholds, grid, yAxes, xAxis, barWidthSettings, noAggregationBarWidthSettings, states, comparisonXAxis, legendConfig);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ReportTimeSeriesChartSettings {\n");
    sb.append("    showTitle: ").append(toIndentedString(showTitle)).append("\n");
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("    titleFont: ").append(toIndentedString(titleFont)).append("\n");
    sb.append("    titleColor: ").append(toIndentedString(titleColor)).append("\n");
    sb.append("    titleAlignment: ").append(toIndentedString(titleAlignment)).append("\n");
    sb.append("    stack: ").append(toIndentedString(stack)).append("\n");
    sb.append("    comparisonEnabled: ").append(toIndentedString(comparisonEnabled)).append("\n");
    sb.append("    timeForComparison: ").append(toIndentedString(timeForComparison)).append("\n");
    sb.append("    comparisonCustomIntervalValue: ").append(toIndentedString(comparisonCustomIntervalValue)).append("\n");
    sb.append("    showLegend: ").append(toIndentedString(showLegend)).append("\n");
    sb.append("    legendColumnTitleFont: ").append(toIndentedString(legendColumnTitleFont)).append("\n");
    sb.append("    legendColumnTitleColor: ").append(toIndentedString(legendColumnTitleColor)).append("\n");
    sb.append("    legendLabelFont: ").append(toIndentedString(legendLabelFont)).append("\n");
    sb.append("    legendLabelColor: ").append(toIndentedString(legendLabelColor)).append("\n");
    sb.append("    legendValueFont: ").append(toIndentedString(legendValueFont)).append("\n");
    sb.append("    legendValueColor: ").append(toIndentedString(legendValueColor)).append("\n");
    sb.append("    thresholds: ").append(toIndentedString(thresholds)).append("\n");
    sb.append("    grid: ").append(toIndentedString(grid)).append("\n");
    sb.append("    yAxes: ").append(toIndentedString(yAxes)).append("\n");
    sb.append("    xAxis: ").append(toIndentedString(xAxis)).append("\n");
    sb.append("    barWidthSettings: ").append(toIndentedString(barWidthSettings)).append("\n");
    sb.append("    noAggregationBarWidthSettings: ").append(toIndentedString(noAggregationBarWidthSettings)).append("\n");
    sb.append("    states: ").append(toIndentedString(states)).append("\n");
    sb.append("    comparisonXAxis: ").append(toIndentedString(comparisonXAxis)).append("\n");
    sb.append("    legendConfig: ").append(toIndentedString(legendConfig)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `showTitle` to the URL query string
    if (getShowTitle() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sshowTitle%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getShowTitle()))));
    }

    // add `title` to the URL query string
    if (getTitle() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%stitle%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getTitle()))));
    }

    // add `titleFont` to the URL query string
    if (getTitleFont() != null) {
      joiner.add(getTitleFont().toUrlQueryString(prefix + "titleFont" + suffix));
    }

    // add `titleColor` to the URL query string
    if (getTitleColor() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%stitleColor%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getTitleColor()))));
    }

    // add `titleAlignment` to the URL query string
    if (getTitleAlignment() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%stitleAlignment%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getTitleAlignment()))));
    }

    // add `stack` to the URL query string
    if (getStack() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sstack%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getStack()))));
    }

    // add `comparisonEnabled` to the URL query string
    if (getComparisonEnabled() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%scomparisonEnabled%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getComparisonEnabled()))));
    }

    // add `timeForComparison` to the URL query string
    if (getTimeForComparison() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%stimeForComparison%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getTimeForComparison()))));
    }

    // add `comparisonCustomIntervalValue` to the URL query string
    if (getComparisonCustomIntervalValue() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%scomparisonCustomIntervalValue%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getComparisonCustomIntervalValue()))));
    }

    // add `showLegend` to the URL query string
    if (getShowLegend() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sshowLegend%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getShowLegend()))));
    }

    // add `legendColumnTitleFont` to the URL query string
    if (getLegendColumnTitleFont() != null) {
      joiner.add(getLegendColumnTitleFont().toUrlQueryString(prefix + "legendColumnTitleFont" + suffix));
    }

    // add `legendColumnTitleColor` to the URL query string
    if (getLegendColumnTitleColor() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%slegendColumnTitleColor%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getLegendColumnTitleColor()))));
    }

    // add `legendLabelFont` to the URL query string
    if (getLegendLabelFont() != null) {
      joiner.add(getLegendLabelFont().toUrlQueryString(prefix + "legendLabelFont" + suffix));
    }

    // add `legendLabelColor` to the URL query string
    if (getLegendLabelColor() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%slegendLabelColor%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getLegendLabelColor()))));
    }

    // add `legendValueFont` to the URL query string
    if (getLegendValueFont() != null) {
      joiner.add(getLegendValueFont().toUrlQueryString(prefix + "legendValueFont" + suffix));
    }

    // add `legendValueColor` to the URL query string
    if (getLegendValueColor() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%slegendValueColor%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getLegendValueColor()))));
    }

    // add `thresholds` to the URL query string
    if (getThresholds() != null) {
      for (int i = 0; i < getThresholds().size(); i++) {
        if (getThresholds().get(i) != null) {
          joiner.add(getThresholds().get(i).toUrlQueryString(String.format(java.util.Locale.ROOT, "%sthresholds%s%s", prefix, suffix,
          "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix))));
        }
      }
    }

    // add `grid` to the URL query string
    if (getGrid() != null) {
      joiner.add(getGrid().toUrlQueryString(prefix + "grid" + suffix));
    }

    // add `yAxes` to the URL query string
    if (getyAxes() != null) {
      for (String _key : getyAxes().keySet()) {
        if (getyAxes().get(_key) != null) {
          joiner.add(getyAxes().get(_key).toUrlQueryString(String.format(java.util.Locale.ROOT, "%syAxes%s%s", prefix, suffix,
              "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, _key, containerSuffix))));
        }
      }
    }

    // add `xAxis` to the URL query string
    if (getxAxis() != null) {
      joiner.add(getxAxis().toUrlQueryString(prefix + "xAxis" + suffix));
    }

    // add `barWidthSettings` to the URL query string
    if (getBarWidthSettings() != null) {
      joiner.add(getBarWidthSettings().toUrlQueryString(prefix + "barWidthSettings" + suffix));
    }

    // add `noAggregationBarWidthSettings` to the URL query string
    if (getNoAggregationBarWidthSettings() != null) {
      joiner.add(getNoAggregationBarWidthSettings().toUrlQueryString(prefix + "noAggregationBarWidthSettings" + suffix));
    }

    // add `states` to the URL query string
    if (getStates() != null) {
      for (int i = 0; i < getStates().size(); i++) {
        if (getStates().get(i) != null) {
          joiner.add(getStates().get(i).toUrlQueryString(String.format(java.util.Locale.ROOT, "%sstates%s%s", prefix, suffix,
          "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix))));
        }
      }
    }

    // add `comparisonXAxis` to the URL query string
    if (getComparisonXAxis() != null) {
      joiner.add(getComparisonXAxis().toUrlQueryString(prefix + "comparisonXAxis" + suffix));
    }

    // add `legendConfig` to the URL query string
    if (getLegendConfig() != null) {
      joiner.add(getLegendConfig().toUrlQueryString(prefix + "legendConfig" + suffix));
    }

    return joiner.toString();
  }
static {
  // Initialize and register the discriminator mappings.
  Map<String, Class<?>> mappings = new HashMap<String, Class<?>>();
  mappings.put("barChartWithLabels", ReportBarChartWithLabelsSettings.class);
  mappings.put("rangeChart", ReportRangeChartSettings.class);
  mappings.put("ReportTimeSeriesChartSettings", ReportTimeSeriesChartSettings.class);
  JSON.registerDiscriminator(ReportTimeSeriesChartSettings.class, "subType", mappings);
}
}

