/**
 * Copyright © 2026-2026 ThingsBoard, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.thingsboard.client.model;

import javax.annotation.Generated;
import javax.annotation.Nullable;
import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import org.thingsboard.client.model.EventFilter;
import org.thingsboard.client.model.EventType;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import org.thingsboard.client.JSON;
import org.thingsboard.client.ApiClient;
/**
 * RuleNodeDebugEventFilter
 */
@JsonPropertyOrder({
  RuleNodeDebugEventFilter.JSON_PROPERTY_SERVER,
  RuleNodeDebugEventFilter.JSON_PROPERTY_IS_ERROR,
  RuleNodeDebugEventFilter.JSON_PROPERTY_ERROR_STR,
  RuleNodeDebugEventFilter.JSON_PROPERTY_MSG_DIRECTION_TYPE,
  RuleNodeDebugEventFilter.JSON_PROPERTY_ENTITY_ID,
  RuleNodeDebugEventFilter.JSON_PROPERTY_ENTITY_TYPE,
  RuleNodeDebugEventFilter.JSON_PROPERTY_MSG_ID,
  RuleNodeDebugEventFilter.JSON_PROPERTY_MSG_TYPE,
  RuleNodeDebugEventFilter.JSON_PROPERTY_RELATION_TYPE,
  RuleNodeDebugEventFilter.JSON_PROPERTY_DATA_SEARCH,
  RuleNodeDebugEventFilter.JSON_PROPERTY_METADATA_SEARCH
})
@Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.20.0")
@JsonIgnoreProperties(
  value = "eventType", // ignore manually set eventType, it will be automatically generated by Jackson during serialization
  allowSetters = true // allows the eventType to be set during deserialization
)
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "eventType", visible = true)

public class RuleNodeDebugEventFilter extends EventFilter {
  public static final String JSON_PROPERTY_SERVER = "server";
  @Nullable
  private String server;

  /**
   * Boolean value to filter the errors
   */
  public enum IsErrorEnum {
    FALSE(Boolean.valueOf("false")),
    
    TRUE(Boolean.valueOf("true"));

    private Boolean value;

    IsErrorEnum(Boolean value) {
      this.value = value;
    }

    @JsonValue
    public Boolean getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static IsErrorEnum fromValue(Boolean value) {
      for (IsErrorEnum b : IsErrorEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_IS_ERROR = "isError";
  @Nullable
  private IsErrorEnum isError;

  public static final String JSON_PROPERTY_ERROR_STR = "errorStr";
  @Nullable
  private String errorStr;

  /**
   * String value representing msg direction type (incoming to entity or outcoming from entity)
   */
  public enum MsgDirectionTypeEnum {
    IN(String.valueOf("IN")),
    
    OUT(String.valueOf("OUT"));

    private String value;

    MsgDirectionTypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static MsgDirectionTypeEnum fromValue(String value) {
      for (MsgDirectionTypeEnum b : MsgDirectionTypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_MSG_DIRECTION_TYPE = "msgDirectionType";
  @Nullable
  private MsgDirectionTypeEnum msgDirectionType;

  public static final String JSON_PROPERTY_ENTITY_ID = "entityId";
  @Nullable
  private String entityId;

  /**
   * String value representing the entity type
   */
  public enum EntityTypeEnum {
    DEVICE(String.valueOf("DEVICE"));

    private String value;

    EntityTypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static EntityTypeEnum fromValue(String value) {
      for (EntityTypeEnum b : EntityTypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_ENTITY_TYPE = "entityType";
  @Nullable
  private EntityTypeEnum entityType;

  public static final String JSON_PROPERTY_MSG_ID = "msgId";
  @Nullable
  private String msgId;

  public static final String JSON_PROPERTY_MSG_TYPE = "msgType";
  @Nullable
  private String msgType;

  public static final String JSON_PROPERTY_RELATION_TYPE = "relationType";
  @Nullable
  private String relationType;

  public static final String JSON_PROPERTY_DATA_SEARCH = "dataSearch";
  @Nullable
  private String dataSearch;

  public static final String JSON_PROPERTY_METADATA_SEARCH = "metadataSearch";
  @Nullable
  private String metadataSearch;

  public RuleNodeDebugEventFilter() { 
  }

  public RuleNodeDebugEventFilter server(@Nullable String server) {
    this.server = server;
    return this;
  }

  /**
   * String value representing the server name, identifier or ip address where the platform is running
   * @return server
   */
  @Nullable
  @JsonProperty(value = JSON_PROPERTY_SERVER, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getServer() {
    return server;
  }


  @JsonProperty(value = JSON_PROPERTY_SERVER, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setServer(@Nullable String server) {
    this.server = server;
  }


  public RuleNodeDebugEventFilter isError(@Nullable IsErrorEnum isError) {
    this.isError = isError;
    return this;
  }

  /**
   * Boolean value to filter the errors
   * @return isError
   */
  @Nullable
  @JsonProperty(value = JSON_PROPERTY_IS_ERROR, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public IsErrorEnum getIsError() {
    return isError;
  }


  @JsonProperty(value = JSON_PROPERTY_IS_ERROR, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIsError(@Nullable IsErrorEnum isError) {
    this.isError = isError;
  }


  public RuleNodeDebugEventFilter errorStr(@Nullable String errorStr) {
    this.errorStr = errorStr;
    return this;
  }

  /**
   * The case insensitive &#39;contains&#39; filter based on error message
   * @return errorStr
   */
  @Nullable
  @JsonProperty(value = JSON_PROPERTY_ERROR_STR, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getErrorStr() {
    return errorStr;
  }


  @JsonProperty(value = JSON_PROPERTY_ERROR_STR, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setErrorStr(@Nullable String errorStr) {
    this.errorStr = errorStr;
  }


  public RuleNodeDebugEventFilter msgDirectionType(@Nullable MsgDirectionTypeEnum msgDirectionType) {
    this.msgDirectionType = msgDirectionType;
    return this;
  }

  /**
   * String value representing msg direction type (incoming to entity or outcoming from entity)
   * @return msgDirectionType
   */
  @Nullable
  @JsonProperty(value = JSON_PROPERTY_MSG_DIRECTION_TYPE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public MsgDirectionTypeEnum getMsgDirectionType() {
    return msgDirectionType;
  }


  @JsonProperty(value = JSON_PROPERTY_MSG_DIRECTION_TYPE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMsgDirectionType(@Nullable MsgDirectionTypeEnum msgDirectionType) {
    this.msgDirectionType = msgDirectionType;
  }


  public RuleNodeDebugEventFilter entityId(@Nullable String entityId) {
    this.entityId = entityId;
    return this;
  }

  /**
   * String value representing the entity id in the event body (originator of the message)
   * @return entityId
   */
  @Nullable
  @JsonProperty(value = JSON_PROPERTY_ENTITY_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getEntityId() {
    return entityId;
  }


  @JsonProperty(value = JSON_PROPERTY_ENTITY_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEntityId(@Nullable String entityId) {
    this.entityId = entityId;
  }


  public RuleNodeDebugEventFilter entityType(@Nullable EntityTypeEnum entityType) {
    this.entityType = entityType;
    return this;
  }

  /**
   * String value representing the entity type
   * @return entityType
   */
  @Nullable
  @JsonProperty(value = JSON_PROPERTY_ENTITY_TYPE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public EntityTypeEnum getEntityType() {
    return entityType;
  }


  @JsonProperty(value = JSON_PROPERTY_ENTITY_TYPE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEntityType(@Nullable EntityTypeEnum entityType) {
    this.entityType = entityType;
  }


  public RuleNodeDebugEventFilter msgId(@Nullable String msgId) {
    this.msgId = msgId;
    return this;
  }

  /**
   * String value representing the message id in the rule engine
   * @return msgId
   */
  @Nullable
  @JsonProperty(value = JSON_PROPERTY_MSG_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getMsgId() {
    return msgId;
  }


  @JsonProperty(value = JSON_PROPERTY_MSG_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMsgId(@Nullable String msgId) {
    this.msgId = msgId;
  }


  public RuleNodeDebugEventFilter msgType(@Nullable String msgType) {
    this.msgType = msgType;
    return this;
  }

  /**
   * String value representing the message type
   * @return msgType
   */
  @Nullable
  @JsonProperty(value = JSON_PROPERTY_MSG_TYPE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getMsgType() {
    return msgType;
  }


  @JsonProperty(value = JSON_PROPERTY_MSG_TYPE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMsgType(@Nullable String msgType) {
    this.msgType = msgType;
  }


  public RuleNodeDebugEventFilter relationType(@Nullable String relationType) {
    this.relationType = relationType;
    return this;
  }

  /**
   * String value representing the type of message routing
   * @return relationType
   */
  @Nullable
  @JsonProperty(value = JSON_PROPERTY_RELATION_TYPE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getRelationType() {
    return relationType;
  }


  @JsonProperty(value = JSON_PROPERTY_RELATION_TYPE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRelationType(@Nullable String relationType) {
    this.relationType = relationType;
  }


  public RuleNodeDebugEventFilter dataSearch(@Nullable String dataSearch) {
    this.dataSearch = dataSearch;
    return this;
  }

  /**
   * The case insensitive &#39;contains&#39; filter based on data (key and value) for the message.
   * @return dataSearch
   */
  @Nullable
  @JsonProperty(value = JSON_PROPERTY_DATA_SEARCH, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getDataSearch() {
    return dataSearch;
  }


  @JsonProperty(value = JSON_PROPERTY_DATA_SEARCH, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDataSearch(@Nullable String dataSearch) {
    this.dataSearch = dataSearch;
  }


  public RuleNodeDebugEventFilter metadataSearch(@Nullable String metadataSearch) {
    this.metadataSearch = metadataSearch;
    return this;
  }

  /**
   * The case insensitive &#39;contains&#39; filter based on metadata (key and value) for the message.
   * @return metadataSearch
   */
  @Nullable
  @JsonProperty(value = JSON_PROPERTY_METADATA_SEARCH, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getMetadataSearch() {
    return metadataSearch;
  }


  @JsonProperty(value = JSON_PROPERTY_METADATA_SEARCH, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMetadataSearch(@Nullable String metadataSearch) {
    this.metadataSearch = metadataSearch;
  }


  @Override
  public RuleNodeDebugEventFilter notEmpty(@Nullable Boolean notEmpty) {
    this.setNotEmpty(notEmpty);
    return this;
  }

  /**
   * Return true if this RuleNodeDebugEventFilter object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RuleNodeDebugEventFilter ruleNodeDebugEventFilter = (RuleNodeDebugEventFilter) o;
    return Objects.equals(this.server, ruleNodeDebugEventFilter.server) &&
        Objects.equals(this.isError, ruleNodeDebugEventFilter.isError) &&
        Objects.equals(this.errorStr, ruleNodeDebugEventFilter.errorStr) &&
        Objects.equals(this.msgDirectionType, ruleNodeDebugEventFilter.msgDirectionType) &&
        Objects.equals(this.entityId, ruleNodeDebugEventFilter.entityId) &&
        Objects.equals(this.entityType, ruleNodeDebugEventFilter.entityType) &&
        Objects.equals(this.msgId, ruleNodeDebugEventFilter.msgId) &&
        Objects.equals(this.msgType, ruleNodeDebugEventFilter.msgType) &&
        Objects.equals(this.relationType, ruleNodeDebugEventFilter.relationType) &&
        Objects.equals(this.dataSearch, ruleNodeDebugEventFilter.dataSearch) &&
        Objects.equals(this.metadataSearch, ruleNodeDebugEventFilter.metadataSearch) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(server, isError, errorStr, msgDirectionType, entityId, entityType, msgId, msgType, relationType, dataSearch, metadataSearch, super.hashCode());
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RuleNodeDebugEventFilter {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    server: ").append(toIndentedString(server)).append("\n");
    sb.append("    isError: ").append(toIndentedString(isError)).append("\n");
    sb.append("    errorStr: ").append(toIndentedString(errorStr)).append("\n");
    sb.append("    msgDirectionType: ").append(toIndentedString(msgDirectionType)).append("\n");
    sb.append("    entityId: ").append(toIndentedString(entityId)).append("\n");
    sb.append("    entityType: ").append(toIndentedString(entityType)).append("\n");
    sb.append("    msgId: ").append(toIndentedString(msgId)).append("\n");
    sb.append("    msgType: ").append(toIndentedString(msgType)).append("\n");
    sb.append("    relationType: ").append(toIndentedString(relationType)).append("\n");
    sb.append("    dataSearch: ").append(toIndentedString(dataSearch)).append("\n");
    sb.append("    metadataSearch: ").append(toIndentedString(metadataSearch)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `eventType` to the URL query string
    if (getEventType() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%seventType%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getEventType()))));
    }

    // add `notEmpty` to the URL query string
    if (getNotEmpty() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%snotEmpty%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getNotEmpty()))));
    }

    // add `server` to the URL query string
    if (getServer() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sserver%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getServer()))));
    }

    // add `isError` to the URL query string
    if (getIsError() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sisError%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getIsError()))));
    }

    // add `errorStr` to the URL query string
    if (getErrorStr() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%serrorStr%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getErrorStr()))));
    }

    // add `msgDirectionType` to the URL query string
    if (getMsgDirectionType() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%smsgDirectionType%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getMsgDirectionType()))));
    }

    // add `entityId` to the URL query string
    if (getEntityId() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sentityId%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getEntityId()))));
    }

    // add `entityType` to the URL query string
    if (getEntityType() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sentityType%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getEntityType()))));
    }

    // add `msgId` to the URL query string
    if (getMsgId() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%smsgId%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getMsgId()))));
    }

    // add `msgType` to the URL query string
    if (getMsgType() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%smsgType%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getMsgType()))));
    }

    // add `relationType` to the URL query string
    if (getRelationType() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%srelationType%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getRelationType()))));
    }

    // add `dataSearch` to the URL query string
    if (getDataSearch() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sdataSearch%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getDataSearch()))));
    }

    // add `metadataSearch` to the URL query string
    if (getMetadataSearch() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%smetadataSearch%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getMetadataSearch()))));
    }

    return joiner.toString();
  }
static {
  // Initialize and register the discriminator mappings.
  Map<String, Class<?>> mappings = new HashMap<String, Class<?>>();
  mappings.put("RuleNodeDebugEventFilter", RuleNodeDebugEventFilter.class);
  JSON.registerDiscriminator(RuleNodeDebugEventFilter.class, "eventType", mappings);
}
}

