/**
 * Copyright © 2026-2026 ThingsBoard, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.thingsboard.client.model;

import javax.annotation.Generated;
import javax.annotation.Nullable;
import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.thingsboard.client.model.SnmpCommunicationConfig;
import org.thingsboard.client.model.SnmpCommunicationSpec;
import org.thingsboard.client.model.SnmpMapping;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import org.thingsboard.client.JSON;
import org.thingsboard.client.ApiClient;
/**
 * TelemetryQueryingSnmpCommunicationConfig
 */
@JsonPropertyOrder({
  TelemetryQueryingSnmpCommunicationConfig.JSON_PROPERTY_MAPPINGS,
  TelemetryQueryingSnmpCommunicationConfig.JSON_PROPERTY_QUERYING_FREQUENCY_MS
})
@Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.20.0")
@JsonIgnoreProperties(
  value = "spec", // ignore manually set spec, it will be automatically generated by Jackson during serialization
  allowSetters = true // allows the spec to be set during deserialization
)
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "spec", visible = true)

public class TelemetryQueryingSnmpCommunicationConfig extends SnmpCommunicationConfig {
  public static final String JSON_PROPERTY_MAPPINGS = "mappings";
  @Nullable
  private List<SnmpMapping> mappings = new ArrayList<>();

  public static final String JSON_PROPERTY_QUERYING_FREQUENCY_MS = "queryingFrequencyMs";
  @Nullable
  private Long queryingFrequencyMs;

  public TelemetryQueryingSnmpCommunicationConfig() { 
  }

  public TelemetryQueryingSnmpCommunicationConfig mappings(@Nullable List<SnmpMapping> mappings) {
    this.mappings = mappings;
    return this;
  }

  public TelemetryQueryingSnmpCommunicationConfig addMappingsItem(SnmpMapping mappingsItem) {
    if (this.mappings == null) {
      this.mappings = new ArrayList<>();
    }
    this.mappings.add(mappingsItem);
    return this;
  }

  /**
   * Get mappings
   * @return mappings
   */
  @Nullable
  @JsonProperty(value = JSON_PROPERTY_MAPPINGS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public List<SnmpMapping> getMappings() {
    return mappings;
  }


  @JsonProperty(value = JSON_PROPERTY_MAPPINGS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMappings(@Nullable List<SnmpMapping> mappings) {
    this.mappings = mappings;
  }


  public TelemetryQueryingSnmpCommunicationConfig queryingFrequencyMs(@Nullable Long queryingFrequencyMs) {
    this.queryingFrequencyMs = queryingFrequencyMs;
    return this;
  }

  /**
   * Get queryingFrequencyMs
   * @return queryingFrequencyMs
   */
  @Nullable
  @JsonProperty(value = JSON_PROPERTY_QUERYING_FREQUENCY_MS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Long getQueryingFrequencyMs() {
    return queryingFrequencyMs;
  }


  @JsonProperty(value = JSON_PROPERTY_QUERYING_FREQUENCY_MS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setQueryingFrequencyMs(@Nullable Long queryingFrequencyMs) {
    this.queryingFrequencyMs = queryingFrequencyMs;
  }


  /**
   * Return true if this TelemetryQueryingSnmpCommunicationConfig object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TelemetryQueryingSnmpCommunicationConfig telemetryQueryingSnmpCommunicationConfig = (TelemetryQueryingSnmpCommunicationConfig) o;
    return Objects.equals(this.mappings, telemetryQueryingSnmpCommunicationConfig.mappings) &&
        Objects.equals(this.queryingFrequencyMs, telemetryQueryingSnmpCommunicationConfig.queryingFrequencyMs) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(mappings, queryingFrequencyMs, super.hashCode());
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TelemetryQueryingSnmpCommunicationConfig {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    mappings: ").append(toIndentedString(mappings)).append("\n");
    sb.append("    queryingFrequencyMs: ").append(toIndentedString(queryingFrequencyMs)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `spec` to the URL query string
    if (getSpec() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sspec%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getSpec()))));
    }

    // add `mappings` to the URL query string
    if (getMappings() != null) {
      for (int i = 0; i < getMappings().size(); i++) {
        if (getMappings().get(i) != null) {
          joiner.add(getMappings().get(i).toUrlQueryString(String.format(java.util.Locale.ROOT, "%smappings%s%s", prefix, suffix,
          "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix))));
        }
      }
    }

    // add `queryingFrequencyMs` to the URL query string
    if (getQueryingFrequencyMs() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%squeryingFrequencyMs%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getQueryingFrequencyMs()))));
    }

    return joiner.toString();
  }
static {
  // Initialize and register the discriminator mappings.
  Map<String, Class<?>> mappings = new HashMap<String, Class<?>>();
  mappings.put("TelemetryQueryingSnmpCommunicationConfig", TelemetryQueryingSnmpCommunicationConfig.class);
  JSON.registerDiscriminator(TelemetryQueryingSnmpCommunicationConfig.class, "spec", mappings);
}
}

