/**
 * Copyright © 2026-2026 ThingsBoard, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.thingsboard.client.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.thingsboard.client.model.DataSource;
import org.thingsboard.client.model.ImageAlignment;
import org.thingsboard.client.model.ImageWidthType;
import org.thingsboard.client.model.Insets;
import org.thingsboard.client.model.ReportComponent;
import org.thingsboard.client.model.ReportComponentSubType;
import org.thingsboard.client.model.ReportComponentType;
import org.thingsboard.client.model.ReportTimeSeriesChartSettings;
import org.thingsboard.client.model.TimeWindowConfiguration;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import org.thingsboard.client.JSON;
import org.thingsboard.client.ApiClient;
/**
 * TimeseriesChartComponent
 */
@JsonPropertyOrder({
  TimeseriesChartComponent.JSON_PROPERTY_DATA_SOURCES,
  TimeseriesChartComponent.JSON_PROPERTY_MARGINS,
  TimeseriesChartComponent.JSON_PROPERTY_PADDINGS,
  TimeseriesChartComponent.JSON_PROPERTY_BACKGROUND,
  TimeseriesChartComponent.JSON_PROPERTY_BORDER_WIDTH,
  TimeseriesChartComponent.JSON_PROPERTY_BORDER_RADIUS,
  TimeseriesChartComponent.JSON_PROPERTY_BORDER_COLOR,
  TimeseriesChartComponent.JSON_PROPERTY_WIDTH_TYPE,
  TimeseriesChartComponent.JSON_PROPERTY_CUSTOM_WIDTH,
  TimeseriesChartComponent.JSON_PROPERTY_ALIGNMENT,
  TimeseriesChartComponent.JSON_PROPERTY_HEIGHT,
  TimeseriesChartComponent.JSON_PROPERTY_TIMEWINDOW,
  TimeseriesChartComponent.JSON_PROPERTY_TIME_SERIES_CHART_SETTINGS
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.20.0")
@JsonIgnoreProperties(
  value = "type", // ignore manually set type, it will be automatically generated by Jackson during serialization
  allowSetters = true // allows the type to be set during deserialization
)
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "type", visible = true)

public class TimeseriesChartComponent extends ReportComponent {
  public static final String JSON_PROPERTY_DATA_SOURCES = "dataSources";
  @javax.annotation.Nullable
  private List<DataSource> dataSources = new ArrayList<>();

  public static final String JSON_PROPERTY_MARGINS = "margins";
  @javax.annotation.Nullable
  private Insets margins;

  public static final String JSON_PROPERTY_PADDINGS = "paddings";
  @javax.annotation.Nullable
  private Insets paddings;

  public static final String JSON_PROPERTY_BACKGROUND = "background";
  @javax.annotation.Nullable
  private String background;

  public static final String JSON_PROPERTY_BORDER_WIDTH = "borderWidth";
  @javax.annotation.Nullable
  private Integer borderWidth;

  public static final String JSON_PROPERTY_BORDER_RADIUS = "borderRadius";
  @javax.annotation.Nullable
  private Integer borderRadius;

  public static final String JSON_PROPERTY_BORDER_COLOR = "borderColor";
  @javax.annotation.Nullable
  private String borderColor;

  public static final String JSON_PROPERTY_WIDTH_TYPE = "widthType";
  @javax.annotation.Nullable
  private ImageWidthType widthType;

  public static final String JSON_PROPERTY_CUSTOM_WIDTH = "customWidth";
  @javax.annotation.Nullable
  private Integer customWidth;

  public static final String JSON_PROPERTY_ALIGNMENT = "alignment";
  @javax.annotation.Nullable
  private ImageAlignment alignment;

  public static final String JSON_PROPERTY_HEIGHT = "height";
  @javax.annotation.Nullable
  private Integer height;

  public static final String JSON_PROPERTY_TIMEWINDOW = "timewindow";
  @javax.annotation.Nullable
  private TimeWindowConfiguration timewindow;

  public static final String JSON_PROPERTY_TIME_SERIES_CHART_SETTINGS = "timeSeriesChartSettings";
  @javax.annotation.Nullable
  private ReportTimeSeriesChartSettings timeSeriesChartSettings;

  public TimeseriesChartComponent() { 
  }

  public TimeseriesChartComponent dataSources(@javax.annotation.Nullable List<DataSource> dataSources) {
    this.dataSources = dataSources;
    return this;
  }

  public TimeseriesChartComponent addDataSourcesItem(DataSource dataSourcesItem) {
    if (this.dataSources == null) {
      this.dataSources = new ArrayList<>();
    }
    this.dataSources.add(dataSourcesItem);
    return this;
  }

  /**
   * Get dataSources
   * @return dataSources
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_DATA_SOURCES, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public List<DataSource> getDataSources() {
    return dataSources;
  }


  @JsonProperty(value = JSON_PROPERTY_DATA_SOURCES, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDataSources(@javax.annotation.Nullable List<DataSource> dataSources) {
    this.dataSources = dataSources;
  }


  public TimeseriesChartComponent margins(@javax.annotation.Nullable Insets margins) {
    this.margins = margins;
    return this;
  }

  /**
   * Get margins
   * @return margins
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_MARGINS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Insets getMargins() {
    return margins;
  }


  @JsonProperty(value = JSON_PROPERTY_MARGINS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMargins(@javax.annotation.Nullable Insets margins) {
    this.margins = margins;
  }


  public TimeseriesChartComponent paddings(@javax.annotation.Nullable Insets paddings) {
    this.paddings = paddings;
    return this;
  }

  /**
   * Get paddings
   * @return paddings
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PADDINGS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Insets getPaddings() {
    return paddings;
  }


  @JsonProperty(value = JSON_PROPERTY_PADDINGS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPaddings(@javax.annotation.Nullable Insets paddings) {
    this.paddings = paddings;
  }


  public TimeseriesChartComponent background(@javax.annotation.Nullable String background) {
    this.background = background;
    return this;
  }

  /**
   * Get background
   * @return background
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_BACKGROUND, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getBackground() {
    return background;
  }


  @JsonProperty(value = JSON_PROPERTY_BACKGROUND, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setBackground(@javax.annotation.Nullable String background) {
    this.background = background;
  }


  public TimeseriesChartComponent borderWidth(@javax.annotation.Nullable Integer borderWidth) {
    this.borderWidth = borderWidth;
    return this;
  }

  /**
   * Get borderWidth
   * @return borderWidth
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_BORDER_WIDTH, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Integer getBorderWidth() {
    return borderWidth;
  }


  @JsonProperty(value = JSON_PROPERTY_BORDER_WIDTH, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setBorderWidth(@javax.annotation.Nullable Integer borderWidth) {
    this.borderWidth = borderWidth;
  }


  public TimeseriesChartComponent borderRadius(@javax.annotation.Nullable Integer borderRadius) {
    this.borderRadius = borderRadius;
    return this;
  }

  /**
   * Get borderRadius
   * @return borderRadius
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_BORDER_RADIUS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Integer getBorderRadius() {
    return borderRadius;
  }


  @JsonProperty(value = JSON_PROPERTY_BORDER_RADIUS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setBorderRadius(@javax.annotation.Nullable Integer borderRadius) {
    this.borderRadius = borderRadius;
  }


  public TimeseriesChartComponent borderColor(@javax.annotation.Nullable String borderColor) {
    this.borderColor = borderColor;
    return this;
  }

  /**
   * Get borderColor
   * @return borderColor
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_BORDER_COLOR, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getBorderColor() {
    return borderColor;
  }


  @JsonProperty(value = JSON_PROPERTY_BORDER_COLOR, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setBorderColor(@javax.annotation.Nullable String borderColor) {
    this.borderColor = borderColor;
  }


  public TimeseriesChartComponent widthType(@javax.annotation.Nullable ImageWidthType widthType) {
    this.widthType = widthType;
    return this;
  }

  /**
   * Get widthType
   * @return widthType
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_WIDTH_TYPE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public ImageWidthType getWidthType() {
    return widthType;
  }


  @JsonProperty(value = JSON_PROPERTY_WIDTH_TYPE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setWidthType(@javax.annotation.Nullable ImageWidthType widthType) {
    this.widthType = widthType;
  }


  public TimeseriesChartComponent customWidth(@javax.annotation.Nullable Integer customWidth) {
    this.customWidth = customWidth;
    return this;
  }

  /**
   * Get customWidth
   * @return customWidth
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CUSTOM_WIDTH, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Integer getCustomWidth() {
    return customWidth;
  }


  @JsonProperty(value = JSON_PROPERTY_CUSTOM_WIDTH, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCustomWidth(@javax.annotation.Nullable Integer customWidth) {
    this.customWidth = customWidth;
  }


  public TimeseriesChartComponent alignment(@javax.annotation.Nullable ImageAlignment alignment) {
    this.alignment = alignment;
    return this;
  }

  /**
   * Get alignment
   * @return alignment
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ALIGNMENT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public ImageAlignment getAlignment() {
    return alignment;
  }


  @JsonProperty(value = JSON_PROPERTY_ALIGNMENT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAlignment(@javax.annotation.Nullable ImageAlignment alignment) {
    this.alignment = alignment;
  }


  public TimeseriesChartComponent height(@javax.annotation.Nullable Integer height) {
    this.height = height;
    return this;
  }

  /**
   * Get height
   * @return height
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_HEIGHT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Integer getHeight() {
    return height;
  }


  @JsonProperty(value = JSON_PROPERTY_HEIGHT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setHeight(@javax.annotation.Nullable Integer height) {
    this.height = height;
  }


  public TimeseriesChartComponent timewindow(@javax.annotation.Nullable TimeWindowConfiguration timewindow) {
    this.timewindow = timewindow;
    return this;
  }

  /**
   * Get timewindow
   * @return timewindow
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TIMEWINDOW, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public TimeWindowConfiguration getTimewindow() {
    return timewindow;
  }


  @JsonProperty(value = JSON_PROPERTY_TIMEWINDOW, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTimewindow(@javax.annotation.Nullable TimeWindowConfiguration timewindow) {
    this.timewindow = timewindow;
  }


  public TimeseriesChartComponent timeSeriesChartSettings(@javax.annotation.Nullable ReportTimeSeriesChartSettings timeSeriesChartSettings) {
    this.timeSeriesChartSettings = timeSeriesChartSettings;
    return this;
  }

  /**
   * Get timeSeriesChartSettings
   * @return timeSeriesChartSettings
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TIME_SERIES_CHART_SETTINGS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public ReportTimeSeriesChartSettings getTimeSeriesChartSettings() {
    return timeSeriesChartSettings;
  }


  @JsonProperty(value = JSON_PROPERTY_TIME_SERIES_CHART_SETTINGS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTimeSeriesChartSettings(@javax.annotation.Nullable ReportTimeSeriesChartSettings timeSeriesChartSettings) {
    this.timeSeriesChartSettings = timeSeriesChartSettings;
  }


  @Override
  public TimeseriesChartComponent subType(@javax.annotation.Nonnull ReportComponentSubType subType) {
    this.setSubType(subType);
    return this;
  }

  @Override
  public TimeseriesChartComponent type(@javax.annotation.Nonnull ReportComponentType type) {
    this.setType(type);
    return this;
  }

  /**
   * Return true if this TimeseriesChartComponent object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TimeseriesChartComponent timeseriesChartComponent = (TimeseriesChartComponent) o;
    return Objects.equals(this.dataSources, timeseriesChartComponent.dataSources) &&
        Objects.equals(this.margins, timeseriesChartComponent.margins) &&
        Objects.equals(this.paddings, timeseriesChartComponent.paddings) &&
        Objects.equals(this.background, timeseriesChartComponent.background) &&
        Objects.equals(this.borderWidth, timeseriesChartComponent.borderWidth) &&
        Objects.equals(this.borderRadius, timeseriesChartComponent.borderRadius) &&
        Objects.equals(this.borderColor, timeseriesChartComponent.borderColor) &&
        Objects.equals(this.widthType, timeseriesChartComponent.widthType) &&
        Objects.equals(this.customWidth, timeseriesChartComponent.customWidth) &&
        Objects.equals(this.alignment, timeseriesChartComponent.alignment) &&
        Objects.equals(this.height, timeseriesChartComponent.height) &&
        Objects.equals(this.timewindow, timeseriesChartComponent.timewindow) &&
        Objects.equals(this.timeSeriesChartSettings, timeseriesChartComponent.timeSeriesChartSettings) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(dataSources, margins, paddings, background, borderWidth, borderRadius, borderColor, widthType, customWidth, alignment, height, timewindow, timeSeriesChartSettings, super.hashCode());
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TimeseriesChartComponent {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    dataSources: ").append(toIndentedString(dataSources)).append("\n");
    sb.append("    margins: ").append(toIndentedString(margins)).append("\n");
    sb.append("    paddings: ").append(toIndentedString(paddings)).append("\n");
    sb.append("    background: ").append(toIndentedString(background)).append("\n");
    sb.append("    borderWidth: ").append(toIndentedString(borderWidth)).append("\n");
    sb.append("    borderRadius: ").append(toIndentedString(borderRadius)).append("\n");
    sb.append("    borderColor: ").append(toIndentedString(borderColor)).append("\n");
    sb.append("    widthType: ").append(toIndentedString(widthType)).append("\n");
    sb.append("    customWidth: ").append(toIndentedString(customWidth)).append("\n");
    sb.append("    alignment: ").append(toIndentedString(alignment)).append("\n");
    sb.append("    height: ").append(toIndentedString(height)).append("\n");
    sb.append("    timewindow: ").append(toIndentedString(timewindow)).append("\n");
    sb.append("    timeSeriesChartSettings: ").append(toIndentedString(timeSeriesChartSettings)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `subType` to the URL query string
    if (getSubType() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%ssubType%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getSubType()))));
    }

    // add `type` to the URL query string
    if (getType() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%stype%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getType()))));
    }

    // add `dataSources` to the URL query string
    if (getDataSources() != null) {
      for (int i = 0; i < getDataSources().size(); i++) {
        if (getDataSources().get(i) != null) {
          joiner.add(getDataSources().get(i).toUrlQueryString(String.format(java.util.Locale.ROOT, "%sdataSources%s%s", prefix, suffix,
          "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix))));
        }
      }
    }

    // add `margins` to the URL query string
    if (getMargins() != null) {
      joiner.add(getMargins().toUrlQueryString(prefix + "margins" + suffix));
    }

    // add `paddings` to the URL query string
    if (getPaddings() != null) {
      joiner.add(getPaddings().toUrlQueryString(prefix + "paddings" + suffix));
    }

    // add `background` to the URL query string
    if (getBackground() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sbackground%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getBackground()))));
    }

    // add `borderWidth` to the URL query string
    if (getBorderWidth() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sborderWidth%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getBorderWidth()))));
    }

    // add `borderRadius` to the URL query string
    if (getBorderRadius() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sborderRadius%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getBorderRadius()))));
    }

    // add `borderColor` to the URL query string
    if (getBorderColor() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sborderColor%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getBorderColor()))));
    }

    // add `widthType` to the URL query string
    if (getWidthType() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%swidthType%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getWidthType()))));
    }

    // add `customWidth` to the URL query string
    if (getCustomWidth() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%scustomWidth%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getCustomWidth()))));
    }

    // add `alignment` to the URL query string
    if (getAlignment() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%salignment%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getAlignment()))));
    }

    // add `height` to the URL query string
    if (getHeight() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sheight%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getHeight()))));
    }

    // add `timewindow` to the URL query string
    if (getTimewindow() != null) {
      joiner.add(getTimewindow().toUrlQueryString(prefix + "timewindow" + suffix));
    }

    // add `timeSeriesChartSettings` to the URL query string
    if (getTimeSeriesChartSettings() != null) {
      joiner.add(getTimeSeriesChartSettings().toUrlQueryString(prefix + "timeSeriesChartSettings" + suffix));
    }

    return joiner.toString();
  }
static {
  // Initialize and register the discriminator mappings.
  Map<String, Class<?>> mappings = new HashMap<String, Class<?>>();
  mappings.put("TimeseriesChartComponent", TimeseriesChartComponent.class);
  JSON.registerDiscriminator(TimeseriesChartComponent.class, "type", mappings);
}
}

